dpctl/tensor/CMakeLists.txt
In our internal inquiries we also encountered DPC++ RT bringing up the need to use this option. So here it goes.
Resolves gh-1184
=> Use -fno-sycl-id-queries-fit-in-int to resolve gh-1184

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
This PR implements request for quality-of-life properties of usm_ndarray requested in gh-1192. It adds ``usm_ndarray._element_offset`` and ``usm_ndarray._byte_bounds``.
The `_element_offset` gives the offset of the start of array from the beginning of the start of allocation in elements.
`_byte_bounds` gives the tuple with addresses of end-points of the array. Not every memory element in between the end-points may be addressed by indexing.
```
In [2]: dpt.empty(10)[5:]._element_offset
Out[2]: 5
In [3]: dpt.empty(10)[5:]._byte_bounds
Out[3]: (18446664917462351892, 18446664917462351912)
In [4]: _[1] - _[0]
Out[4]: 20
In [5]: dpt.empty(10)[5:].itemsize
Out[5]: 4
```
Tests are added. This PR resolves gh-1192
=> Implement QOL properties of usm_ndarray

dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/simplify_iteration_space.cpp, dpctl/tests/test_usm_ndarray_ctor.py
This PR fixes issues in `simplify_iteration_space*` functions introduced in gh-1198.
It also corrects calculation of numpy array byte-boundaries to form `sycl::buffer` accessing
content of NumPy's array from a SYCL kernel.
Closes gh-1201
=> Fixed regression in iteration space simplifier, fixed arguments of numpy to usm_ndarray copying function 

dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
Using multiple host_tasks when copying metadata to device has shown to cause crashes on CPU.
This PR addresses the issue by reducing the number of calls to device_allocate_and_pack.
=> Refactored boolean advanced indexing host tasks

dpctl/tensor/CMakeLists.txt, dpctl/tensor/__init__.py, dpctl/tensor/_utility_functions.py, dpctl/tensor/libtensor/include/kernels/boolean_reductions.hpp, dpctl/tensor/libtensor/source/boolean_reductions.cpp, dpctl/tensor/libtensor/source/boolean_reductions.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_usm_ndarray_utility_functions.py
This pull request implements ``dpctl.tensor.all`` and ``dpctl.tensor.any``.
=> Implements dpctl.tensor.any and dpctl.tensor.all

.github/workflows/conda-package.yml, conda-recipe/meta.yaml, conda-recipe/run_test.sh
Update meta.yaml to require sysroot_linux-64 >=2.28, and use dppy/label/tools to get it until it comes online from conda-forge
The sysroot packages are from https://github.com/conda-forge/linux-sysroot-feedstock/pull/47, built locally and uploaded to dppy/label/tools for the purpose on unblocking the build.
**N.B.**: This PR is into feature/elementwise-functions which is presently broken due to default sysroot version, 2.17, is below the minimum version [required](https://www.intel.com/content/www/us/en/developer/articles/system-requirements/intel-oneapi-dpcpp-system-requirements.html) by DPC++. See gh-1203
=> Try using sysroot 2.28

dpctl/tensor/__init__.py, dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sqrt.hpp, dpctl/tensor/libtensor/source/elementwise_functions.cpp, dpctl/tests/test_tensor_sqrt.py
This pull request implements dpctl.tensor.sqrt using the simplified ufunc interface.
=> Implements dpctl.tensor.sqrt

.github/workflows/conda-package.yml, .github/workflows/generate-coverage.yaml, .github/workflows/os-llvm-sycl-build.yml
This PR changes workflows to use ``SYCL_QUEUE_THREAD_POOL_SIZE=6`` to stabilize sporadic crashes in the CI on CPU.
Also changes the array API conformity workflow to fail when array API conformity tests fail to run (i.e., when no JSON report is generated).
=> Changes to workflows to stabilize tests on CPU

MANIFEST.in, cmake/FindDpctl.cmake, dpctl/__main__.py
The PR proposes to include header files from tensor library into dpctl conda package.
The headers will be installed by path:
```
${CONDA_PREFIX}/site-packages/dpctl/tensor/libtensor/include
```
=> Add headers from tensor lib to conda package

dpctl/tensor/_elementwise_common.py, dpctl/tests/elementwise/test_multiply.py
Resolves #1219 
Changes ``_resolve_weak_types`` to handle complex scalars properly and adds a test for the issue/fix.
=> Fixes incorrect result when multiplying real array and complex scalar

dpctl/tensor/_elementwise_common.py, dpctl/tests/elementwise/test_multiply.py
Fixed behavior of mathematical functions for floating-point and complex floating-point scalars.
Added test.
Resolves https://github.com/IntelPython/dpctl/issues/1219
Resolves https://github.com/IntelPython/dpnp/issues/1304
=> Fixed behavior of mathematical functions for scalars.

dpctl/tensor/_reduction.py, dpctl/tests/test_tensor_sum.py
This PR changes a bit the behavior for  `dpctl.tensor.sum` function for scalars. 
The previous implementation always returned `dpt.zeros` for zero-dimensions of the input array and worked incorrectly for scalars. According to the Python Array API: `If N is 0, the sum is 0 (i.e., the empty sum)` [[sum](https://data-apis.org/array-api/2022.12/API_specification/generated/array_api.sum.html?highlight=sum)]. 
Now if  `dpctl.tensor.sum` takes a scalar it returns a scalar has the same behavior as numpy
```
#old impl
a = dpt.asarray(1)
dpt.sum(a)
usm_ndarray(0., dtype=float32)
a = dpt.asarray(())
dpt.sum(a)
usm_ndarray(0., dtype=float32)
#new impl
a = dpt.asarray(1)
dpt.sum(a)
usm_ndarray(1., dtype=float32)
a = dpt.asarray(())
dpt.sum(a)
usm_ndarray(0., dtype=float32)
```
=> Fix dpctl.tensor.sum for support zero-dimensional array

dpctl/tensor/_elementwise_common.py, dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_usmarray.pyx, dpctl/tensor/libtensor/include/kernels/elementwise_functions/add.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/multiply.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/subtract.hpp, dpctl/tensor/libtensor/source/elementwise_functions.cpp, dpctl/tensor/libtensor/source/elementwise_functions.hpp, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_multiply.py, dpctl/tests/elementwise/test_subtract.py
Closes #1229 
This pull request implements in-place addition, subtraction, and multiplication of ``usm_ndarray`` instances.
By avoiding the additional allocation of an output array, the performance advantage compared compared to applying the operator with a scalar, a la ``dpt.add(x, 2)``, is considerable.
For example:
```
In [8]: X = dpt.ones((16768, 16768), dtype="f4")
In [9]: %time X += 2
CPU times: user 58.5 ms, sys: 78.1 ms, total: 137 ms
Wall time: 133 ms
In [10]: %time dpt.add(X, 2)
CPU times: user 238 ms, sys: 147 ms, total: 385 ms
Wall time: 392 ms
```
=> In-place addition, multiplication, subtraction of usm_ndarrays

dpctl/tensor/_elementwise_funcs.py
This PR adjusts the wording of the documentation for comparison functions ``dpctl.tensor.less``, ``dpctl.tensor.less_equal``, ``dpctl.tensor.greater``, ``dpctl.tensor.greater_equal``.
=> Adjusts wording of comparison function docs

dpctl/tensor/libtensor/include/kernels/elementwise_functions/add.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/multiply.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/not_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/subtract.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/true_divide.hpp, dpctl/tensor/libtensor/source/elementwise_functions.cpp, dpctl/tensor/libtensor/source/elementwise_functions.hpp, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_multiply.py, dpctl/tests/elementwise/test_subtract.py
This PR significant improves the performance of in-place operations between C-contiguous rows and C-contiguous matrices by implementing a variant kernel similar to that which is used for standard binary operations.
=> Optimized in-place operators for rows and matrices

dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.hpp
Changes preambles for ``common_inplace.hpp``, ``kernels/boolean_advanced_indexing.hpp``, ``source/integer_advanced_indexing.hpp``, and ``integer_advanced_indexing.cpp`` to the correct filename and description.
=> Correct libtensor preambles

dpctl/tests/test_dparray.py
With this PR, all tests for the numpy_usm_shared module are now skipped pending eventual removal.
This also fixes the coverage CI, which currently fails due to changes in Numpy 1.25.0 that break tests for the numpy_usm_shared module.
=> skip numpy_usm_shared tests

libsyclinterface/helper/source/dpctl_error_handlers.cpp
This RP refactors `requested_verbosity_level` function to solve #1246 and suggest the usage of  `_dupenv_s` for Windows by conditional compilation.
=> Use _depenv_s in libsyclinterface on Windows

dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp, dpctl/tests/elementwise/test_floor_divide.py
Resolves #1247
This PR changes the behavior of dpctl.tensor.floor_divide to round the result of division between signed integers toward negative infinity rather than toward 0 (as is the norm in C++).
=> Round signed integers toward negative infinity in dpctl.tensor.floor_divide

dpctl/tensor/_copy_utils.py, dpctl/tests/test_usm_ndarray_ctor.py
This PR makes minor changes to `dpctl.tensor.astype` function by replacing the getting `target_dtype`. 
The old implementation did not consider whether the device where input array is allocated supported double-precision floating point types and returned `float64` for `None` type which raised `ValueError`. 
```
a = dpt.asarray([1, 1, 1], dtype='i4')
dpt.astype(a, None)
ValueError: Device Intel(R) Graphics [0x46a6] does not provide native support 
for double-precision floating point type.
```
This PR uses `_get_dtype`  function from dpctl.tensor._ctors which fixes wrong behavior. 
For `None` returns default floating point type supported by device.
For all other types returns `dpt.dtype(dtype)`
=> Return default floating point type of the device in dpctl.tensor.astype when newdtype=None

dpctl/tensor/_ctors.py, dpctl/tests/test_usm_ndarray_ctor.py
Resolves #1230 
This PR adjusts how integer overflow and underflow is handled by ``dpctl.tensor.full``.
Previously, when an integer that would overflow the type of array in the result of ``full`` was passed in as ``fill_value``, an exception would be thrown by pybind11.
Now, ``_to_scalar`` is used to get fill value back after it has been converted to a Numpy scalar, which brings the value into the range of the type and allows pybind11 to unpack the scalar.
=> Fix out of bounds integer behavior in dpctl.tensor.full

.github/workflows/os-llvm-sycl-build.yml
Update workflow building `dpctl` with OS LLVM nightly builds to use latest CPU/FPGA_EMU drivers (https://github.com/intel/llvm/releases/tag/2023-WW27)
=> Use latest CPU/fpga driver published on intel/llvm

dpctl/tensor/libtensor/include/kernels/elementwise_functions/proj.hpp, dpctl/tests/elementwise/test_complex.py
Closes gh-1275
This PR modifies the kernel associated with `dpctl.tensor.proj` to avoid using literal constants of type `double` to allow compilation for hardware without fp64 support.
Modified test `test_complex.py::test_complex_output` to pass on such HW as well.
=> Fix failure of proj to JIT-compile associated kernel on HW without fp64-support 

.github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/libtensor/include/kernels/boolean_reductions.hpp
This PR pins specific, last known to work, version of SYCLOS compiler instead of using the latest nightly build.
Reproducer has been filed for the compiler team to investigate.
=> Pin SYCLOS_Nightly version used

dpctl/tensor/_copy_utils.py
```
In [1]: import dpctl.tensor as dpt, dpctl, dpctl.utils
In [2]: n, m = 8 * 540, 8 * 960
In [3]: a = dpt.ones((m, n))
In [4]: b = dpt.zeros((m, n))
In [5]: b_s = dpt.zeros((m, n+2))
In [6]: with dpctl.utils.onetrace_enabled():
...:     b_s[:,:-2] += a
...:
Device Timeline (queue: 0x556080b9cea0): zeCommandListAppendMemoryCopy(H2D)[48 bytes]<4.1> [ns] = 16946404661 (append) 16952292497 (submit) 16952613747 (start) 16952623538 (end)
Device Timeline (queue: 0x556080b9cea0): dpctl::tensor::kernels::add::add_inplace_strided_kernel<float, float, dpctl::tensor::offset_utils::TwoOffsets_StridedIndexer>[SIMD32 {64800; 1; 1} {512; 1; 1}]<5.1> [ns] = 17017855801 (append) 17018342202 (submit) 17019138920 (start) 17030770482 (end)
```
Earlier, two more copy operations were being performed as well. …
=> No need to call _copy_overlapping if src and dst address same memory

.github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml, conda-recipe/meta.yaml, dpctl/tensor/_elementwise_common.py, dpctl/tensor/libtensor/include/utils/memory_overlap.hpp, dpctl/tensor/libtensor/source/elementwise_functions.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/_numpy_warnings.py, dpctl/tests/elementwise/test_abs.py, dpctl/tests/elementwise/test_exp.py, dpctl/tests/elementwise/test_log.py, dpctl/tests/elementwise/test_sincos.py, dpctl/tests/elementwise/test_sqrt.py, dpctl/tests/elementwise/test_square.py, setup.py
The PR proposes to allocate a temporary buffer rather than to raise an exception in case when the memory overlapping is detected between `in` and `out` arrays in a call of unary function.
The changed is intended to have the below code example as a valid:
```
a = dpt.arange(10, dtype='f4')
_ = dpt.sqrt(a, out=a)
```
The approach with temporary buffer was chosen as a start point while integrating support of the use case, since it is easiest way to implement this.
The next step might be to add separate kernels to handle in-place unary operations (when both `in` and `out` arrays point to the same memory) if the performance gain would be sensible.
=> Created a temporary copy in case of overlap for unary function

dpctl/tests/test_sycl_kernel_submit.py
test_sycl_kernel_submit::test_async_submit sporadically fails on Windows where in kernels finish execution before test checks are done. Typical remedy is to restart Windows tests and after few iterations they pass.
This PR changes the tests to attempt launching kernels few times and rechecking tests condition before asserting test failure.
=> test_async_submit is to try few times before failing

dpctl/tests/elementwise/test_floor_ceil_trunc.py
Since support for overlapping out and argument arrays has been added the expected TypeError is no longer raised.
Do not use `np.float32(usm_ndarray)` use-pattern, use `dpt.asnumpy(usm_ndarray)` instead. The former generates usm_ndarray.size single-element device-to-host transfers, while the latter does it in a single kernel invocation.
=> Fixed failure of test_floor_ceil_trunc_errors, sped up usm_type test

dpctl/tensor/_reduction.py, dpctl/tests/test_tensor_sum.py
Closes gh-1293
This PR adds handling of `keepdims=True` case for special-case early exit for zero-size input.
=> Fix gh-1293 for sum over zero-size array with keepdims set

.github/workflows/conda-package.yml, conda-recipe/build.sh
Add package build for python 3.11
I've been able to successfully build it for `numba-dpex` Docker. All tests pass
=> Add python 3.11 support

setup.py
This is mapping  of #1269 to gold/2021 branch
=> Add metadata to setup.py

dpctl/tests/test_sycl_kernel_submit.py
`test_sycl_kernel_submit.py::test_async_submit` has been sporadically failing as it attempts to confirm that concurrency was indeed detected. The chance of such detection decreases on beefier machines. 
This PR selects global-work-size for the submitted kernels based on device's max_work_group_size property, and increases it few times before failing the test. 
This change should reduce the need to restart failing jobs just to get this test to pass.
=> Test async changes

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/exp.hpp, dpctl/tests/elementwise/test_complex.py, dpctl/tests/elementwise/test_exp.py
In this PR, tests for `dpctl.tensor.exp`, `dpctl.tensor.real`, `dpctl.tensor.imag`, and `dpctl.tensor.conj` are updated. Implementation of `dpt.exp` is also modified to handle special cases for floating-point complex numbers correctly. Moreover, doc-strings are modified.
=> update elementwise tests for exp, real, imag, and conj

dpctl/tensor/libtensor/include/utils/offset_utils.hpp, dpctl/tensor/libtensor/include/utils/strided_iters.hpp
This PR implements fixed-dimensionality indexer for three offsets. These are useful for writing dpctl-based extensions.
=> Added fixed dimensions indexer for three offsets

dpctl/tensor/libtensor/include/utils/strided_iters.hpp
When simplifying iteration space, first consider strides of output array (last stride argument) since output arrays should never have zero strides.
```
In [4]: from dpctl.tensor._tensor_impl import _contract_iter3
In [5]: sh, st1, st2, st3 = (8192, 8192), (0, 1), (1, 0), (8192, 1) # shape, strides in issue
In [6]: _contract_iter3(sh, st1, st2, st3)
Out[6]: ([8192, 8192], [0, 1], 0, [1, 0], 0, [8192, 1], 0)
In [7]: _contract_iter3(sh, st2, st1, st3)
Out[7]: ([8192, 8192], [1, 0], 0, [0, 1], 0, [8192, 1], 0)
```
=> Closes gh-1250 by fixing stride simplification logic

conda-recipe/meta.yaml
`libSyclInterface.so` library compiled with DPC++ 2023.2 compiler requires DPC++ compiler runtime 2023.2. as evidenced by this import error encountered by @AlexanderKalistratov :
```
ImportError: /home/akalistr/miniconda3/envs/dpbench-dev/lib/python3.10/site-packages/dpctl/libDPCTLSyclInterface.so.0: undefined symbol: _ZN4sycl3_V16detail14tls_code_loc_tC1ERKNS1_13code_locationE
```
=> Require 2023.2 compiler package and runtime

dpctl/tests/elementwise/test_log.py
Changed tests to avoid `RuntimeErrors` issued by NumPy for numerical exceptions
Replaced feeding zeros into `dpt.log` where it is not essentially for the property tested. 
When testing special values, hard code expected results, rather than recompute them with `np.log`.
=> MAINT: changes to test_log.py to avoid RuntimeErrors

dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/hypot.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logaddexp.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logical_and.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logical_or.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logical_xor.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/negative.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/positive.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/pow.hpp
This pull request simplifies the comparison functions by removing unnecessary output type specializations for ``float`` and ``std::complex<float>``.
This reduces the amount of code generation, in hopes of decreasing the binary size.
This PR also fixes typos throughout the elementwise functions and implements the templates from ``elementwise_common`` where they were not being used.
=> Removes redundant output types from logical and comparison functions

docs/generate_rst.py, dpctl/tests/test_sycl_event.py, dpctl/tests/test_sycl_usm.py
This PR aims to fix dpctl's flake8 style conformity and the flake8 CI, which have both been changed by flake8 releasing version 6.1.0.
Checks for equality between types (i.e., ``type(x) == type(y)``) have been changed to use the `is` keyword to that end.
=> flake8 6.1.0 fixes

dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp, dpctl/tests/elementwise/test_floor_divide.py
On some devices, ``sycl::floor`` and ``std::floor`` would drop the sign of 0.
This PR resolves those cases and adds a test.
=> dpctl.tensor.floor_divide fixed for signed 0 output

dpctl/tensor/_data_types.py
Fix a small mistake in `dpt.isdtype` that prevent wrong user input to be correctly displayed in the error message:
> TypeError: Expected instance of `dpt.dtype`, got {dtype_}
=> Fix missing string format in isdtype

.github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml, conda-recipe/meta.yaml, dpctl/_backend.pxd, dpctl/_sycl_context.pyx, dpctl/_sycl_device.pyx, dpctl/_sycl_event.pyx, dpctl/_sycl_queue.pyx, dpctl/apis/include/dpctl_capi.h, dpctl/tensor/_dlpack.pyx, dpctl/tests/_device_attributes_checks.py, libsyclinterface/helper/source/dpctl_utils_helper.cpp, libsyclinterface/include/dpctl_sycl_enum_types.h, libsyclinterface/tests/test_sycl_device_aspects.cpp, setup.py
This PR closes gh-1277, reverts 03a46e14c2aabae4408139673889d6dd7a0a6f87 to enable Cython 3.0, modifies Cython files per Cython guidance, and removes deprecated in 2023.2 `sycl::aspect::usm_restricted_shared_allocations` and `dpctl.SyclDevice.has_aspect_usm_restricted_shared_allocations` property.
=> Update for cython 3

dpctl/tensor/libtensor/source/full_ctor.cpp
Remove `using` statement adding an unused qualifier to the namespace.
=> Clean-up: removed unused symbol in full_ctor.cpp

dpctl/tensor/_copy_utils.py, dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.hpp
`dpctl` used to utilize int64 data type temporary to compute running sum of flattened mask array. For smaller arrays, where int32 would suffice, this resulted in suboptimal performance. 
This PR adds support for int32 in advanced Boolean indexing implementation function, and changes orchestrating Pyton code to allocated temporary of int32 data type if the number of elements in the mask array is less than a threshold.
=> Boolean indexing performance

dpctl/tensor/_copy_utils.py, dpctl/tests/test_usm_ndarray_indexing.py
Fixes regression in output dtype of `tensor.nonzero` and closes gh-1322.
Changes in gh-1300 made data type of indexes arrays was the same as dtype of temporary cumulative sum array, which incidentally worked before the change.
=> Nonzero regression

dpctl/tensor/_dlpack.pyx, dpctl/tests/test_usm_ndarray_dlpack.py
Closes gh-1241 by fixing DLPack exporter logic in `dpctl`.
=> Fix gh 1241

dpctl/tensor/CMakeLists.txt, dpctl/tests/test_usm_ndarray_ctor.py
Closes gh-1314 by compiling Python binding code converting `float('nan')` to a floating-point number using `-fno-fast-math`.
---
To see that this is the right solution, use 
```c++
// filename: nan.cpp
#include "pybind11/pybind11.h"
double fp_id(double x) {
return x;
}
PYBIND11_MODULE(_nan, m) {
m.def("fp_id", &fp_id);
}
```
Compile it 
```
icpx nan.cpp --shared -fPIC $(python -m pybind11 --includes) -o _nan.so
```
and test with 
```
python -c "import _nan; print(_nan.fp_id(float('nan')))"
```
With default compilation option `-1` comes out, signaling an uncaught exception. It takes `-fno-fast-math` for it to round-trip correctly.
=> Compile certain source files in libtensor with no-fast-math

dpctl/tensor/_copy_utils.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logaddexp.hpp
This PR fixes an array API test case for ``logaddexp`` that fails for mixed nan and number operands.
It also applies a previous fix used for ``astype`` with ``order="K"`` to ``copy``.
=> Fix some array api test cases

dpctl/tensor/libtensor/source/boolean_reductions.hpp, dpctl/tests/test_usm_ndarray_utility_functions.py
Closes #1327 
This PR fixes a typo in the Python binding common to both boolean reductions (any, all).
The binding was calling the implementations of these functions with ``dst_nd`` rather than ``iter_nd``.
``dst_nd`` and ``iter_nd`` often ended up being the same for small-dimensional arrays, which masked the problem.
=> Fix boolean reductions for #1327

dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/greater_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/less_equal.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/maximum.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/minimum.hpp, dpctl/tensor/libtensor/include/utils/math_utils.hpp
This PR refactors complex comparison functions into a new header file, `utils\math_utils.hpp`.
=> Refactor complex comparison functions

dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp, dpctl/tests/elementwise/test_expm1.py, dpctl/tests/elementwise/test_log1p.py
This PR changes the logic of ``expm1`` for complex data types to better account for special cases (``NaN``s, ``inf``s, etc.). These cases were handled identically to Numpy, but did not conform to the array API.
In addition, this PR slips in changes to silence the remaining warnings in the test suite which were being raised by the elementwise tests.
=> Fix expm1 for complex special cases

dpctl/_backend.pxd, dpctl/_sycl_platform.pxd, dpctl/_sycl_platform.pyx, dpctl/tests/test_sycl_platform.py, libsyclinterface/include/dpctl_sycl_context_interface.h, libsyclinterface/include/dpctl_sycl_platform_interface.h, libsyclinterface/source/dpctl_sycl_platform_interface.cpp, libsyclinterface/tests/test_sycl_platform_interface.cpp
While testing `dpctl` in the [flat device hierarchy mode](https://spec.oneapi.io/level-zero/latest/core/PROG.html#device-hierarchy) I realized we have not implemented equality testing for `dpctl.SyclPlatform` which caused test `test_sycl_context.py::test_multi_device_different_platforms` to fail.
This PR implements `DPCTLPlatform_AreEq`, `DPCTLPlatform_Hash`, adds tests and implaments `dpctl.SyclPlatform.__equal__` and `dpctl.SyclPlatform.__hash__` based on these. 
Incidentally this PR also corrects declaration of `DPCTLContext_Hash` which mistakenly  used `__dpctl_take` instead of `__dpctl_keep` annotation.
=> Sycl platform equal

dpctl/tensor/_copy_utils.py, dpctl/tensor/libtensor/source/device_support_queries.cpp, dpctl/tensor/libtensor/source/device_support_queries.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_usm_ndarray_indexing.py
This PR closes gh-1335.
It introduced array API notion of (device-specific) [default index data type](https://data-apis.org/array-api/draft/API_specification/data_types.html#default-data-types), and ensure that `dpctl.tensor.nonzero` 
output arrays are created of this data type.
Relevant test was adjusted accordingly.
=> Fix nonzero result dtype win

dpctl/tensor/_copy_utils.py, dpctl/tensor/_indexing_functions.py, dpctl/tensor/_manipulation_functions.py, dpctl/tensor/_stride_utils.pxi, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
This PR fixes two bugs: closes gh-1330, and fixes array_api_tests failure regarding `usm_ndarray.to_device` not supporting `stream` keyword.
=> usm_ndarray.to_device(dev, stream=queue) support

dpctl/apis/include/dpctl_capi.h
Define `CYTHON_EXTERN_C` as empty for C compilers.
=> Closes gh-1344

dpctl/tests/test_usm_ndarray_dlpack.py
Since USM-host allocation, unlike USM-device and USM-shared allocations, is not associated with any particular device, only with the host, it is unreasonable to expect that ``sycl::get_pointer_device(ptr, ctx)`` will return the same device that is stored in the `sycl_queue` attribute of `dpctl.tensor.usm_ndarray` instance.
The tests are adjusted to bypass that check for USM-host allocations.
=> Fixed tests from_dlpack and _from_dlpack_strided for USM-host allocations

.github/workflows/os-llvm-sycl-build.yml
The intel/llvm/pull/10551 has been merged, so the build should succeed and produce working binary.
=> Use latest sycl bundle to build DPCTL

dpctl/tensor/_usmarray.pyx, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/boolean_reductions.hpp, dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/elementwise_functions.hpp, dpctl/tensor/libtensor/source/sum_reductions.cpp, dpctl/tensor/libtensor/source/where.cpp, dpctl/tests/test_usm_ndarray_ctor.py
The PR proposes a minor change to get rid of typo in the text of exception and code comments: `accomodate` -> `accommodate` (double m's).
=> Correct typo in an exception text

conda-recipe/meta.yaml, dpctl/tests/_c_ext.c, dpctl/tests/setup_c_ext.py, dpctl/tests/setup_cython_api.py, dpctl/tests/test_headers.py
This PR adds compilers to test requirements list.
test_sycl_queue.py::test_cython_api requires a compiler to build a native extension.
=> Test environment requires compilers

dpctl/tensor/_copy_utils.py, dpctl/tensor/_ctors.py, dpctl/tensor/_data_types.py, dpctl/tests/test_tensor_asarray.py
Closes gh-1350
`dpctl.tensor.asarray` implementation of `order='K'` keyword processing was replaced with call to tested `_empty_like_orderK` utility to fix the issue reported in gh-1350.
Few routines had to be shuffled to avoid import failure due to circular import dependencies.
=> Fix bad order=K code logic in tensor.asarray 

README.md
wheel package is published on PyPi and on pypi.anaconda.org.
README is part of wheel metadata which is published on PyPi and this update is needed to specify 
pypi.anaconda.org as recommended installation channel.
=> Update README for wheel installation

dpctl/tensor/_copy_utils.py, dpctl/tensor/_search_functions.py, dpctl/tests/test_usm_ndarray_search_functions.py
This PR adjusts the behavior of ``dpctl.tensor.where`` to preserve the memory layout of its inputs. This improves the access pattern of the kernel.
Performance of old behavior:
```
In [1]: import dpctl.tensor as dpt, numpy as np
In [2]: dt = dpt.int32
In [3]: sh = (8160, 8160)
In [4]: ar1 = dpt.ones(sh, dtype=dt, order="C")[:4080, ::-2].mT
In [5]: ar2 = dpt.zeros(sh, dtype=dt, order="C")[:4080, ::-2].mT
In [6]: condition = dpt.zeros(sh, dtype=dt, order="C")[:4080, ::-2].mT
In [7]: res = dpt.where(condition, ar1, ar2)
CPU times: user 143 ms, sys: 53.4 ms, total: 196 ms
Wall time: 220 ms
In [8]: %time res = dpt.where(condition, ar1, ar2)
CPU times: user 48.3 ms, sys: 67.6 ms, total: 116 ms
Wall time: 119 ms
In [9]: %time res = dpt.where(condition, ar1, ar2)
CPU times: user 81.5 ms, sys: …
```
=> ``dpctl.tensor.where`` output preserves memory order of inputs

dpctl/tensor/_elementwise_common.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_usmarray.pyx, dpctl/tensor/libtensor/source/elementwise_functions.hpp, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_floor_ceil_trunc.py, dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_logaddexp.py, dpctl/tests/elementwise/test_trigonometric.py
This PR completes the implementation of in-place arithmetic operators.
With current behavior, in-place operations simply call the standard implementation and then set the original memory equal to the result. This sometimes leads to unnecessary memory allocation.
By reworking the ``out`` keyword, either input operand array can now be used as the output array, and copies are only required for casting and where race conditions must be considered (i.e., when the ``out`` array overlaps only some of an input).
=> Fully enable ``usm_ndarray`` in-place arithmetic operators

dpctl/tensor/__init__.py, dpctl/tensor/_linear_algebra_functions.py, dpctl/tests/test_usm_ndarray_linalg.py
This PR implements the function ``dpctl.tensor.matrix_transpose``, a function wrapper for ``usm_ndarray.mT`` as required by the array API specification.
=> Implements dpctl.tensor.matrix_transpose

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
The ``real`` and ``imag`` properties of ``usm_ndarray`` were setting the flags of the returned view incorrectly.
In most cases, the output was not contiguous, but the input was, which caused most functions to behave incorrectly on views into the real or imaginary parts of complex arrays.
This PR corrects that, and also allows ``real`` and ``imag`` to work on 0-dimensional arrays.
=> usm_ndarray.real and usm_ndarray.imag now set flags correctly

dpctl/tensor/_elementwise_common.py
Corrected messsage text in two exceptions in "_elementwise_common.py" file as pointed out by @vtavana
=> Improved message text in two exceptions

.github/workflows/conda-package.yml, .github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml
Closes gh-1295
Stop building conda packages of `dpctl` for Python 3.8
=> Do not build dpctl for Python 3.8

dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/where.hpp
We used `sycl::multi_ptr` constructor instead of
`sycl::address_space_cast` previsously, and change in https://github.com/KhronosGroup/SYCL-Docs/pull/432 introduced `sycl::access:decorated::legacy` as the default which is deprecated in SYCL 2020 standard which highlighted the problem.
In using `sycl::address_space_cast` we specify
`sycl::access::decorated::yes`.
=> Conversion from raw to multi_ptr should be done with address_space_cast

dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp
This PR resolves the following deprecation warning from SYCLOS compiler:
```
In file included from ~/dpctl/dpctl/tensor/libtensor/source/elementwise_functions.cpp:56:
~/dpctl/dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp:118:42: warning: \
'sincos' is deprecated: SYCL builtin functions with raw pointer arguments have been deprecated. \
Please use multi_ptr. [-Wdeprecated-declarations]
118 |             const realT sinY_val = sycl::sincos(y, &cosY_val);
```
The resolution is to convert raw pointer to multi-pointer using `sycl::address_space_cast`.
=> Resolve SYCL-2020 deprecation warning

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
Ensure that ndarray that we converted usm_ndarray single element instance into  is 0d before calling `__int__`, `__float__`, `__complex__`, `__index__`.
```
In [1]: import numpy as np
In [2]: np.__version__
Out[2]: '1.25.2'
In [3]: int(np.arange(1,2))
<ipython-input-3-5727c43c7d79>:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
int(np.arange(1,2))
Out[3]: 1
In [4]: int(np.reshape(np.arange(1,2), tuple()))
Out[4]: 1
In [5]: int(np.arange(1,2))
<ipython-input-5-5727c43c7d79>:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single …
```
=> Address NumPy 1.25 deprecation warnings

dpctl/tests/test_usm_ndarray_ctor.py
Moved the assertion about comparison with generic types before other assertions in `test_flags` test
This change is made in reference to Coverity scan issue, which is a false positive, but the test can be improved anyway.
=> Turn comparison call into assertion in test_usm_ndarray_ctor::test_flags 

scripts/gen_coverage.py, scripts/gen_docs.py
Initialized env to empty dictionary instead of `None`.
This resolves two Coverity reported issues.
=> Fix for Coverity highlighted issue in scripts

dpctl/tensor/_copy_utils.py
Adds support for lowercase order in `tensor.copy` and `tensor.astype`
Closes #1372
=> Addressed issue with lowercase order value in tensor copy and astype

dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/include/utils/strided_iters.hpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/simplify_iteration_space.cpp, dpctl/tensor/libtensor/source/simplify_iteration_space.hpp, dpctl/tests/test_usm_ndarray_indexing.py
This PR fixes some edge cases to boolean indexing that were not working as expected.
The cumulative sum used to get the count of set elements in the mask was misbehaving, especially for cases with negative strides (and most noticeably, the 1D case). This seems to have been caused by stride simplification can change the order elements are traversed in, which caused incorrect results.
Additionally, the ``offset`` parameter was also unused in when the contiguous kernel was called after simplification.
A new stride simplification method called ``compact_iteration_space`` was introduced to fix the problem.
=> Fixes boolean indexing for strided masks

libsyclinterface/source/dpctl_sycl_queue_interface.cpp
Ensured that `create_property_list` always returns an not-null unique pointer by creating an default-constructed `property_list` for the fall-through.
With this change we no longer need two branches for call to `sycl::queue` constructor, since `propList` is always available.
=> Addressed "Very high" Coverity issue: dereferencing null pointer

dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp
Coverity flaged `floor_divide` functor for boolean input types.
```
114040 [Operands don't affect result] (static_checker_CONSTANT_EXPRESSION_RESULT)
The expression's value does not depend on the operands; often, this represents an inadvertent logic error.
In dpctl::​tensor::​kernels::​floor_divide::​FloorDivideFunctor<bool, bool, signed char>::​operator ()(bool const &, bool const &): An operation with non-constant operands that computes a result with constant value ([CWE-569](http://cwe.mitre.org/data/definitions/569.html))
```
Wrote dedicated simpler code for handling boolean inputs.
=> Addressed Coverity issue about handling bools in floor_divide

.github/workflows/conda-package.yml, .github/workflows/generate-docs.yml
Opening a PR from my fork of `dpctl` to test changes to "conda-packages.yaml" workflow (step about array-api-conformity) and to "generate-docs.yaml" worflow.
=> Fix fork workflows

conda-recipe/run_test.bat, conda-recipe/run_test.sh
Modified "conda-recipe/run_test.bat" and "conda-recipe/run_test.sh" to execute `python -m dpctl -f` for detailed information about available devices and driver versions.
=> run_test files to output verbose listing of platform config

dpctl/_sycl_context.pyx, dpctl/_sycl_device.pyx, dpctl/_sycl_event.pyx, dpctl/_sycl_queue.pyx, dpctl/_sycl_timer.py, dpctl/apis/include/dpctl4pybind11.hpp, dpctl/memory/_memory.pyx, dpctl/tensor/_copy_utils.py, dpctl/tensor/_device.py, dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_manipulation_functions.py, dpctl/tensor/_print.py, dpctl/tensor/_slicing.pxi, dpctl/tensor/_stride_utils.pxi, dpctl/tensor/_usmarray.pyx, dpctl/tensor/include/dlpack/README.md, dpctl/tensor/include/dlpack/dlpack.h, dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/utils/offset_utils.hpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/device_support_queries.cpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_tensor_asarray.py, libsyclinterface/include/dpctl_data_types.h, libsyclinterface/include/dpctl_device_selection.hpp, libsyclinterface/include/dpctl_sycl_device_selector_interface.h, libsyclinterface/include/dpctl_sycl_event_interface.h, libsyclinterface/include/dpctl_sycl_queue_interface.h, libsyclinterface/include/dpctl_vector.h
Used `codespell` to identify misspellings.
=> Spelling fixes pointed out by codespell

dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/source/sum_reductions.cpp
This PR improves performance of reduction kernel with atomics
1. Contig implementation kernel gets a dedicated name (easier to spot in the output of onetrace)
2. Increases work-group size multiple of the size of sub-group
3. Changes the order in which workgroups tile the array from "along reduction axis" moves fastest to "along iteration axis" moves fastest.
4. Introduces a dedicated implementation for reduction over axis0 and deploys it.
Performance in the main trunk:
```
In [2]: x = dpt.reshape(dpt.asarray(1, dtype="f4")/dpt.square(\
dpt.arange(1, 1282200*128 + 1, dtype="f4")), (1282200, 128))
In [3]: %time y = dpt.sum(x, axis=0)
CPU times: user 309 ms, sys: 128 ms, total: 437 ms
Wall time: 473 ms
In [4]: %time y = dpt.sum(x, axis=0)
CPU times: user …
```
=> Reduction performance

cmake/FindDpctl.cmake
FindPythonLibs is deprecated since cmake 3.18 and was removed in cmake 3.27. It results in build errors for projects that uses 3.27 and dpctl.
```
-- pybind11 v2.10.2
CMake Warning (dev) at _skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/FindPythonLibsNew.cmake:98 (find_package):
Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
_skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/pybind11Tools.cmake:50 (find_package)
_skbuild/linux-x86_64-3.11/cmake-build/_deps/pybind11-src/tools/pybind11Common.cmake:180 (include) …
```
=> Remove deprecated FindPythonLibs

dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp
Used ``address_space_cast<address_space::private_space,...>`` on a local variable.
To create the `sycl::multi_ptr` from a local variable (in private memory) we should be using ``address_space::private_space``.
=> Correct address_space when casting ref of local variable to multi_ptr

dpctl/tensor/libtensor/include/kernels/elementwise_functions/sqrt.hpp
Fixed `constexpr` significant bits value for `double` type.
Renamed variable for clarity.
This is commit is cherry-picked from gh-1383
=> Fixed constexpr significant bits value for double

dpctl/tensor/libtensor/source/sum_reductions.cpp, dpctl/tests/test_tensor_sum.py
Closes gh-1391
The specialized reduce_over_axis0 kernel should be called if both src/dst are F-contiguous, or when src is F-contig, and dst is C-contig but 1D (usually it is also F-contig in this case though).
=> Fix for incorrect result in reduction over axis=0

dpctl/tensor/CMakeLists.txt, dpctl/tensor/_manipulation_functions.py, dpctl/tensor/_reshape.py, dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp, dpctl/tensor/libtensor/include/utils/offset_utils.hpp, dpctl/tensor/libtensor/include/utils/strided_iters.hpp, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp, dpctl/tensor/libtensor/source/copy_for_roll.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_usm_ndarray_manipulation.py
This PR supersedes gh-1341.
This PR removes `shift` parameter from `_copy_usm_ndarray_for_reshape` and introduces `_copy_usm_ndarray_for_roll_1d` (for `axis=None`) and `_copy_usm_ndarray_for_roll_nd` functions where `shifts` argument is expected to be a tuple specifying shift size for every axis.
This dedicated function `_copy_usm_ndarray_for_roll_nd` is used to implement multi-axis `roll` function instead of a sequence of concurrent copy operations.
This PR will make input `dpt.roll(x, shift=(1,1))` raise a `TypeError` exception (since array API spec mandates that when shift is a tuple, an axis must also be a tuple).
=> Add roll kernels

dpctl/tests/test_sycl_queue_manager.py
`dpctl.SyclDevice.create_subdevice` -> `dpctl.SyclDevice.create_sub_device`. 
The typo was masked by overly broad `except` exception pattern.
=> Fixed qualifier name typo

.github/workflows/generate-coverage.yaml, .github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/libtensor/include/kernels/boolean_reductions.hpp, dpctl/tensor/libtensor/source/boolean_reductions.cpp, dpctl/tensor/libtensor/source/boolean_reductions.hpp
This PR makes changes to boolean reductions which align with #1364
Namely, the traversal pattern of work groups in boolean reductions has been changed to be fastest over the iteration dimension, rather than the reduction dimension, and a specialized kernel for reductions over `axis 0` in matrices has been added.
The original contiguous boolean reduction kernel has also been renamed to make the difference more apparent.
=> Boolean reduction performance improvements

CHANGELOG.md
This PR modifies `CHANGELOG.md` to enumerate changes that go into forthcoming 0.15.0 release of `dpctl`.
=> Populate changelog for 0.15.0 release

conda-recipe/meta.yaml, dpctl/tensor/_elementwise_common.py, dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_trigonometric.py, setup.py
Install tests/elementwise/*.py into the package
Closes gh-1408
=> Install missing elementwise test files into the dpctl prefix

dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp
This PR modifies "libtensor/include/kernels/elementwise_functions/common.hpp" to add missing `#include <pybind11/pybind11.h>` and missing definition of `offset_utils` namespace.
=> Add missing include, missing namespace definition

dpctl/tests/conftest.py, dpctl/tests/elementwise/test_abs.py, dpctl/tests/elementwise/test_exp.py, dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_log.py, dpctl/tests/elementwise/test_round.py, dpctl/tests/elementwise/test_sqrt.py, dpctl/tests/elementwise/test_square.py, dpctl/tests/elementwise/test_trigonometric.py, pyproject.toml
This PR simplifies the `test_[func]_out_overlap` testing for elementwise funcs in dpctl by removing most of these tests, which were redundant, leaving only a test for overlap in `test_abs.py`.
This PR also modifies `pyproject.toml` and `conftest.py` to add a new pytest marker and complementary option, `broken_complex`, which skips some tests by default due to known issues on some platforms (esp. Windows).
=> Changes to elementwise function tests that use complex data types

dpctl/CMakeLists.txt, dpctl/tests/test_service.py, examples/pybind11/use_dpctl_sycl_kernel/resource/README.md, libsyclinterface/CMakeLists.txt
This PR ports some fixes from #1395 to main branch with intent to include them in 0.15.0 release:
- Fixed typo in `examples/pybind11/use_dpctl_sycl_kernel/resource/README.md`
- Ensure that `libsyclinterface/include/*.hpp` are made available for projects during build time.
---
=> Port back fixes from async-ref-count-increment branch

CMakeLists.txt, examples/pybind11/external_usm_allocation/CMakeLists.txt, examples/pybind11/onemkl_gemv/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_kernel/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_queue/CMakeLists.txt, libsyclinterface/cmake/modules/GetProjectVersion.cmake
Use `cmake_minumum_required(VERSION min_version...policy_version FATAL_ERROR)`.
Also update from using `find_package(PythonExtensions)` to `find_package(Python COMPONENTS ...)`.
=> Use cmake_minimum_required with min...max

.github/workflows/conda-package.yml
Fixed conda-packages workfload's failure in uploading wheels.
=> Fix upload_linux/upload_windows steps

dpctl/tensor/__init__.py, dpctl/tensor/_reduction.py, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/utils/sycl_utils.hpp, dpctl/tensor/libtensor/source/reduction_over_axis.cpp, dpctl/tensor/libtensor/source/reduction_over_axis.hpp, dpctl/tests/test_tensor_sum.py
This is PR builds on top of work of #1399 and implements `_prod_over_axis` and the satellite associated type query function.
```
In [2]: import dpctl.tensor._tensor_impl as ti
In [4]: x = dpt.linspace(1, 2, num=32, dtype="f4")
In [5]: x
Out[5]:
usm_ndarray([1.       , 1.032258 , 1.0645161, 1.0967741, 1.1290323,
1.1612903, 1.1935483, 1.2258065, 1.2580645, 1.2903225,
1.3225806, 1.3548386, 1.3870968, 1.4193548, 1.4516128,
1.483871 , 1.516129 , 1.548387 , 1.5806451, 1.6129032,
1.6451613, 1.6774192, 1.7096773, 1.7419355, 1.7741935,
1.8064516, 1.8387096, 1.8709677, 1.9032258, 1.9354837,
1.9677418, 2.       ], dtype=float32)
In [6]: z = dpt.empty(tuple(), dtype="f4")
In [7]: ti._prod_over_axis(src=x, trailing_dims_to_reduce=1, dst=z, …
```
=> Implement product

dpctl/tensor/_manipulation_functions.py, dpctl/tensor/libtensor/include/kernels/repeat.hpp, dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tensor/libtensor/source/repeat.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_usm_ndarray_manipulation.py
This PR permits `axis=None` for any input to ``repeat``.
To do so, the previously implemented kernels for repeat were tweaked to permit this behavior, and overloads of ``py_repeat_by_sequence`` and ``py_repeat_by_scalar`` without ``axis`` arguments were implemented. These share an overloaded Python binding, with and without an ``axis`` argument.
=> repeat with `axis=None` repeats flattened array

.github/workflows/conda-package.yml
This PR fixed "conda-packages.yam" workflow by using `apt update --fix-missing` before doing `apt install gdb` which errors out with status code 404.
=> [CI] Fix test_linux step in conda-packages workflow

dpctl/tensor/libtensor/source/repeat.cpp
This PR fixes a bug in repeat where host_task event dependencies for allocating shapes and strides on the device were not always being passed to the kernel, which could cause the program to crash.
[See this CI run](https://github.com/IntelPython/dpctl/actions/runs/6426525416/job/17451716888)
=> Fix host_task dependency not being passed to repeat 1d

dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tests/test_usm_ndarray_manipulation.py
Closes #1432 
This PR fixes a bug caused by a typo in the Python binding changes made in #1427
Also adds a test for correct behavior
=> Fixes ``repeat`` for ``axis=0`` with scalar input

dpctl/CMakeLists.txt, dpctl/tests/test_tensor_sum.py, dpctl/tests/test_utils.py, dpctl/utils/CMakeLists.txt, dpctl/utils/__init__.py, dpctl/utils/src/device_queries.cpp
This PR exposes device descriptors from https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
It adds `dpctl.utils.intel_device_info(dev)` function that returns dictionary with meaningful values for these descriptors (if implemented).
=> Add intel device info data

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/true_divide.hpp, dpctl/tensor/libtensor/source/elementwise_functions.cpp, dpctl/tests/elementwise/test_divide.py, dpctl/tests/elementwise/test_floor_divide.py
This pull request implements kernels for in-place division and floor division, i.e., ``dpt.divide(x, y, out=x)`` and ``dpt.floor_divide(x, y, out=x)``.
This avoids allocating an additional buffer for the output and copying back to the first operand.
=> Dedicated kernels for in-place ``dpt.divide`` and ``dpt.floor_divide``

.github/workflows/conda-package.yml, conda-recipe/bld.bat, conda-recipe/build.sh
Wheels are uploaded to the version from wheels package that comes from versioner. That version is different for wheel and Conda and contains GitHub stash. That results into junk in Conda registry version list. PR simply uploads same wheel to the version of Conda package.
=> Upload wheel to the same version

conda-recipe/meta.yaml
Require dpcpp compiler 2024.0 and runtime >=2024.0
Also introduced jinja variable to keep those two in sync.
This PR is opened with base being gold/2021, but will get merged into main branch once dpcpp 2024.0 is available on intel channel.
=> Require dpcpp compiler 2024.0 and runtime >=2024.0

dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_sign.py, dpctl/tests/elementwise/test_trigonometric.py
This PR skips elementwise tests in dpctl on Windows for complex types due to known issues to be addressed after 2024 has been released.
The PR targets gold/2021 only.
=> Skip tests for complex types for functions known to fail on Windows

dpctl/_sycl_context.pyx, dpctl/_sycl_event.pyx, dpctl/_sycl_queue.pxd, dpctl/_sycl_queue.pyx
This PR arises from improve upon behavior noted in gh-1434
- Static method `dpctl.SyclEvent.wait_for` now uses `DPCTLEvent_Wait` instead of `DPCTLEvent_WaitAndThrow`, aligning with `dpctl.SyclEvent.wait` and `dpctl.SyclQueue.wait` methods.
- `dpctl.SyclAsyncException` has been removed
- Constructor calls to `DPCTLQueue_Create` and `DPCTLContext_Create` now pass `NULL` function pointer for the async handler function
- The `dpctl._sycl_queue.default_async_handler` function has been removed.
---
=> Do not use wait and throw

dpctl/tests/test_utils.py
Tweaked `test_intel_device_info` to allow for empty returned dictionary for some CPUs, like in virtual machines in public CI (see syclos build [log](https://github.com/IntelPython/dpctl/actions/runs/6529939196/job/17728364009) of gh-1443).
=> Tweaked test_intel_device_info

dpctl/tensor/libtensor/include/kernels/accumulators.hpp
This PR modifies `inclusive_scan_rec_local_scan_krn` kernel in `"accumulatros.hpp"`.
It removed superfluous barrier, formats code for readability, and moves a comment while updating it slightly.
=> Removed superfluous barrier, moved comment, formatted kernel

dpctl/_backend.pxd, dpctl/_host_task_util.hpp, dpctl/_sycl_queue.pxd, dpctl/_sycl_queue.pyx, dpctl/_sycl_timer.py, dpctl/tests/test_sycl_event.py, dpctl/tests/test_sycl_kernel_submit.py, dpctl/tests/test_sycl_queue_memcpy.py, libsyclinterface/include/dpctl_sycl_queue_interface.h, libsyclinterface/source/dpctl_sycl_queue_interface.cpp, libsyclinterface/tests/test_sycl_queue_interface.cpp
Added `dpctl.SyclQueue._submit_keep_args_alive(args, events)` that increments reference count of `args` object (typically a sequence of arguments an asynchronous task is operating on), ensuring that `args` object is not garbage collected until after `events` signal that tasks working on these objects complete their execution.
=> Added submit_keep_args_alive

libsyclinterface/source/dpctl_sycl_device_interface.cpp
Use `partition_type_property` descriptor in `DPCTLDevice_GetParentDevice`.
This allows to test that the device is an unpartitioned device without raising and handling the C++ exception.
If `info::device::partition_type_property` is `info::partition_property::no_partition` then retrieving 
the `parent_device` descriptor will throw.
This change reduces the clutter of expected [ERR] messages in `DPCTL_VERBOSITY=error` mode.
=> Use partition_type_property descriptor in DPCTLDevice_GetParentDevice

dpctl/tensor/CMakeLists.txt, dpctl/tensor/__init__.py, dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/libtensor/include/kernels/clip.hpp, dpctl/tensor/libtensor/source/clip.cpp, dpctl/tensor/libtensor/source/clip.hpp, dpctl/tensor/libtensor/source/tensor_py.cpp, dpctl/tests/test_tensor_clip.py
This pull request implements the function ``clip``, for clipping elements of an array to a range.
Clip permits both Python scalar and ``dpctl.tensor.usm_ndarray`` arguments for its ``min`` and ``max`` arguments.
An example of the new functionality:
```
In [1]: import dpctl.tensor as dpt, numpy as np
In [2]: x = dpt.arange(-2, 8, dtype="i4")
In [3]: dpt.clip(x, 0, 5)
Out[3]: usm_ndarray([0, 0, 0, 1, 2, 3, 4, 5, 5, 5], dtype=int32)
```
=> Implements ``dpctl.tensor.clip``

dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tests/test_tensor_sum.py, dpctl/tests/test_usm_ndarray_reductions.py
This PR modifies computation of typed pointer to take offsets into account in reduction implementations for contiguous inputs.
It also adds tests which would fail before this change
=> Fix reduction contig impl offset handling

dpctl/tensor/libtensor/source/reductions/reduction_atomic_support.hpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tests/test_tensor_sum.py, dpctl/tests/test_usm_ndarray_reductions.py
Closes #1455 
This PR fixes typos in ``reductions/reduction_over_axis.hpp`` which caused the ``axis1`` implementation to be called where ``axis0`` was determined to be correct.
Now, the correct table is used to retrieve the function pointer.
Additionally, this PR sneaks in a fix for another typo in ``reduction_atomic_support.hpp`` which caused ``MinAtomicSupportFactory`` and ``MaxAtomicSupportFactory`` to inherit from ``ArithmeticAtomicSupportFactory`` rather than ``MinMaxAtomicSupportFactory``. This meant atomics were unused for ``min`` and ``max`` for floating-point types.
=> Fix ``axis0`` calls in reduction Python binding

dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tests/test_usm_ndarray_reductions.py
This pull request restricts calls of contiguous variants for search reductions, now excluding cases where F-contiguous data is reduced to a single value.
These cases would return the index as if counting down columns rather than counting along the rows.
=> Fix search reductions giving incorrect results for F-contiguous inputs

dpctl/tensor/libtensor/include/kernels/reductions.hpp
This pull request adds ``SequentialSearchReduction`` functor to improve ``argmax`` and ``argmin`` for small arrays.
=> Improves performance of search reductions for small numbers of elements

dpctl/tensor/CMakeLists.txt, dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_reduction.py, dpctl/tensor/_utility_functions.py, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/source/tensor_ctors.cpp, dpctl/tensor/libtensor/source/tensor_elementwise.cpp, dpctl/tensor/libtensor/source/tensor_reductions.cpp, dpctl/tests/elementwise/test_elementwise_classes.py, examples/python/sycl_timer.py
1. Renamed misspelled variable
2. If `reduction_nelems` is small, use `SequentialReductionKernel` for tree-reductions as it is done for atomic reduction
3. Tweak scaling down logic for moderately-sized number of elements to reduce. Closes gh-1461
We should also use `max_wg` if the `iter_nelems` is very small (one), since choosing `max_wg` for large` iter_nelems` may lead to under-utilization of GPU.
---
=> Improve performance of reduction for small number of elements to reduce for types where tree-reduction is needed

dpctl/tensor/_reduction.py, dpctl/tests/test_tensor_sum.py
Closes gh-1468
This PR changes `_reduce_over_axis` when an implementation to reduce using requested `dtype` for given input type does not exist. The change casts input array into a temporary array of requested `dtype` and calls reduction on the temporary (silent assumption that implementation to reduce input array using the same input dtype is available).
=> Fix for gh-1468 in arithmetic reduction when type promotion is needed

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_reductions.py
This enables `dpt.usm_ndarray(np.prod((2,3,4)))`.
=> Fix usm_ndarray ctor when shape is integral numpy scalar

.github/workflows/conda-package.yml, dpctl/tensor/__init__.py, dpctl/tensor/_array_api.py, dpctl/tests/test_tensor_array_api_inspection.py
This pull request proposes implementing ``dpctl.tensor.__array_namespace_info__``, an inspection utility coming soon to the array API specification.
In addition, this PR adds an ``__array_api_version__`` attribute [as per the specification](https://data-apis.org/array-api/latest/API_specification/generated/array_api.__array_api_version__.html#array_api.__array_api_version__) and experimentally removes the ``--ci`` flag from array API testing.
=> Add array API inspection utilities to ``dpctl.tensor``

dpctl/tensor/__init__.py, dpctl/tensor/_reduction.py, dpctl/tensor/_statistical_functions.py, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tests/test_tensor_statistical_functions.py
This pull request
1. Implements ``dpctl.tensor.mean``, ``dpctl.tensor.std``, and ``dpctl.tensor.var`` as top-level functions which leverage tensor submodules.
2. Resolves #1456 by adding logic to tree reduction implementations that populate the output array with the identity when reducing over axes which include a zero-size axis and by adding early exits for `py_reduction_over_axis`, `py_tree_reduction_over_axis`, and `py_search_over_axis` when the destination array is of zero size. 
This permitted removing `identity` as an argument to the general reduction Python API, as well as removing logic for zero-size array inputs.
3. Adjusts reduction Python API functions to return a copy of the input array, rather than the input array itself, when no reduction will be performed (i.e., `axis=()`) …
=> Implements statistical functions ``mean``, ``std``, ``var``

cmake/FindDpctl.cmake
Update environment names for dpctl find cmake file. Issue most likely was introduced in #1389 but was reveled only now under certain circumstances: I was trying to build numba-dpex in vscode. I've tested locally that both scikit build and direct cmake build are working.
=> Fix cmake FindDpctl.cmake

dpctl/tensor/_elementwise_common.py, dpctl/tests/elementwise/test_elementwise_classes.py
The `nin` and `nout` properties return the number of arguments to the element-wise function treated as inputs or outputs, respectively.
`nout` is always 1 for both unary and binary functions, as both cases permit an `out` keyword argument.
=> Adds `nin` and `nout` properties to unary and binary element-wise classes

dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sin.hpp
This pull request makes changes to `sin` and `expm1` to properly treat real and complex `-0` inputs.
=> Resolves gh-1439

.github/workflows/conda-package.yml, conda-recipe/meta.yaml
The compiler package `dpcpp_linux-64=2024.0.1` has known issues breaking CMake integration with DPC++. 
This PR pins build-time version to 2024.0.1 until the underlying issue gets resolved.
=> Stay away from 2024.0.1 compiler package for now

dpctl/tests/elementwise/test_exp.py, dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_sqrt.py, dpctl/tests/elementwise/test_trigonometric.py
After transition to `sycl::ext::oneapi::experimental` namespace functions for complex types in gh-1411, all tests pass.
=> Remove marks broken_complex from all tests

dpctl/tensor/__init__.py, dpctl/tensor/_data_types.py, dpctl/tensor/_manipulation_functions.py, dpctl/tensor/_type_utils.py, dpctl/tests/test_tensor_dtype_routines.py, dpctl/tests/test_usm_ndarray_manipulation.py
Changed `dpt.can_cast` and `dpt.result_type` to be device-aware if arguments are instances of `usm_ndarray`.
=> Device-aware `can_cast` and `result_type`

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp
Check that `sycl::malloc_device` did not return `nullptr` to signal allocation failure.
=> Check if malloc_device return nullptr in matmul code

conda-recipe/meta.yaml
This change modifies `"meta.yaml"` to disallow 2024.0.1 and 2024.0.2 but allow for newer versions
=> Allow for newer version of DPC++ compiler

conda-recipe/meta.yaml
This PR add maintainers to the conda recipe. 
It serves to tests whether internal scanning for people names is going to break due the inspecting the conda-package tar-ball's `info/` folder.
=> Updated recipe-maintainers list

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tests/test_usm_ndarray_linalg.py
This PR fixes flaw in kernels cause out-of-bound memory access by only accessing memory if indexes are in range.
It also reverses work-arounds making CPU dispatching different from GPU dispatching
Added tests for strided inputs to test negative strides for first operand, second operand and the batching.
=> Fix out of bound access in gemm thread k kernels

dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_type_utils.py, dpctl/tests/elementwise/test_type_utils.py, dpctl/tests/test_usm_ndarray_manipulation.py
Added support for weak scalars data type.
=> Fixed dpctl.tensor.result_type function for scalars

dpctl/tensor/_elementwise_common.py, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_bitwise_and.py, dpctl/tests/elementwise/test_bitwise_left_shift.py, dpctl/tests/elementwise/test_bitwise_or.py, dpctl/tests/elementwise/test_bitwise_right_shift.py, dpctl/tests/elementwise/test_bitwise_xor.py, dpctl/tests/elementwise/test_divide.py, dpctl/tests/elementwise/test_floor_ceil_trunc.py, dpctl/tests/elementwise/test_floor_divide.py, dpctl/tests/elementwise/test_hyperbolic.py, dpctl/tests/elementwise/test_logaddexp.py, dpctl/tests/elementwise/test_multiply.py, dpctl/tests/elementwise/test_pow.py, dpctl/tests/elementwise/test_remainder.py, dpctl/tests/elementwise/test_subtract.py, dpctl/tests/elementwise/test_trigonometric.py
Used `ValueError` instead of `TypeError` per Python guidelines. 
Inappropriate uses were pointed out by @vtavana (Thank you)
=> Replaced few TypeError with ValueError in _elementwise_common

dpctl/tensor/CMakeLists.txt
This PR remove use of `-fsycl-link-huge-device-code` link option when building tensor_impl modules on Linux.
=> Do not use link-huge-device-code option

dpctl/tensor/libtensor/include/kernels/sorting.hpp, dpctl/tensor/libtensor/source/sorting/sorting_common.hpp
`test_sort_1d[c16]` and `test_sort_2d[c16]` were failing on GPU devices supporting double precision, 
This PR applies a work-around by using `std::isnan` until the bug is analyzed and fixed. Both failing tests pass now.
Additionally, this PR replaced use of `while` loop in `sort_over_work_group_contig_krn` with use of `for` loop over fixed size interval reducing branching/
=> Fix for complex sorting test failure

.github/workflows/conda-package.yml, .github/workflows/cpp_style_checks.yml, .github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml, .github/workflows/pre-commit.yml, .github/workflows/python_style_checks.yml
This PR specifies permissions in GitHub Action workflows. Minimal read-all permission is set by default, and specific scope get elevated permission as needed.
This would improve OpenSSF Scorecard value for dpctl
=> Specify permissions in GH Action workflows

conda-recipe/meta.yaml
No longer require `numpy < 1.26` in runtime environment.
=> conda-recipe-meta-yaml tweaks

.github/workflows/conda-package.yml, dpctl/tensor/__init__.py, dpctl/tensor/_data_types.py, dpctl/tensor/_type_utils.py
This pull request moves `isdtype` to `_type_utils.py` to make the function signature match what is required by the array API specification.
Additionally experiments with using the `--disable-deadline` when running array API tests, as some tests fail for exceeding the deadline.
=> Fix dpctl.tensor.isdtype function signature

.github/workflows/generate-docs.yml
Fix for generate documentation workflow. Only run "Publish docs" step if PR is not being closed.
=> Fix generate-docs workflow breakage when run on PR closure

dpctl/tensor/_copy_utils.py, dpctl/tests/test_usm_ndarray_ctor.py
Closes gh-1503
In code copying usm_ndarray into usm_ndarray, when broadcasting `rhs` to the common shape using `usm_ndarray` constructor, `offset` parameter was not being set, causing incorrect behavior reported gh-1503.
This PR specifies the `offset` parameter, and adds test based on reproducing example of said issue.
=> Fix copy of src with offset

dpctl/tensor/_clip.py, dpctl/tensor/_copy_utils.py, dpctl/tests/test_tensor_clip.py
This pull request adjusts dpctl.tensor.clip to permit `min` and `max` to be `None` simultaneously, resulting in effectively a no-op.
In addition, makes a small adjustment to dpctl.tensor.copy, which would return a `TypeError` instead of raising it, and resolves https://github.com/IntelPython/dpctl/issues/1489 by fixing two typos in `_resolve_one_strong_one_weak_types`
=> `clip` permits `None` for `min` and `max`

dpctl/tensor/_copy_utils.py, dpctl/tensor/_type_utils.py, dpctl/tests/test_usm_ndarray_ctor.py
This pull request implements the `device` keyword into `dpctl.tensor.astype`, which permits simultaneously casting and sending the array to a separate device.
The type of the array must be supported on the new device, as well as the type it is being cast to.
=> Adds `device` keyword argument to `astype`

.github/workflows/conda-package.yml, .github/workflows/cpp_style_checks.yml, .github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml, .github/workflows/os-llvm-sycl-build.yml, .github/workflows/pre-commit.yml, .github/workflows/python_style_checks.yml
Updated action versions to the latest available.
=> Update versions of Github actions scripts prompted by transition from Node 16 to Node 20

dpctl/tensor/_ctors.py, dpctl/tests/test_tensor_asarray.py
This pull request adjusts `dpt.asarray` such that the `dtype` argument is passed to `np.asarray` call when called with a Python scalar as input
This guarantees the expected `OverflowError` is thrown.
Additionally, this PR adds tests for this behavior, for `copy=False` errors to `test_tensor_asarray`, and removes a superfluous `NotImplementedError` for Python sequences from `asarray`.
Closes gh-1512
=> Fix array API test failure caused by issue reported in gh-1512

CHANGELOG.md
This PR populates `CHANGELOG.md` with entries since 0.15.0 release
--- 
The full list of PRs merged since 0.15.0 tag:
- [gh-1424](https://github.com/IntelPython/dpctl/pull/1424) [cmake MNT]
- [gh-1425](https://github.com/IntelPython/dpctl/pull/1425) [CICD]
- [gh-1399](https://github.com/IntelPython/dpctl/pull/1399) (reductions)
- [gh-1427](https://github.com/IntelPython/dpctl/pull/1427) `dpt.repeat` support for `axis=None`
- [gh-1429](https://github.com/IntelPython/dpctl/pull/1429) [CICD MNT]
- [gh-1430](https://github.com/IntelPython/dpctl/pull/1430) `dpt.repeat` bug fix
- [gh-1433](https://github.com/IntelPython/dpctl/pull/1433) [BUG FIX] for `dpt.repeat` for `axis=0`
- [gh-1428](https://github.com/IntelPython/dpctl/pull/1428) and …
=> Populated changelog of new features since 0.15.0 release

dpctl/tensor/CMakeLists.txt
E.g.
```
[123/222] $BUILD_PREFIX/bin/icpx -D_tensor_elementwise_impl_EXPORTS -DNOTFOUND -DUSE_SYCL_FOR_COMPLEX_TYPES \
-I$BUILD_PREFIX/include \
.... \
-c $SRC_DIR/dpctl/tensor/libtensor/source/elementwise_functions/acos.cpp
```
=> Fix generated -DNOTFOUND for compiling elementwise functions

CMakeLists.txt, cmake/dpctl-config.cmake, dpctl/__main__.py, dpctl/tests/test_service.py
`dpctl/__main__.py` no longer triggers loading of libsycl library for queries
`python -m dpctl --includes` will no longer load SYCL runtime libraries.
Module file acquired three more options
--include-dir
--tensor-include-dir
--library-dir
This would output absolute path to directory of include headers,
tensor include headers, and directory containing DPCTLSyclInterface
library.
`FindDpctl.cmake` has been renamed to `dpctl-config.cmake`. 
This PR also installs `dpctl-config.cmake` to `${PREFIX}/lib/cmake` folder, making `find_package(Dpctl)` work out of the box with `dpctl` installed in the Python environment. 
With local build of `dpctl`,  downstream projects can hint CMake to finding Dpctl package by
using standard mechanism:
```
-DDpctl_ROOT=$(python -m dpctl --cmakedir)
```
=> Service improvements

dpctl/tests/elementwise/test_abs.py, dpctl/tests/elementwise/test_add.py
Encountered unexpected test failure using the following test invocation:
```bash
python -m pytest \
dpctl/tests/test_tensor_*.py \
dpctl/tests/test_usm_ndarray_*.py \
dpctl/tests/elementwise/test_a*.py
```
=> No reason to expected ufunc.types_ to be `None`.

CHANGELOG.md
Updated entries in `"CHANGELOG.md"` with additional changes that went in.
=> Reflected additional work that went into main trunk in the changelog

dpctl/tests/test_usm_ndarray_linalg.py
This resolves NumPy warning issued upon `rhs_array == scalar` where scalar is Python integer not range of the array's dtype when running tests from `test_usm_ndarray_linalg.py` test file.
Presently we issue warnings from 
```
tests/test_usm_ndarray_linalg.py::test_vecdot_1d[i1]
tests/test_usm_ndarray_linalg.py::test_vecdot_1d[u1]
tests/test_usm_ndarray_linalg.py::test_vecdot_3d[i1]
tests/test_usm_ndarray_linalg.py::test_vecdot_3d[u1]
tests/test_usm_ndarray_linalg.py::test_vecdot_axis[i1]
tests/test_usm_ndarray_linalg.py::test_vecdot_axis[u1]
tests/test_usm_ndarray_linalg.py::test_vecdot_strided[i1]
tests/test_usm_ndarray_linalg.py::test_vecdot_strided[u1]
```
This PR resolves all of them. The warning goes like:
```
/usr/share/miniconda/envs/test_dpctl/lib/python3.11/site-packages/dpctl/ten …
```
=> Explicitly project ref-values to range of short integral types

.github/workflows/conda-package.yml
Change array-api-tests run command.
This should resolve the following `ModuleNotFoundError` seen in the logs:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/runner/work/dpctl/dpctl/dpctl/__init__.py", line 38, in <module>
from ._device_selection import select_device_with_aspects
File "/home/runner/work/dpctl/dpctl/dpctl/_device_selection.py", line 20, in <module>
from ._sycl_device import SyclDevice, SyclDeviceCreationError
ModuleNotFoundError: No module named 'dpctl._sycl_device'
============================= test session starts ==============================
```
=> Change array-api-tests run command

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp
Used `if constexpr` to make `m_groups=1` specializations of functors unnecessary. 
Also used const references for vectors in some places.
=> changes to matmul codebase: reducing line-count

dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_linear_algebra_functions.py, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
This pull request makes changes to `_usmarray.pyx` to guarantee that the writable flag is handled correctly for views created via `real`, `imag`, `T`, `mT`, and shape-setting and indexing properties.
`__getitem__` now only adjusts the flag after all writing to the result has been performed, fixing the practice of setting elements to a read-only array.
Elementwise functions, `clip`, and `matmul` also now contain early (top-level) checks for the writable flag of a provided `out` array, fixing an edge case where the writable flag would be overridden by copying to the original array. This practice also prevents unnecessary computation and memory allocation.
=> Fixes setting of writable flag for views and writing to read-only arrays with `out` keyword

dpctl/tensor/_usmarray.pyx, dpctl/tests/elementwise/test_elementwise_classes.py, dpctl/tests/test_tensor_clip.py, dpctl/tests/test_usm_ndarray_linalg.py
This is a follow-up to gh-1527. 
It changes `usm_ndarray._set_writable_flag` implementation to use `_copy_writable` utility function. 
It also adds tests to verify that read-only array passed to `out` keyword raises `ValueError`.
=> Writable flag views followup

dpctl/_backend.pxd, dpctl/_sycl_device.pyx, dpctl/tests/_device_attributes_checks.py, libsyclinterface/include/dpctl_sycl_device_interface.h, libsyclinterface/source/dpctl_sycl_device_interface.cpp, libsyclinterface/tests/test_sycl_device_interface.cpp
Added `uint32_t DPCTLDevice_GetMaxClockFrequency(__dpctl_keep const DPCTLSyclDeviceRef DRef)` and `uint64_t DPCTLDevice_GetMaxMemAllocSize(__dpctl_keep const DPCTLSyclDeviceRef DRef)`.
These expose `info::device::max_clock_frequency` and `info::device::max_mem_alloc_size` descriptors.
Corresponding Python API are attributes `dpctl.SyclDevice.max_clock_frequecne` and `dpctl.SyclDevice.max_mem_alloc_size`.
E.g.:
```
(dev_dpctl) opavlyk@opavlyk-mobl:~/repos/dpctl$ ipython
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import dpctl.tensor as dpt, dpctl
In [2]: dpctl.SyclDevice("cpu").max_mem_alloc_size // (1024 * 1024 * 1024)
Out[2]: 7
In [3]: …
```
=> Two new device descriptors added

libsyclinterface/tests/test_sycl_device_interface.cpp
"OpenCL:CPU" device started reporting `aspect::fp16` and supporting `sycl::half` type, but vector widths for `sycl::half` type both return zero.
=> Added work-around for breaking change in 2024.1 compiler

dpctl/tensor/libtensor/include/utils/offset_utils.hpp
Making `NoOpIndexer` constructor and the call operator a `constexpr` allows compiler to completely inline its definition at earlier optimization stages.
Also replaced stray `py::ssize_t` with `ssize_t`.
=> Make some offset indexer classes constexpr

.github/workflows/conda-package.yml
The `pr-comment` action generates the following warning:
```
Unexpected input(s) 'repo-token-user-login', valid inputs are ['message', 'message-path', 'message-id', \
'refresh-message-position', 'repo-owner', 'repo-name', 'repo-token', \
'allow-repeats', 'proxy-url', 'status', 'message-success', 'message-failure', \
'message-cancelled', 'message-skipped', 'issue', 'update-only', 'preformatted', 'find', 'replace']
```
This PR repos the offending argument as it is ignored anyway.
=> Removed action parameter per GH warning

dpctl/tensor/libtensor/include/kernels/sorting.hpp
Apply fix suggested by Coverity to `COPY_INSTEAD_OF_MOVE` issue.
=> Addressed COPY_INSTEAD_OF_MOVE coverity issue

dpctl/tests/elementwise/test_greater.py, dpctl/tests/elementwise/test_greater_equal.py, dpctl/tests/elementwise/test_less.py, dpctl/tests/elementwise/test_less_equal.py, dpctl/tests/elementwise/test_logical_and.py, dpctl/tests/elementwise/test_logical_not.py, dpctl/tests/elementwise/test_logical_or.py, dpctl/tests/elementwise/test_logical_xor.py
Coverity reports several copy-paste-errors in tests of elementwise functions. This PR addresses those issues.
=> Fix Coverity issues in tests

dpctl/apis/include/dpctl4pybind11.hpp, dpctl/tensor/libtensor/include/utils/output_validation.hpp, dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/clip.cpp, dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/elementwise_functions/elementwise_functions.hpp, dpctl/tensor/libtensor/source/eye_ctor.cpp, dpctl/tensor/libtensor/source/full_ctor.cpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/linear_sequences.cpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tensor/libtensor/source/sorting/argsort.cpp, dpctl/tensor/libtensor/source/sorting/sort.cpp, dpctl/tensor/libtensor/source/triul_ctor.cpp, dpctl/tensor/libtensor/source/where.cpp
This pull request refactors Python API functions to use new utilities for validating output arrays. These utilities validate that an array is sufficiently ample for a given number of elements (i.e., not the result of broadcasting) and that the array's writable flag is set.
=> Adds and implements utilities for validating array size and writable flag

dpctl/_sycl_device.pyx
This PR changes implementations of two `SyclDevice` properties to ensure that returned array is deallocated before return Python object value is constructed.
MaxWorkGroupSizes2d, MaxWorkGroupSizes1d returns an array. Copy array elements into local variables, free array before packing those values into Python tuple.
=> Rewrite some properties to delete arrays before dealing w/ objects

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_type_utils.py, dpctl/tests/elementwise/test_negative.py, dpctl/tests/elementwise/test_type_utils.py
@npolina4 pointed out that array API states it should not be supported for Boolean inputs.
There is no dedicated loop for type `bool`, but input `dtype` `bool `gets promoted to integral types, and `negative` function returns result for the promoted type.
The change makes `UnaryElementwiseFunc` instance for negative use acceptance functions, which raises an exception for promotion with `dpt.bool` as starting data type.
A test is added.
=> Fix negative for boolean inputs

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_type_utils.py, dpctl/tests/elementwise/test_subtract.py
The change makes `BinaryElementwiseFunc` instance for `dpt.subtract` use acceptance function, that raises an exception for promotion with `dpt.bool` as starting data type. Changes apply to the case where both arguments are of `dpt.bool` data type.
A test is added.
=> Fix subtract for boolean inputs

dpctl/tensor/_elementwise_funcs.py
This pull request makes a number of changes to the docstrings of element-wise functions, with a focus on guaranteeing that the information in the docstrings is correct and removing typos.
Each function, when referencing expected data types of inputs, now refers to the types which will not be cast. For example, `dpt.divide` arguments now state that they expect floating-point data, as otherwise, the data will be copied and cast.
=> Cleans up elementwise function docstrings

dpctl/_sycl_platform.pyx, dpctl/tensor/_dlpack.pxd, dpctl/tensor/_dlpack.pyx, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_dlpack.py, libsyclinterface/source/dpctl_sycl_platform_interface.cpp
`x.__dlpack_device__()` returns ID of the parent device, if allocation device is not a root device.
It gives ID (position in `sycl::device::get_devices()`) for the root device that the array allocation device descends from for sub-devices, or ID of the allocation device is that device is a root device.
This allows sharing through DLPack of allocation on sub-devices, as long as default platform context for the platform the device is from was used in allocation.
=> x.__dlpack_device__() returns ID of the parent device

dpctl/tensor/_utility_functions.py
Closes gh-1563
Allocating the temporary as USM-device ensures that atomic updates are always possible.
=> Boolean reductions allocate int32 temporary as USM-device

.github/workflows/conda-package.yml
Create empty temporary directory to run "pytest" command from to work-around an issue in pytest accessing files/directories it may not have access to during test collection.
https://github.com/pytest-dev/pytest/issues/11904
This should fixed test_windows step failures.
=> To work around an issue in pytest, run tests from empty temp dir

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp
Use kernel device-specific descriptor to determine maximal work-group size for this kernel.
This resolves
```
RuntimeError: Exceeded the number of registers available on the hardware.
The number registers per work-group cannot exceed 65536 for this kernel on this device.
The kernel uses 108 registers per work-item for a total of 1024 work-items per work-group.
-54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)
```
when running example:
```python
m1 = dpt.ones((1000, 1000), dtype="i4", device="cuda")
m2 = dpt.ones((1000, 1003), dtype="i4", device="cuda")
r = dpt.matmul(m1[:, :900], m2[:900, :])
```
=> Fix RuntimeError when running strided gemm on CUDA devices 

libsyclinterface/cmake/modules/SetupCoverage.cmake
As pointed out by @diptorupd "dpctl.lcov" file no longer contains data for `libsyclinterface`'s ".cpp" files.
Restoring this option recovers those locally.
=> Restore using -fno-sycl-footer option for coverage collection

libsyclinterface/source/dpctl_sycl_device_manager.cpp
Use of `std::move` destroys the context saved in the cache, negating existence of this cache, but also setting the code up for possible silent failures.
=> Removed use of std::move in DPCTLDeviceMgr_GetCachedContext

dpctl/tests/test_service.py
Also added code to work around a bug with CPU runtime, which may cause DPC++ RT to not see CPU device in the sub-process if the parent process has initialized CPU plugin.
=> Modularized test_main tests

dpctl/tensor/_linear_algebra_functions.py, dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tests/test_usm_ndarray_linalg.py
Updates `vecdot` and `tensordot` to reflect changes to the array API specification
- `tensordot` permits negative axis values when `axes` is a tuple, as there is no ambiguity, because they are specified separately
- `vecdot` now only permits negative integers for its `axis` argument to prevent ambiguity
Additionally, this fixes a few cases where `vecdot`, `tensordot`, and `matmul` would produce incorrect results (e.g., fixes #1570 )
=> `tensordot` and `vecdot` array API conformity changes

dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tensor/libtensor/include/utils/type_dispatch_building.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot_atomic_support.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot_dispatch.hpp
This pull request adds headers missing from files in `libtensor/source/linalg_functions/` and `kernels/linalg_functions`
=> Adds license headers missing from `libtensor/source/linalg_functions/` and `kernels/linalg_functions` files

dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/include/kernels/clip.hpp, dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/integer_advanced_indexing.hpp, dpctl/tensor/libtensor/include/kernels/repeat.hpp, dpctl/tensor/libtensor/include/kernels/where.hpp
No copying of indexers in functor constructors
Used `const`/`constexpr` qualifiers for indexers created, as appropriate. 
Private members indexers in functor structs now use `const` qualifier.
=> No copying of indexers in functor constructors

dpctl/tensor/libtensor/include/utils/strided_iters.hpp, dpctl/tensor/libtensor/source/clip.cpp, dpctl/tensor/libtensor/source/where.cpp
This PR checks in changes made during development work:
1. Use const reference for `CIndexer_vector` and `CIndexer_array` methods for container arguments
2. Handle possible USM-host allocation failure in "clip.hpp"
=> Technical debt changes

dpctl/_sycl_queue.pyx, dpctl/enum_types.py, dpctl/tests/test_sycl_kernel_submit.py
Fixes https://github.com/IntelPython/numba-dpex/pull/1379 and https://github.com/IntelPython/dpctl/pull/1581 . Other enums must be revisited.
=> Start kernel_arg_type enums from 0

dpctl/_backend.pxd, dpctl/_sycl_queue.pyx, dpctl/tests/test_sycl_kernel_submit.py
Adds `_arg_data_type._LOCAL_ACCESSOR` to `_backend.pyx`, and `dpctl_local_accessor` to `dpctl._sycl_queue.kernel_arg_type`.
=> Add local_accessor kernel_arg_type

libsyclinterface/dbg_build.sh, libsyclinterface/include/dpctl_sycl_queue_interface.h, libsyclinterface/source/dpctl_sycl_queue_interface.cpp, libsyclinterface/tests/CMakeLists.txt, libsyclinterface/tests/test_sycl_device_aspects.cpp, libsyclinterface/tests/test_sycl_queue_interface.cpp, libsyclinterface/tests/test_sycl_queue_submit.cpp, libsyclinterface/tests/test_sycl_queue_submit_local_accessor_arg.cpp, scripts/gen_coverage.py
This PR extends `test_sycl_queue_submit` to use 1D range, 2D range, 3D range and use dependent events.
=> Improve coverage sycl interface

dpctl/tensor/_manipulation_functions.py
`tensor.expand_dims` docstring change only.
Documentation string now reflects that `axis` keyword argument is allowed to be a tuple of integers. 
See https://github.com/data-apis/array-api/issues/760
=> Docstring of expand_dims to reflect that axis can be a tuple

dpctl/memory/_memory.pyx
Used `DPCTLQueue_MemoryWithEvent` to order copy operations in `copy_via_host` function.
This eliminates one call to `DPCTLEvent_Wait`.
=> Used DPCTLQueue_MemoryWithEvent to order copy operations

libsyclinterface/include/dpctl_sycl_platform_interface.h
Inspecting documentation building log noticed mismatch between doxygen doc-string and actual declaration.
This PR fixes the mismatch.
=> Renamed argument of DPCTLPlatform_Hash to match doxygen doc string

dpctl/_sycl_device.pyx, dpctl/memory/_memory.pyx, dpctl/tensor/_linear_algebra_functions.py, dpctl/tensor/_print.py, dpctl/tensor/_reduction.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_usmarray.pyx, dpctl/utils/_onetrace_context.py
Addressed indentation, and spacing errors tripping Sphinx, as guided by output of `sphinx-build` command.
The log of sphinx build should not contain non-blocking `ERROR statements in the build log/
=> Address sphinx errors

dpctl/apis/include/dpctl4pybind11.hpp
This PR eliminates superfluous copying of `dpctl_capi` instance, even if it is later eliminated by the compiler. 
The copying would necessary in `static dpctl_capi api = lookup()` line, since `lookup` returns `dpctl_capi` instance by value.
The change is to make it return a reference.
Since `dpctl_capi` is a singleton, this change only eliminates a single copy, so consider it a technical debt cleanup change.
The PR also adds a default move assignment operator for `dpctl_capi`.
=> Avoid superfluous copy of dpctl_capi struct

dpctl/_sycl_timer.py
Use Note in `dpctl.SyclTimer` docstring.
Also fix grammar in the text of the note. 
The change in this PR only affects docstring of `dpctl.SyclTimer` class.
=> Use Note in SyclTimer docstring

dpctl/apis/include/dpctl4pybind11.hpp
This PR removes private method `dpctl_capi::lookup`.
This removes one of static `dpctl_capi` instance from `dpctl_capi` definition. This leaves a single static instance created dynamically in get static method.
=> Remove private method lookup in dpctl_capi

dpctl/tensor/_searchsorted.py, dpctl/tests/test_usm_ndarray_searchsorted.py
Output of `tensor.searchsorted` must always have default indexing data type.
This is mandated by array API specification
=> Output of searchsorted must always have default indexing data type

dpctl/tensor/_searchsorted.py, dpctl/tests/test_usm_ndarray_searchsorted.py
`tensor.searchsorter` applies `sorter` array, if present, to first input array using `tensor.take` with default `mode="wrap"`, which replaces out of bound indices with in-bound ones using modular reduction.
This closes gh-1599
=> Documented wrapping behavior of out of bound values of sorter

dpctl/tensor/_linear_algebra_functions.py, dpctl/tests/test_usm_ndarray_linalg.py
This PR corrects behavior of `matmul` to properly account for appending of axes to inputs where one or both arguments are vectors.
Previously, these cases would raise an error, and require an `out` array with axes appended by the user.
=> Fixes `out` kwarg in `matmul` when axes are appended to inputs

libsyclinterface/source/dpctl_sycl_device_manager.cpp
This PR backports gh-1573 to 'maintenance/0.16.x' branch.
=> Backport gh-1573 to 0.16.x maintenance branch

dpctl/tensor/_linear_algebra_functions.py, dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tests/test_usm_ndarray_linalg.py
This PR backports fixes from gh-1577.
=> Backport changes from gh-1577 to 0.16.x maintenance branch

dpctl/_sycl_queue.pyx, dpctl/enum_types.py, dpctl/tests/test_sycl_kernel_submit.py
This PR backport #1585  to 'maintenance/0.16.x' branch. 
Merging this PR is a pre-requisite for backporting gh-1581.
=> Backport gh 1585

dpctl/__main__.py, dpctl/tests/test_service.py
Output of `python -m dpctl --library` incorrectly output `-lSyclInterface`. It should have been `-lDPCTLSyclInterface`. 
This PR changes the output, adjusts docstrings to use correct library name and modifies test to assert that the expected library name occurs as a substring in the output.
This fix should be backported to 0.16.1
=> Fix main script

CHANGELOG.md
This PR modifies `CHANGELOG.md` file to document changes from 0.16.0 tag to future 0.16.1 tag.
The writeup assumes that gh-1612 is merged, so this should only be merged after gh-1612 is in.
=> Added changelog entries for the upcoming 0.16.1 release

CHANGELOG.md
Fixed typo in changelog introduced in recent gh-1613 and pointed out by @diptorupd
=> Fix for typo in changelog

.github/workflows/conda-package.yml
Fix conda-packages workflow's step 'test_examples_linux' by removing pinning from above on compiler's version.
=> Remove pinning of compiler version for test_examples step

.github/workflows/conda-package.yml
Backport gh-1616 to 'maintenance/0.16.x' branch.
This is CI/CD change only to enable all steps to build with newly released DPC++ 2024.1.0 compiler
=> Backport gh-1616 to 0.16.x maintenance branch

dpctl/__main__.py, dpctl/tests/test_service.py
This PR backports gh-1614 to 'maintenance/0.16.x' branch.
=> Backport gh-1614 to 0.16.x maintenance branch

.github/workflows/generate-coverage.yaml
Use DPC++ 2024.1.0 to collect coverage. 
Use of 2023.2.0 was a work-around.
=> Use DPC++ 2024.1.0 to collect coverage

docs/doc_sources/reference_guides/dpctl/tensor.linear_algebra.rst, docs/doc_sources/reference_guides/dpctl/tensor.rst
This PR adds a documentation page for linear algebra functions `matmul`, `matrix_transpose`, `tensordot`, and `vecdot`, which were previously undocumented in the base branch for dpctl documentation revamp.
Opening as a PR to not interfere with possible ongoing work in the branch.
=> Adds page for linear algebra functions to `dpctl.tensor` documentation

dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/utils/sycl_utils.hpp
Need barrier after call to custom inclusive scan to avoid race condition with subsequent writes into SLM.
Added comments explaining why barriers are needed
=> Need barrier after call to custom inclusive scan to avoid race condition

dpctl/tensor/_accumulation.py
Docstring edits for `cumulative_*` family of functions.
New line after list of items to make Sphinx happy, and edits to explanation of the shape of the output array.
=> Docstring edits for accumulation functions

dpctl/tensor/CMakeLists.txt, dpctl/tensor/__init__.py, dpctl/tensor/_accumulation.py, dpctl/tensor/_reduction.py, dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/utils/sycl_utils.hpp, dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/accumulators/accumulate_over_axis.hpp, dpctl/tensor/libtensor/source/accumulators/accumulators_common.cpp, dpctl/tensor/libtensor/source/accumulators/accumulators_common.hpp, dpctl/tensor/libtensor/source/accumulators/cumulative_logsumexp.cpp, dpctl/tensor/libtensor/source/accumulators/cumulative_logsumexp.hpp, dpctl/tensor/libtensor/source/accumulators/cumulative_prod.cpp, dpctl/tensor/libtensor/source/accumulators/cumulative_prod.hpp, dpctl/tensor/libtensor/source/accumulators/cumulative_sum.cpp, dpctl/tensor/libtensor/source/accumulators/cumulative_sum.hpp, dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tensor/libtensor/source/tensor_accumulation.cpp, dpctl/tests/test_tensor_accumulation.py
This pull request proposes implementation of `dpctl.tensor.cumulative_sum`, `dpctl.tensor.cumulative_prod`, and `dpctl.tensor.cumulative_logsumexp`.
`cumulative_sum` is already part of the array API standard and is implemented as per the spec. `cumulative_prod` and `cumulative_logsumexp` are implemented with a similar API, including an `include_initial` keyword argument.
=> Implements accumulation functions in dpctl.tensor

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_indexing_functions.py, dpctl/tensor/_manipulation_functions.py, examples/cython/usm_memory/blackscholes/blackscholes.pyx
This PR changes docstrings for `tile` and `repeat` to better describe behaviors of these functions, and fixes minor typos throughout dpctl where "usm_narray" was used instead of "usm_ndarray"
=> Edit docstrings for `tile` and `repeat`, fix "usm_narray" typos

dpctl/tensor/_accumulation.py
The PR proposes to add a note for description of `axis` in accumulation functions as per Python array API for `cumulative_sum` documentation.
Without the note in the description it might not be clear that `axis` keyword is required (rather than optional) in some use cases.
=> Add a note for description of `axis` in accumulation functions

dpctl/tensor/libtensor/include/kernels/elementwise_functions/abs.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/acos.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/acosh.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/asin.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/asinh.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/atan.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/atan2.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/atanh.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/cabs_impl.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/ceil.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/cos.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/cosh.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/expm1.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor_divide.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/log1p.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/logaddexp.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/proj.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/remainder.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sign.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sin.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sinh.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/sqrt.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/tan.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/tanh.hpp
Using the 2024.1 compiler and building with `DPCTL_TARGET_CUDA=1` fails due to unrecognized symbols in elementwise functions like `fabs`, `fabsf`, `copysign`, and `floor` from the C++ std namespace.
This PR proposes replacing the non-working symbols with their Sycl namespace equivalents.
=> Fix compiling for CUDA with 2024.1 compiler

dpctl/tensor/_accumulation.py, dpctl/tensor/_array_api.py, dpctl/tensor/_reduction.py, dpctl/tensor/_type_utils.py, dpctl/tests/test_tensor_array_api_inspection.py, dpctl/tests/test_usm_ndarray_indexing.py, dpctl/tests/test_usm_ndarray_reductions.py, dpctl/tests/test_usm_ndarray_searchsorted.py
This pull request updates reductions over floating point data to be performed in the input type by default as per the 2023.12 array API spec.
This pull request also changes `__array_api_version__` to 2023.12. As `cumulative_sum` is a requirement of the 2023.12 spec, this PR should be redirected to master after the base branch is merged.
=> Update reduction data types for 2023.12 array API specification, update `__array_api_version__`

CHANGELOG.md, CMakeLists.txt
This PR proposes 2 changes:
* Change PROJECT version in CMakeLists.txt to 0.16
* Sets the date of 0.16.1 release to April 10, 2024
-----
=> Set release date of 0.16.1 in changelog document

.flake8, dpctl/_sycl_context.pyx, dpctl/_sycl_device.pyx, dpctl/_sycl_device_factory.pyx, dpctl/_sycl_event.pyx, dpctl/_sycl_platform.pyx, dpctl/_sycl_queue.pyx, dpctl/_sycl_timer.py, dpctl/program/_program.pyx, dpctl/tensor/_array_api.py, dpctl/tensor/_copy_utils.py, dpctl/tensor/_ctors.py, dpctl/tensor/_dlpack.pyx, dpctl/tensor/_reduction.py, dpctl/tensor/_reshape.py, dpctl/tensor/_usmarray.pyx, dpctl/utils/__init__.py, dpctl/utils/_compute_follows_data.pyx, dpctl/utils/_onetrace_context.py
Docstring edits for `dpctl.memory` and `dpctl.utils` namespaces.
=> More docstring edits

CMakeLists.txt
Use `pybind11==2.12.0` to build `dpctl`
=> Use pybind11 version 2.12.0

dpctl/_sycl_queue.pyx, dpctl/memory/_memory.pyx, dpctl/utils/__init__.py, libsyclinterface/include/syclinterface/Support/MemOwnershipAttrs.h, libsyclinterface/include/syclinterface/dpctl_service.h, libsyclinterface/include/syclinterface/dpctl_sycl_platform_interface.h, libsyclinterface/include/syclinterface/dpctl_sycl_platform_manager.h, libsyclinterface/include/syclinterface/dpctl_sycl_queue_interface.h, libsyclinterface/include/syclinterface/dpctl_sycl_queue_manager.h
Spelling fixes in docstrings and in comments identified by sphinxcontrib.spelling
=> Spellings in code

dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/source/device_support_queries.cpp, dpctl/tensor/libtensor/source/elementwise_functions/elementwise_functions.hpp
Changed signatures functions to take ``sycl::queue `` argument by reference, not by value.
Since ``sycl::queue`` contains a shared pointer inside, copying it involves operating atomic variable, and hence should be avoided if possible.
=> Avoid sycl::queue copying in libtensor

dpctl/tensor/_reduction.py, dpctl/tensor/_search_functions.py, dpctl/tensor/libtensor/source/where.cpp, dpctl/tests/test_usm_ndarray_reductions.py, dpctl/tests/test_usm_ndarray_search_functions.py
This pull request proposes building on the set of functions supporting the `out` keyword in dpctl. Specifically, this pull request implements this keyword in all reductions (e.g., `sum`, `max`, `argmax`) and `where`. This paves the way for statistical functions to support the keyword, and may make some function calls more efficient.
This pull request also implements the `order` keyword in `where`, now defaulting to `order="K"` behavior rather than `order="A"`.
=> Implements `out` keyword for `where` and reductions and `order` keyword for `where`

.github/workflows/generate-docs.yml
gh-1377 has made changes to condition of executing "Publish Docs" step which resulted in that condition always evaluating to False, and documentation changes were not uploaded for 8 months since the merge of that PR.
=> Fix logic when built docs are published to gh-pages

dpctl/tensor/_copy_utils.py, dpctl/tensor/_indexing_functions.py, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tests/test_usm_ndarray_indexing.py
This pull request proposes resolutions to #1360, #1382, and #1482 by changing the behavior of advanced indexing and indexing functions.
- `x[i_0, i_1, ...]` now promotes arrays `i_0 ... i_N` to an appropriate integer data type, and only raises where such a data type cannot be found
- `x[indices] = vals` now casts `vals` to the data type of `x` regardless of type. This aligns with `place`/boolean indexing.
- `dpt.put` now warns the user about race conditions when indices are not unique
Additionally, this PR implements changes to `take`, `put`, and generalized advanced integer indexing which handle cases where empty axes are being indexed.
=> Type promotion for `indices` arrays and casting `vals` in integer indexing

dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp
For contiguous inputs, bump local-work-group size from 64 to 128 work-items.
This change is guided by performance study on Newton root finding example rich in elementwise operations.
With this change, `unitrace` states that 311 invocations of the kernel took 2805824666 ns, before that, with 64 workitems, the time was 3475091844 ns.
```
"dpctl::tensor::kernels::multiply::multiply_inplace_contig_kernel<std::complex<float>, std::complex<float>, 4u, 2u>[SIM
D16 {15625; 1; 1} {128; 1; 1}]",          311,           2805824666,    25.380501,              9021944,              8915416,              9143437                          
```
=> Tweak scheduling parameter of elementwise operations

dpctl/tensor/_indexing_functions.py
Document race condition in put when indices array contain duplicated. Provide an example of resolving race condition for 1-d ``x``, ``indices``, and ``vals``.
This PR supersedes gh-1384, since support for `unique_only` can not be efficiently support for higher rank arrays with ``axes`` specified.
=> Addresses gh-1360 with documentation

dpctl/tests/test_utils.py, dpctl/utils/__init__.py, dpctl/utils/src/device_queries.cpp
Added `"free_memory"` for Free Global Memory on the device in bytes, `"memory_clock_rate"` for Maximum Memory Clock Rate in MHz, and `"memory_bus_width"` for bus width in bits.
Additions come from https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
=> Expanded intel_device_info output

dpctl/tests/elementwise/test_abs.py, dpctl/tests/elementwise/test_complex.py, dpctl/tests/elementwise/test_exp2.py, dpctl/tests/elementwise/test_expm1.py, dpctl/tests/elementwise/test_isfinite.py, dpctl/tests/elementwise/test_isinf.py, dpctl/tests/elementwise/test_isnan.py, dpctl/tests/elementwise/test_log.py, dpctl/tests/elementwise/test_log10.py, dpctl/tests/elementwise/test_log1p.py, dpctl/tests/elementwise/test_log2.py, dpctl/tests/elementwise/test_negative.py, dpctl/tests/elementwise/test_positive.py, dpctl/tests/elementwise/test_sign.py, dpctl/tests/elementwise/test_sqrt.py, dpctl/tests/elementwise/test_square.py
The change is to iterate over permutations first, doing some work that does not depend on the order, and then iterate over orders.
This should save doing some computations 4 times (once for each order), now only done once.
The change shaves 4 seconds off of execution of entire test suite on CPU device (from 5 minutes 6 seconds to 5 minutes and 2 seconds).
=> Changes test_func_order tests for some unary functions

dpctl/apis/include/dpctl4pybind11.hpp
This PR fixes two uninitialized typenums in `dpctl_capi` for `UAR_BYTE_` and `UAR_UBYTE_`.
It was noticed during extension writing that these variables are initialized to -1 and never set to the proper values.
=> Initialize `UAR_BYTE_` and `UAR_UBYTE_` in `dpctl_capi`

conda-recipe/build.sh
This PR is designed to fix the problem described here: [SAT-6873](https://jira.devtools.intel.com/browse/SAT-6873). I did some experiments and found out that using pep600 wheel tag prevents the wheel from being installed on non-supported platforms
=> Update wheel tag with pep600

dpctl/tests/test_usm_ndarray_dlpack.py
This PR adds tests to improve coverage in gh-1667
=> Add more dlpack tests

dpctl/tensor/_dlpack.pyx
Factored out device-id computation for DLPack into a separate routine and used it from
both capsule producing functions.
=> Factor out device-id computation

dpctl/tensor/_dlpack.pyx, dpctl/tests/test_usm_ndarray_dlpack.py
Reused `get_parent_device_ordinal_id` routine from `get_dlpack_device_id`.
=> Reuse get parent device ordinal id routine

dpctl/tensor/_dlpack.pxd, dpctl/tensor/_dlpack.pyx, dpctl/tensor/_usmarray.pyx, dpctl/tensor/include/dlpack/README.md, dpctl/tensor/include/dlpack/dlpack.h, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_dlpack.py
This PR bumps the version of dlpack by bringing in the new `dlpack.h` from v1.0rc.
As a result of changes introduced in v1.0rc
- `get_build_dlpack_version` now returns a tuple giving the major and minor DLPack version dpctl was built with
- support for the new `DLManagedTensorVersioned` struct has been added, including full support of the new `flags` attribute
- `__dlpack__` method of `usm_ndarray` has been updated to choose between `DLManagedTensorVersioned` and `DLManagedTensor` paths based on the new `max_version` keyword argument, and also now has `dl_device` and `copy` keyword arguments
- `from_dlpack` method has been updated with `device` and `copy` keyword arguments and now has a path for arrays supporting the new `__dlpack__` interface and `DLManagedTensorVersioned`. `from_dlpack` …
=> Update dlpack to v1.0rc

dpctl/tensor/libtensor/include/kernels/sorting/sort.hpp
Closes gh-1654
The reason behind the crash was out of bound access to shared local memory accessor.
This also fixes a crash in `dpt.sort` on CUDA device for sorting of 256 elements of floating point numbers.
=> Fix for crash reported in gh-1654

dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_linear_algebra_functions.py
This PR proposes a change to `clip`, `matmul`, and the `BinaryElementwiseFunc` class which makes `C` the default contiguity of outputs when `order="K"` and the input arrays must be cast.
This fixes a minor discrepancy where when multiple input arrays are both C- and F-contiguous and need to be cast, the output defaulted to F-contiguous instead of C-contiguous, creating unusual edge cases where type promotion (and therefore the selected device) became relevant to the output array's order, which should not be the case.
For example
```
In [1]: import dpctl.tensor as dpt, dpctl, numpy as np
In [2]: x1 = dpt.ones((10, 1), dtype="i4", device="cpu")
In [3]: x2 = dpt.ones((1, 5), dtype="f4", device="cpu")
In [4]: r = dpt.multiply(x1, x2)
In [5]: r.flags
Out[5]:
C_CONTIGUOUS : False
F_CONTIGUOUS : …
```
=> `order` of output array for binary elementwise funcs, `clip`, and `matmul` defaults to C-contiguous

dpctl/tensor/_reshape.py, dpctl/tests/test_usm_ndarray_ctor.py
Closes gh-1664.
Improves performance of `dpt.reshape(X, new_shape, order="F")` when copy is needed.
=> Reshape improvements

dpctl/tensor/libtensor/include/kernels/elementwise_functions/bitwise_invert.hpp, dpctl/tests/elementwise/test_bitwise_invert.py
This PR proposes removing the `sycl::vec` overload of `bitwise_invert` for boolean inputs to fix unexpected behaviors.
Vectorized `bitwise_invert` on boolean inputs would corrupt the data in a subtle way. When casting this data to an integer data type, 255 would always be the result of casting `true`.
This is likely related to `operator!` on `sycl::vec` returning -1 for `true` and expecting the output type to be a signed integer type.
=> Disable vectorized `bitwise_invert` for boolean inputs

dpctl/tensor/_slicing.pxi, dpctl/tests/test_usm_ndarray_ctor.py
Reproducer provided by @ndgrigorian:
```python
x = dpt.ones((0, 10))
y = dpt.moveaxis(x, 1, 0)
y[1] # raises ValueError
```
Now this returns empty 1d array like `y[0]` does.
A test is added for both integral basic indexing,
and for simple slice.
---
=> Fix bug in basic slicing of empty arrays

dpctl/tensor/_manipulation_functions.py, dpctl/tests/test_usm_ndarray_manipulation.py
This PR fixes a small bug in `dpctl.tensor.repeat` caught by the array API tests where calling `repeat` with `axis=None` on a zero-size array would result in an array with the shape of the input, rather than `x.shape == (0,)` as expected.
To fix this, the malformed fast path for zero-size arrays has been removed, as it was unnecessary: all calls in repeat are already special-cased in the C++ backend to return empty events for zero-size inputs, so any savings for this path were minimal.
=> Removes malformed fast path for zero-size arrays in `repeat`

CHANGELOG.md
This PR backports CHANGELOG.md changes from maintenance/0.16.x branch, and adds changes that went into `dpctl` main branch since 0.16.1 release.
=> Populate changelog for 0.17

CMakeLists.txt, conda-recipe/meta.yaml
This change pins compile-time version of the compiler to 2024.2.0, and restricts the range of compiler runtime libraries accordingly for `dpctl=0.17.0`.
=> Pin compiler at build-time, and limit range for run-time

docs/doc_sources/conf.py.in
Presently the code was not ready to version to not have "+" separator in the version string. This change make the code more robust, and should fix the broken documentation build.
=> Fix logic to computing value of release Sphinx variable

conda-recipe/meta.yaml
Fixed compiler version from "2024.0" to "2024.2.0"
=> Fix compiler version pinning in maintenance/0.17.x

.github/workflows/conda-package.yml
Based on experimentation with mkl_fft, switching from using "windows-latest" image to "windows-2019" fixes MS compiler use for Python packages.
=> Replaced windows-latest with windows-2019 to fix windows builds

dpctl/_sycl_device.pyx
Python code now checks that the return value of `DPCTLDevice_GetMaxWorkGroupSize1d` and `DPCTLDevice_GetMaxWorkGroupSize2d` is not NULL before dereferencing.
=> Handle possible NULL return from DPCTLDevice_GetMaxWorkGroupSize1d, 2d

dpctl/tensor/libtensor/source/sorting/searchsorted.cpp, dpctl/tests/test_usm_ndarray_searchsorted.py
Closes #1689 
This PR fixes `dpctl.tensor.searchsorted` for the case of an input array `x1` with negative strides and a scalar (0D) array `x2`.
Previously, this case would raise `RuntimeError`.
=> Fix `tensor.searchsorted` for `x1` with strides and scalar (0D) `x2`

dpctl/_backend.pxd, dpctl/_sycl_device.pyx, dpctl/tests/_device_attributes_checks.py, dpctl/tests/test_sycl_device.py, libsyclinterface/helper/source/dpctl_utils_helper.cpp, libsyclinterface/include/syclinterface/dpctl_sycl_enum_types.h, libsyclinterface/tests/test_sycl_device_aspects.cpp
Add `dpctl.SyclDevice.has_aspect_emulated` now that DPC++ supports it, see gh-292
=> Add support for aspect::emulated

CHANGELOG.md, dpctl/tensor/libtensor/source/sorting/searchsorted.cpp, dpctl/tests/test_usm_ndarray_searchsorted.py
Fix `tensor.searchsorted` for `x1` with strides and scalar (0D) `x2` (#1693)
* Adds code to handle edge case of strided input and scalar `needle` in `searchsorted.cpp`
* Adds a test for fix to gh-1689
=> Backport gh-1693 to maintenance/0.17.x branch

conda-recipe/dpctl-post-link.sh, conda-recipe/dpctl-pre-unlink.sh
Added license headers for pre-unlink/post-link scripts.
These shell scripts are included in the shipped conda package, and require a license header.
This change is to be backported to maintenance/0.17.x once merged to the development branch.
=> Added license headers for pre-unlink/post-link scripts

conda-recipe/dpctl-post-link.sh, conda-recipe/dpctl-pre-unlink.sh
The gh-1695 added license headers for pre-unlink/post-link scripts
These shell scripts are included in the shipped conda package, and require a license header.
=> Backport pull/1695 to maintenance/0.17.x 

dpctl/CMakeLists.txt, libsyclinterface/CMakeLists.txt, scripts/gen_coverage.py
CMAKE_BUILD_TYPE=Debug is set to allow full debugging information on host (-ggdb3), but no debug information on device for spir64 target
=> Support CMAKE_BUILD_TYPE=Coverage and use it in gen_coverage.py

dpctl/tensor/libtensor/include/kernels/elementwise_functions/round.hpp
When compiled for CUDA, `std::rint` would incorrectly round values halfway between two integers towards 0 (i.e., `1.5 -> 1.`). The array API specification requires that these values be rounded to the nearest even integer instead.
To resolve this, `std::rint` has been replaced with `sycl::rint`, which does not rely on the [current floating-point rounding mode](https://en.cppreference.com/w/cpp/numeric/math/rint) ([see SYCL specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_math_functions)).
[As was pointed out at the time of implementation](https://github.com/IntelPython/dpctl/pull/1299#issuecomment-1652072391) the floating-point rounding mode can vary between devices.
=> Fixes `dpctl.tensor.round` on CUDA devices

libsyclinterface/source/dpctl_sycl_queue_interface.cpp
Fixing build break with nightly build of Intel/LLVM sycl bundle due to missing include in "dpctl_sycl_queue_interface.cpp".
=> Add missing include of sstream header

dpctl/tests/test_usm_ndarray_sorting.py
This test used to perform numerous operations on very short vectors. The change replaced that with single row-wise operation on matrices.
Now:
```
(dev_dpctl) opavlyk@opavlyk-mobl:~/repos/dpctl$ SYCL_CACHE_PERSISTENT=1 ONEAPI_DEVICE_SELECTOR=opencl:gpu python -m pytest -v -s ~/repos/dpctl/dpctl/tests/test_usm_ndarray_sorting.py::test_sort_complex_fp_nan
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.12.3, pytest-8.2.0, pluggy-1.5.0 -- /home/opavlyk/mamba/envs/dev_dpctl/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/opavlyk/repos/dpctl/.hypothesis/ex …
```
=> Improve performance of test_sort_complex_fp_nan

.github/workflows/conda-package.yml
Use it to install conda-build, to install anaconda-client.
conda-forge is free, but use of default channels may require a license.
=> Use conda-forge channels instead of default everywhere

dpctl/tensor/_manipulation_functions.py, dpctl/tests/test_usm_ndarray_manipulation.py
This PR improves the message of the ValueError raised by `broadcast_arrays` when called with no arguments.
Closes #1718
=> Improve exception raised by `broadcast_arrays` with no arguments

dpctl/tensor/_search_functions.py, dpctl/tests/test_usm_ndarray_search_functions.py
This PR proposes a change to `dpt.where` to add support for Python scalars, aligning it with `clip` and elementwise functions.
As has been pointed out by the array API community, an common use-case for `dpt.where` is supporting Python scalars. If the decision to permit them in other elementwise functions is made, `where` will likely follow suit.
Regardless of the outcome of this decision, it's sensible to support them here.
As the first argument (`condition`) does not participate in the type promotion in `where`, if both arguments are scalars, the scalars are treated as the default types for the respective kind.
=> Add Python scalar support to `dpt.where`

dpctl/tensor/_stride_utils.pxi, dpctl/tests/test_usm_ndarray_ctor.py
Moves `order` validation to the start of `_from_input_shape_strides` to guarantee it's valid even if unused.
Closes #1724
=> Fixes `_from_input_shape_strides` not validating order in all paths

dpctl/tensor/libtensor/include/kernels/sorting/sort.hpp
This PR removes an unnecessary templating of the `get_kernel` method of the kernel bundle in `sort.hpp`.
As no template parameter was given, this not only did not do anything, but was causing nightly builds to fail.
=> Remove 'template' from call to `get_kernel` method of kernel bundle in sorting

dpctl/tensor/_copy_utils.py
This PR changes `_extract_impl` in `_copy_utils` to coerce USM types to bring `extract` and boolean indexing in line with other operations in dpctl which take multiple arrays as input
Closes #1723
=> `extract` and `_extract_impl` now coerce USM type

.github/workflows/conda-package.yml, dpctl/tests/test_sycl_kernel_submit.py
See
https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/conda.html#GUID-BAA00723-86B2-4E54-9343-E817171F8A39
=> Replace use of intel channel, since it no longer works

.github/workflows/conda-package.yml
Ubuntu 20.04 will soon not be supported by oneAPI.
=> Use Ubuntu 22.04 for `conda package` workflow

.github/workflows/os-llvm-sycl-build.yml, conda-recipe/build.sh, dpctl/tests/conftest.py, dpctl/tests/test_service.py, scripts/gen_coverage.py
This PR modifies `build.sh` to post-process the wheel and remove duplicate shared objects produced by Python packaging that follows symbolic links.
Symbolic links are restored for conda after wheel is installed.
The check ``test_service.py::test_syclinterface`` was modified to ignore presence of duplicate copies of the library shared objects if `--no-sycl-interface-test` option was specified to pytest.
The option is used in 
- coverage collection script `scripts/get_coverage.py`
- in workflow which builds `dpctl` with nighly sycl bundle of intel/llvm.
-------
=> Implement manipulation of flattened SO files

CHANGELOG.md
This PR backports two commits from maintenance/0.17.x that changed `CHANGELOG.md` to set the release date for 0.17, and to add an entry to changelog about fix gh-1694
=> Backport changelong edits

README.md, docs/doc_sources/beginners_guides/installation.rst
Replace "-c intel" with "-c https://software.repos.intel.com/python/conda/" in docs and readme file.
The PyPI channel for intel packages still seems to function.
=> Replace "-c intel" in docs and readme file

.pre-commit-config.yaml, dpctl/tensor/_accumulation.py, dpctl/tensor/_copy_utils.py, dpctl/tensor/_indexing_functions.py, dpctl/tensor/_linear_algebra_functions.py, dpctl/tensor/_manipulation_functions.py, dpctl/tensor/_numpy_helper.py, dpctl/tensor/_reduction.py, dpctl/tensor/_sorting.py, dpctl/tensor/_statistical_functions.py, dpctl/tensor/_utility_functions.py, dpctl/tests/elementwise/test_log1p.py, dpctl/tests/test_usm_ndarray_manipulation.py, dpctl/tests/test_usm_ndarray_utility_functions.py
Changes that allow `dpctl`  pass tests with NumPy 2.0 in the runtime environment
=> Dpctl support for numpy 2.0 in runtime

.github/workflows/conda-package.yml, conda-recipe/meta.yaml
=> Require 2024.2.0 DPC++ compiler

examples/python/device_selection.py, examples/python/lsplatform.py
Replaced it with `ONEAPI_DEVICE_SELECTOR` environment variable.
=> Removed use of deprecated SYCL_DEVICE_FILTER

pyproject.toml
This is to align with current setup of public CI/CD.
Requirement "numpy >=1.24" was causing current build command which stipulates `conda build ... -numpy 1.23` to use latest NumPy from Intel channel (which is 1.26), and resulted in produced artifact with metainformation requiring ">=1.26,<2.0a0".
=> In pyproject change to numpy>=1.23

dpctl/tensor/_dlpack.pyx
Since DPC++ 2024.2.0 implements support for default platform context on Windows, this enables proper support for DLPack exchange on Windows.
Remove special case logic avoiding use of `platform.default_context` on Windows.
Tests exist.
=> Support DLPack on Windows

.github/workflows/conda-package.yml
This change should enable Windows build to have the same NumPy pinning as Linux, that is `>=1.23,<2.0a0` instead of `>=1.26,<2.0a0`, by ensuring that NumPy 1.23 from bootstrap channels gets installed into build environment.
=> Use bootstrap channel for Windows build too

dpctl/tensor/_set_functions.py, dpctl/tests/test_usm_ndarray_unique.py
Resolves gh-1738
Changes `unique_all` and `unique_inverse` to always return `inverse_indices` data field as array with default indexing data type.
A test added to verify this behavior.
=> Fix for gh 1738

conda-recipe/meta.yaml
This PR replaces hard pinning of compiler version in build environment to `>=`.
This allows internal CI to build with future version of compiler as well.
=> Relax hard pinning for build time compiler

README.md, docs/doc_sources/beginners_guides/installation.rst
=> Fix for gh 1749

CMakeLists.txt
Update CMakeLists.txt to pull pybind11 2.13.1 up from 2.12.0
=> Use Pybind11 2.13.1 to build dpctl

dpctl/tensor/_ctors.py, dpctl/tests/test_usm_ndarray_ctor.py
Change to `dpt.asarray` to take read-only flag value from ``__sycl_usm_array_interface__`` into account.
```IPython
In [1]: import dpctl, dpctl.utils as du, dpctl.tensor as dpt, dpnp
In [2]: x = dpt.linspace(100, 0, num=101, dtype="f8")
In [3]: x.flags["W"] = False
In [4]: y = dpnp.asarray(x)
In [5]: z = dpt.asarray(y)
In [6]: z.flags
Out[6]:
C_CONTIGUOUS : True
F_CONTIGUOUS : True
WRITABLE : False
```
=> Propagate read-only flag from sycl_usm_array_interface in asarray

dpctl/tensor/_type_utils.py, dpctl/tensor/libtensor/source/device_support_queries.cpp, dpctl/tensor/libtensor/source/device_support_queries.hpp, dpctl/tensor/libtensor/source/tensor_ctors.cpp, dpctl/tests/test_usm_ndarray_ctor.py
Changes to fix `dpctl` to pass test suite with NumPy 2.0 on Windows.
=> Align to np2 py312

dpctl/tensor/_clip.py, dpctl/tests/test_tensor_clip.py
=> Fix gh 1744 clip out of bounds scalars

.github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, libsyclinterface/source/dpctl_sycl_device_interface.cpp
This PR improves SYCLInterface functions `DPCTLDevice_CreateSubDevicesEqually`, `DPCTLDevice_CreateSubDevicesByCounts`, and `DPCTLDevice_CreateSubDevicesByAffinity`. 
These now check whether given device supports respective partition property before attempting it. If the input device does not support it, `nullptr` is returned without error logged. 
Furthermore, `DPCTLDevice_CreateSubDevicesByAffinity` checks whether the input device supports partitioning over request affinity domain, and returns `nullptr` without error logged if it does not.
This changes became necessary since nightly SYCL bundles are now built with assertions on, and runtime hits an assertion specifying `info::partition_affinity_domain::not_applicable` which is not meant to be used as an input.
=> Fix crash testing with sycl nightly runtime

dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/utils/_order_manager.py
Copy from NumPy ndarray to usm_ndarray is blocking, so release GIL.
mask-positions (cumulative value) which returns a total is blocking, so release the GIL.
=> Release GIL around blocking operations in libtensor

dpctl/tensor/_type_utils.py, dpctl/tensor/libtensor/source/device_support_queries.cpp, dpctl/tensor/libtensor/source/device_support_queries.hpp, dpctl/tensor/libtensor/source/tensor_ctors.cpp, dpctl/tests/test_usm_ndarray_ctor.py
This PR ports commits from gh-1763 to main branch. 
This would get changes to support developing `dpctl` on Windows with NumPy 2.0 in faster than gh-1760 gets merged.
=> Separate changes in pr 1763 from changes in pr 1760

dpctl/tensor/_array_api.py, dpctl/tests/test_tensor_array_api_inspection.py
This PR adds ``max dimensions`` to the ``dpctl.tensor.__array_namespace_info__().capabilities()`` dictionary.
Also revises the other keys to this dictionary, which [did not align exactly with their inclusion in the specification](https://data-apis.org/array-api/draft/API_specification/generated/array_api.info.capabilities.html).
=> Add `max dimensions` to array API capabilities

libsyclinterface/source/dpctl_sycl_device_manager.cpp
"libsyclinterface/source/dpctl_sycl_queue_manager.cpp" used `std::stringstream` but was not including `sstream` header. 
This caused build break in internal CI with forthcoming compiler.
=> Add missing include to fix build break

.github/workflows/conda-package.yml
Add setuptools to list of packages to be installed into test environment in workflow.
This aligns it with test requirements section of meta.yaml. Setuptools is required by tests that check if an extension can be built using dpctl's headers.
=> Fix testing step of conda-package workflow

dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/_type_utils.py, dpctl/tests/elementwise/test_divide.py, dpctl/tests/elementwise/test_greater.py, dpctl/tests/elementwise/test_greater_equal.py, dpctl/tests/elementwise/test_less.py, dpctl/tests/elementwise/test_less_equal.py
This PR closes #1711 by aligning `divide` with Numpy 2.0 behavior.
When a Python integer is out-of-bounds for a (strong, array) integer data type of the other input, `_resolve_weak_types_all_py_ints` uses `np.min_scalar_type` to find the minimum type that will fit it.
This does not affect the output type of comparisons or `divide`, and therefore aligns with NEP-50 while permitting such workflows as:
```
In [2]: dpt.divide(-4, dpt.asarray(3, dtype="u4"))
Out[2]: usm_ndarray(-1.3333334, dtype=float32)
```
This also fixes a bug introduced in #1650 where comparisons between `uint64` data type arrays and Python integers larger than the maximum for the default integral data type no longer worked.
=> `divide` and comparisons allow a greater range of Python integer and integer array combinations

docs/doc_sources/api_reference/dpctl/tensor.elementwise_functions.rst, docs/doc_sources/api_reference/dpctl/tensor.searching_functions.rst, docs/doc_sources/api_reference/dpctl/tensor.utility_functions.rst, dpctl/tensor/__init__.py, dpctl/tensor/_clip.py, dpctl/tensor/_reduction.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_utility_functions.py, dpctl/tests/test_tensor_diff.py, dpctl/tests/test_usm_ndarray_reductions.py
This PR proposes introducing two new functions to dpctl which will be coming to the array API specification's next version: `count_nonzero` and `diff`.
* `count_nonzero` casts an array to `bool` before calling `sum`. As dedicated kernels for `sum` of `bool` into any integer type, the summation won't require any additional copies.
* `diff` recursively takes the `n`-th forward difference along a given axis of an array. `prepend` and `append` arguments (which can be arrays or scalars) are concatenated to the input array. We diverge from the array API by permitting scalars for `prepend` and `append` as well as not constraining them to the same type as the input array
=> Implements `dpctl.tensor.count_nonzero` and `dpctl.tensor.diff`

dpctl/tensor/_utility_functions.py, dpctl/tests/test_tensor_diff.py
`diff` now raises an exception for negative `n` as is expected, rather than just defaulting to `n=1` case
Closes #1779
=> `diff` raises an exception for negative values of `n`

conda-recipe/build.sh, dpctl/tests/test_service.py, libsyclinterface/CMakeLists.txt
Turns off SOVERSION-ing of libDPCTLSyclInterface
Library SOVersioning is used to allow libraries of different versions
to coexist in the same layout. Since libDPCTLSyclInterface library
is being installed into site-packages/dpctl, and since Python does
not support multiple versions of the same package installed, such a
situation where SOVersioning is required never arises.
SOVersioning causes creation of symbolic links which are not supported
by Python wheels (symbolic links are followed and 3 hard identical
copies of the library are bing created) and only cause wheel size
to be overinflated.
With all this said, it is better to not set VERSION/SOVERSION
target property.
=> Drop use of soversion for dpctl sycl interface

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_dlpack.py
`_is_host_cpu(dl_device)` checks if user request export for host CPU device. Recognized inputs are
```
(1, 0)
(_usmarray.DLDeviceType.kDLCPU, 0)
("kDLCPU", 0)
```
Add test to exercise ``__dlpack__`` with non-default `dl_device` keyword arguments
=> Introduce _is_host_cpu utility predicate used in __dlpack__

docs/doc_sources/api_reference/dpctl/tensor.indexing_functions.rst, dpctl/tensor/__init__.py, dpctl/tensor/_copy_utils.py, dpctl/tensor/_indexing_functions.py, dpctl/tests/test_usm_ndarray_indexing.py, dpctl/tests/test_usm_ndarray_sorting.py
The function is planned for Python Array API 2024.12 specification.
=> Implement take_along_axis function per Python Array API

dpctl/memory/_opaque_smart_ptr.hpp
Added missing `#include <utility>` for definition of `std::move`.
=> Include utility for std::move

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
This PR resolves gh-1769
shape setter now accepts integer values.
=> Fix gh-1769 - setting shape by a scalar

libsyclinterface/CMakeLists.txt
Search for `ur_adapter_opencl` and `ur_adapter_level_zero` alongside `pi_opencl` and `pi_level_zero` to accomodate building with both DPC++ 2024.2.0 and open source build of DPC++, a precursor for the forthcoming version of DPC++.
intel/llvm DPC++ has made switch to using unified runtimes, and the compiler nightly build artifacts no longer contain pi_level_zero.so and pi_opencl.so libraries that we used to infer the SO-versioned name of ze_loader and OpenCL loader libraries from.
This change adds ur_adapter_* names to find_library CMake commands.
=> Search for ur_adapter_opencl alongside pi_opencl

dpctl/apis/include/dpctl4pybind11.hpp, examples/pybind11/external_usm_allocation/README.md, examples/pybind11/external_usm_allocation/example.py, examples/pybind11/external_usm_allocation/external_usm_allocation/_usm_alloc_example.cpp, examples/pybind11/external_usm_allocation/tests/test_direct.py
This PR add `dpctl::memory::usm_memory` constructor to create Python memory object from natively made allocation.
The signature is 
```cpp
usm_memory(void *usm_ptr, size_t nbytes, sycl::queue &q, std::shared_ptr<void> owner)
```
where `usm_ptr` is the pointer to USM-allocation, `nbytes` the size of allocation in bytes, `q` the queue associated with the Python memory object, and `owner` is the shared pointer whose destructor frees USM allocation via its custom deleter argument.
Example of using such constructor is added to `examples/pybind11/external_usm_allocation` extension.
=> Add usm memory constructor from existing allocation

docs/doc_sources/api_reference/dpctl/tensor.constants.rst, docs/doc_sources/api_reference/dpctl/tensor.rst, dpctl/tensor/__init__.py, dpctl/tensor/_usmarray.pyx
This PR exposes the `DLDeviceType` enumerators in dpctl.tensor.
Additionally, this PR adds documentation for the enumerator values based on the documentation in `dlpack.h` and adds `tensor.constants.rst` which contains this documentation, as well as documentation on `dpt.pi`, `dpt.e`, etc.
=> Expose `DLDeviceType` enumerator in `dpctl.tensor`

docs/doc_sources/api_reference/dpctl/flags.rst, docs/doc_sources/api_reference/dpctl/tensor.usm_ndarray.rst, dpctl/tensor/_flags.pyx, dpctl/tensor/_usmarray.pyx
This PR adds a new documentation page for the `Flags` helper class which also lists the values its `__getitem__` method will accept for dictionary-like access.
=> Documentation: Add doc page for `dpctl.tensor._flags.Flags` class

dpctl/tensor/_slicing.pxi, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_indexing.py
Resolves gh-1785
Treat `float` and `complex` types as non-booleans. They used to be treated so because `bool(key)` works for these types.
Changed exception raised for unrecognized key from `TypeError` to `IndexError`,
=> Fix for gh 1785

.github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/libtensor/include/utils/offset_utils.hpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/triul_ctor.cpp, dpctl/tests/test_usm_ndarray_print.py
Introduced class `template <typename T> dpctl::tensor::offset_utils::usm_host_allocator` deriving from `sycl::usm_allocator<T, sycl::alloc::kind::host>` that wraps the call to ``base::deallocate`` in try/catch to prevent crashes due to seemingly benign exceptions thrown by call to `sycl::free` by CPU device runtime which are under investigation.
In case such an exception is caught, a message is printed to `std::cerr`, but the exception is otherwise ignored.
Run pytest with `-s` for testing with nightly sycl bundle to be able to see such message printed.
Also remove use of `--no-sycl-interface-test` option, since DPCTLSyclInterface library is no longer so-versioned.
=> Try/catch wrap a call to deallocate in silent usm_host_allocator class to be used by std::vector for array metadata transfers 

dpctl/tensor/_dlpack.pyx, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_dlpack.py
This PR contributes to gh-1781 to support importing objects resident on other devices to oneAPI devices by copying via host.
```
In [1]: import dpctl.tensor as dpt, numpy as np
In [2]: x = dpt.ones((2, 3))
In [3]: x.device
Out[3]: Device(level_zero:gpu:0)
In [4]: y = dpt.from_dlpack(x, device=(1,0))
In [5]: type(y)
Out[5]: numpy.ndarray
In [6]: w1 = dpt.from_dlpack(y, device="opencl:gpu")
In [7]: w1.device
Out[7]: Device(opencl:gpu:0)
In [8]: w2 = dpt.from_dlpack(y, device="gpu")
In [9]: w2.device
Out[9]: Device(level_zero:gpu:0)
In [10]: w3 = dpt.from_dlpack(y, device="cpu")
In [11]: w3.device, type(w3)
Out[11]: (Device(opencl:cpu:0), dpctl.tensor._usmarray.usm_ndarray)
```
=> Enhance from_dlpack to support imported kDLCPU data to kDLOneAPI

dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/utils/offset_utils.hpp, dpctl/tensor/libtensor/include/utils/sycl_alloc_utils.hpp, dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/accumulators/accumulate_over_axis.hpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/clip.cpp, dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/elementwise_functions/elementwise_functions.hpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tensor/libtensor/source/sorting/searchsorted.cpp, dpctl/tensor/libtensor/source/triul_ctor.cpp, dpctl/tensor/libtensor/source/where.cpp
Replace ``sycl::free`` with ``sycl_free_noexcept``.
Add implementation of ``dpctl::tensor::offset_utils::sycl_free_noexcept`` templated function that calls ``sycl::free`` from within try/catch. The exception is logged to ``std::cerr``, but otherwise ignored.
Replaced calls to `sycl::free` in `host_task` with use of ``sycl_free_noexcept``.
This change should improve stability of test suite run executed on CPU device due to a known issue.
=> Replace sycl::free with sycl_free_noexcept

dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
The special casing of copy-and-cast operation after stride simplification, the branch where memcpy is applicable did not set returned event to the intended variable, but rather to the local-scoped one.
This change fixes that logic.
=> Fixed obvious unreferenced bug in copy-and-cast logic 

.github/workflows/conda-package.yml, conda-recipe/meta.yaml
Build conda packages with NumPy 2.0 in the build environment. The `meta.yaml` file for `dpctl` was changed to not use `pin_compatible('numpy', min='x.x', max='x')` per migration guidelines from conda-forge.
Testing should still pick NumPy 1.26.4 from Intel channel.
=> Build with numpy 2.0

docs/doc_sources/api_reference/dpctl/tensor.indexing_functions.rst, dpctl/tensor/__init__.py, dpctl/tensor/_copy_utils.py, dpctl/tensor/_indexing_functions.py, dpctl/tests/test_usm_ndarray_indexing.py
This PR leverages the index-building function `_range` used in `take_along_axis` to implement `dpctl.tensor.put_along_axis`.
=> Implements `dpctl.tensor.put_along_axis`

dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/utils/math_utils.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot_dispatch.hpp, dpctl/tensor/libtensor/source/reductions/argmax.cpp, dpctl/tensor/libtensor/source/reductions/argmin.cpp, dpctl/tensor/libtensor/source/reductions/logsumexp.cpp, dpctl/tensor/libtensor/source/reductions/max.cpp, dpctl/tensor/libtensor/source/reductions/min.cpp, dpctl/tensor/libtensor/source/reductions/reduce_hypot.cpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp
This is a good, recommended practice.
Moved global definition of namespaces `td_ns` and `su_ns` in 'reductions.hpp' into namespace.
Fixed resulting build breakage by including needed headers and defining those namespaces locally in affected files.
Changed definition of `logaddexp` in `math_utils.hpp` to use selector instead of if/else branches to improve performance. Switch revealed silent inefficiency from using `std::log1`p for all types (for `sycl::half` it would silently upcast to float and evaluate ``std::log1p<float>(sycl::half)``).
Used `if constexpr` to use sycl::log1p for half and single FP types. For double, use std::log1p until the issue is fixed.
=> Explicitly include headers used in the c++ file pertaining to reduction

dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/kernels/repeat.hpp, dpctl/tensor/libtensor/include/kernels/sorting/searchsorted.hpp, dpctl/tensor/libtensor/include/utils/offset_utils.hpp
Provide overloaded constructor signatures to `Strided1DIndexer` class to avoid uses of `static_cast` at constructor call sites.
Provide shortcut constructors (for zero offset).
Constructor call site use comments to specify meaning of constructor parameters.
Added few comments to GEMM code too.
---
=> Clean up uses of Strided1DIndexer

.github/workflows/conda-package.yml, .github/workflows/generate-coverage.yaml, .github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/_ctors.py, dpctl/tensor/_dlpack.pyx, dpctl/tests/test_sycl_kernel_submit.py, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_linalg.py
Fixed `test_full_gh_1230` to work with NumPy 2.1.0.
Fixed `dpt.from_dlpack` by handling `ValueError` possibly raised by `ndarray.__dlpack__` when its `dl_device` 
keyword argument is unsupported.
---
=> Fix issues for numpy 2.1.0

dpctl/tensor/CMakeLists.txt, dpctl/tensor/_ctors.py, dpctl/tensor/libtensor/source/full_ctor.cpp, dpctl/tensor/libtensor/source/tensor_ctors.cpp, dpctl/tensor/libtensor/source/zeros_ctor.cpp, dpctl/tensor/libtensor/source/zeros_ctor.hpp, dpctl/tests/test_usm_ndarray_ctor.py
Addressed outstanding FIXME note to use async call to populate array with zeros.
Added optimization for `_full_usm_ndarray` to use `handler::memset` instead of `handler::fill` for 1-byte wide types and for other types when fill value is bitwise zero.
=> tensor.zeros to use async memset

dpctl/tensor/_ctors.py, dpctl/tensor/libtensor/source/full_ctor.cpp
In `full_like(proto_array, fill_value=value_array, order='K')` the change orders kernel to copy from `value_array` into new allocation after tasks that may be populating `value_array`.
Also corrected comment in `py_internal::usm_ndarray_full` C++ function.
---
=> Contributions to strided full like pr

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp
This adds  an optimization to save rows/cols of sub-matrices stored in SLM into registers prior to summing over delta_m, delta_n and updating private result with products.
This does not make any difference in performance of the compiled code though due to compiler optimization being effective as loops are unrolled, but makes compiler's job easier and the intent clearer.
- I verified that compiler output for the kernel with this change is identical to the output before it (checked on Intel Max GPU). 
- I checked that code compiles for CUDA backend and test suite run is green
----
=> tweak to functor implementing gemm 

CMakeLists.txt, examples/pybind11/external_usm_allocation/CMakeLists.txt, examples/pybind11/onemkl_gemv/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_kernel/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_queue/CMakeLists.txt
This PR updates dpctl to use the latest pybind11 release.
Experimentally updating examples to use the latest version as well.
=> Use pybind11 `2.13.5` to build dpctl and examples

dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/repeat.cpp
This PR fixes remaining cases of compute events added to lists of host tasks in `repeat.cpp`, `boolean_advanced_indexing.cpp`, and `dot.cpp`
=> Fix additional compute events added to lists of host tasks

dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/repeat.cpp
Do not push_back compute event to host_tasks list.
This is even though sequence of tasks represented by dot_ev does contain host_task to manage temporary USM allocations.
---
=> Do not push_back compute event to host_tasks list

dpctl/tensor/_ctors.py, dpctl/tensor/libtensor/include/kernels/constructors.hpp, dpctl/tensor/libtensor/source/full_ctor.cpp, dpctl/tests/test_usm_ndarray_ctor.py
This PR implements a strided kernel for `full` to enable `order="K"` support in `empty_like`, `full_like`, `ones_like`, and `zeros_like`.
=> Implement dedicated strided `full` kernel and add `order="K"` support to constructors

README.md, docs/doc_sources/beginners_guides/installation.rst
This PR removes the wheels installation with Anaconda from the instruction, since we will no longer be able to upload packages to Anaconda. And so far,  wheels can only be uploaded on Pypi
=> Remove the wheels installation with anaconda from the instruction

dpctl/tensor/_clip.py, dpctl/tensor/_statistical_functions.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/true_divide.hpp, dpctl/tensor/libtensor/source/elementwise_functions/true_divide.cpp, dpctl/tests/elementwise/test_divide.py
This PR proposes adding a utility function `_divide_by_scalar` to the `_tensor_elementwise_impl` sub-module.
This function improves the performance of division where the denominator is a Python scalar by avoiding a call to `asarray` and allocating device memory.
This function is also deployed to the statistical functions.
Slips in a change to remove a superfluous `wait()` from `_clip.py`
=> Add `dpctl.tensor._tensor_elementwise_impl._divide_by_scalar` utility function and use it in statistical functions

conda-recipe/meta.yaml
We only patched cmake to work around a problem with IntelSYCL and cmake 3.26, it works out of the box with newer versions of cmake.
=> No need to pin cmake used on Windows to 3.26

.github/workflows/python_style_checks.yml, CHANGELOG.md
Version in [pre-commit config](https://github.com/IntelPython/dpctl/blob/master/.pre-commit-config.yaml) differed from the version in the workflow, which could lead to conflicts between the workflow and pre-commit.
=> Updates black version used in Python code style workflow

CHANGELOG.md, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_usmarray.pyx, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_bitwise_and.py, dpctl/tests/elementwise/test_bitwise_left_shift.py, dpctl/tests/elementwise/test_bitwise_or.py, dpctl/tests/elementwise/test_bitwise_xor.py, dpctl/tests/elementwise/test_divide.py, dpctl/tests/elementwise/test_elementwise_classes.py, dpctl/tests/elementwise/test_floor_divide.py, dpctl/tests/elementwise/test_multiply.py, dpctl/tests/elementwise/test_pow.py, dpctl/tests/elementwise/test_remainder.py, dpctl/tests/elementwise/test_subtract.py
This pull request proposes a new implementation for in-place element-wise operators which permits casting equivalent to `"same_kind"`
This allows such operations as
```
In [1]: import dpctl.tensor as dpt, dpctl, numpy as np
In [2]: x = dpt.ones((10, 10), dtype="i4")
In [3]: y = dpt.ones((10, 10), dtype="i8")
In [4]: x += y
In [5]: x
Out[5]:
usm_ndarray([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)
```
This PR maintains the inclusion of (conditionally used) in-place kernels in element-wise operators when …
=> Permit `"same_kind"` casting for `usm_ndarray` element-wise in-place operators

CHANGELOG.md, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_type_utils.py, dpctl/tensor/_usmarray.pyx, dpctl/tests/elementwise/test_add.py, dpctl/tests/elementwise/test_bitwise_and.py, dpctl/tests/elementwise/test_bitwise_left_shift.py, dpctl/tests/elementwise/test_bitwise_or.py, dpctl/tests/elementwise/test_bitwise_xor.py, dpctl/tests/elementwise/test_divide.py, dpctl/tests/elementwise/test_elementwise_classes.py, dpctl/tests/elementwise/test_floor_divide.py, dpctl/tests/elementwise/test_multiply.py, dpctl/tests/elementwise/test_pow.py, dpctl/tests/elementwise/test_remainder.py, dpctl/tests/elementwise/test_subtract.py
This PR backports all changes from gh-1827 except two which modified the change-log.
The change-log would need to be updated for 0.18 release, and that change backported to main branch.
=> Backport gh-1827

CHANGELOG.md
This PR removes entry to CHANGELOG in 0.19 section after the change from gh-1827 was backported to 0.18 in gh-1830
=> [MAINT] Update changelog after backport gh 1830

dpctl/tests/__init__.py, dpctl/tests/conftest.py, dpctl/tests/test_sycl_context.py, dpctl/tests/test_sycl_device.py, dpctl/tests/test_sycl_event.py, dpctl/tests/test_sycl_platform.py, dpctl/tests/test_sycl_queue.py, dpctl/tests/test_tensor_accumulation.py, dpctl/tests/test_tensor_asarray.py, dpctl/tests/test_tensor_clip.py, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_dlpack.py, dpctl/tests/test_usm_ndarray_indexing.py, dpctl/tests/test_usm_ndarray_print.py, dpctl/tests/test_usm_ndarray_search_functions.py, dpctl/tests/test_usm_ndarray_searchsorted.py
Since dpctl/tests does not contain __init__.py, the standard invocation of pytest failed, rendering it impossible to run test suite without checkout out source tree.
This change should enable the run out of the box
=> Enable pytest --pyargs dpctl.tests

CHANGELOG.md, dpctl/tests/__init__.py, dpctl/tests/conftest.py, dpctl/tests/test_sycl_context.py, dpctl/tests/test_sycl_device.py, dpctl/tests/test_sycl_event.py, dpctl/tests/test_sycl_platform.py, dpctl/tests/test_sycl_queue.py, dpctl/tests/test_tensor_accumulation.py, dpctl/tests/test_tensor_asarray.py, dpctl/tests/test_tensor_clip.py, dpctl/tests/test_usm_ndarray_ctor.py, dpctl/tests/test_usm_ndarray_dlpack.py, dpctl/tests/test_usm_ndarray_indexing.py, dpctl/tests/test_usm_ndarray_print.py, dpctl/tests/test_usm_ndarray_search_functions.py, dpctl/tests/test_usm_ndarray_searchsorted.py
Backport of gh-1833 from development branch to maintenance/0.18.x
=> Backport gh 1833

CHANGELOG.md
This PR is to port change-log entry in 0.18 section to development branch
=> Add changelog for backport of gh-1833

.github/workflows/conda-package.yml, CHANGELOG.md
Try not building for 3.9 to check if this fixes CI
=> Triage CI failure

dpctl/tests/test_sycl_kernel_submit.py
This PR reverts work-around added to "test_sycl_kernel_submit.py" to fix test due to issue with MKL 2024.2.0, as used by `mkl_umath`. The issue is fixed in MKL 2024.2.1
=> Revert work-around for problem in MKL 2024.2.0, fixed in 2024.2.1

.github/workflows/conda-package.yml, .github/workflows/cpp_style_checks.yml, .github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml, .github/workflows/openssf-scorecard.yml, .github/workflows/os-llvm-sycl-build.yml, .github/workflows/pre-commit.yml, .github/workflows/python_style_checks.yml
Add `timeout-minutes` property, https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
This ensures that run-away jobs, like one encountered in gh-1836 would not take extraordinarily long to fail.
=> Add job explicit, conservative job timeouts

dpctl/tensor/libtensor/source/sorting/argsort.cpp, dpctl/tensor/libtensor/source/sorting/sort.cpp
This changes behavior of `py_sort` C++ function to throw `py::value_error` exception should either input array be not C-contiguous.
=> Throw exception in py_sort if inputs are not C-contiguous

CHANGELOG.md, conda-recipe/meta.yaml
dpctl was still specifying run-time dependency on level-zero though run_export of level-zero-devel.
=> Ignore run export on level-zero

.github/workflows/conda-package.yml, CHANGELOG.md
Change workflow script conda-package.yaml, to use `miniforge-variant: Miniforge3` to address warnings.
=> Use Miniforge3 variant, instead of deprecated Mambaforge

CHANGELOG.md, CMakeLists.txt, examples/pybind11/external_usm_allocation/CMakeLists.txt, examples/pybind11/onemkl_gemv/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_kernel/CMakeLists.txt, examples/pybind11/use_dpctl_sycl_queue/CMakeLists.txt
Bump pybind11 version used to build `dpctl` and its examples to 2.13.6
=> Update to pybind11 2.13.6

CHANGELOG.md, dpctl/tensor/libtensor/include/utils/offset_utils.hpp
Removed `#include <exception>` line from "offset_utils.hpp".
The file uses none of the functionality defined in that header.
=> Remove #include <exception> line from offset_utils.hpp

CHANGELOG.md, dpctl/tensor/CMakeLists.txt, dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
The "simplify_iteration_space.cpp" was being compiled as source for every pybind11 native extension.
This change compiles it as a static library once, and links the library into pybind11 native extension modules, shaving some build time. 
"simplify_iteration_space.cpp" also no longer includes "dpctl4pybind11.hpp", and hence does not need SYCL target enabled, compiling it as ordinary host code.
---
=> Simplify iteration space as static library

CHANGELOG.md
This PR sets release date of dpctl=0.18.0 in CHANGELOG to Sept. 26, 2024
---
=> Set release date for 0.18 to Sep 26, 2024

CHANGELOG.md, dpctl/tensor/CMakeLists.txt, dpctl/tensor/libtensor/include/kernels/copy_as_contiguous.hpp, dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp, dpctl/tensor/libtensor/source/copy_as_contig.cpp, dpctl/tensor/libtensor/source/copy_as_contig.hpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp, dpctl/tensor/libtensor/source/tensor_ctors.cpp, dpctl/tests/test_tensor_asarray.py
This PR adds specialized kernels to copy `usm_ndarray` to C-/F-contiguous destinations of the same shape and the same dtype.
It also adds dedicated kernels to copy batches of square matrices (which are views of F-contig matrices) to C-contiguous destinations, and batches of square matrices which are views of C-contig matrices to F-contiguous destinations. The intended usage is to speed-up conversion from C-contig batch of square matrices to F-contig batch of square matrices.
Tests are added.
=> Dedicated code to copy array to C-contig/F-contig destinations

dpctl/apis/include/dpctl4pybind11.hpp, dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/kernels/copy_as_contiguous.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/dot_product.hpp, dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp, dpctl/tensor/libtensor/include/kernels/reductions.hpp, dpctl/tensor/libtensor/include/utils/output_validation.hpp, dpctl/tensor/libtensor/include/utils/type_dispatch.hpp, dpctl/tensor/libtensor/include/utils/type_utils.hpp, dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/accumulators/accumulate_over_axis.hpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp, dpctl/tensor/libtensor/source/clip.cpp, dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp, dpctl/tensor/libtensor/source/elementwise_functions/elementwise_functions.hpp, dpctl/tensor/libtensor/source/elementwise_functions/true_divide.cpp, dpctl/tensor/libtensor/source/full_ctor.cpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp, dpctl/tensor/libtensor/source/repeat.cpp, dpctl/tensor/libtensor/source/sorting/searchsorted.cpp, dpctl/tensor/libtensor/source/sorting/sort.cpp, dpctl/tensor/libtensor/source/triul_ctor.cpp, dpctl/tensor/libtensor/source/where.cpp, dpctl/tensor/libtensor/source/zeros_ctor.cpp
This PR 
- adds missing `#include <stdexcept>` to files that use `std::runtime_error` exception
- adds missing `#include <new>` to files that use `std::bad_alloc` exception
- functions that submit kernels which are compiled by means of calling `sycl::get_kernel_bundle<sycl::bundle_state::executable>` now use `cgh.use_kernel_bundle(kb)` to avoid recompiling that kernel.
---
=> Technical debt

.github/workflows/conda-package.yml
The `test_windows` step of the workflow is currently broken with 
```
Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
D:\a\dpctl\dpctl>L "C:\Users\runneradmin\miniconda3\condabin\..\Scripts\conda.exe"   install --name base "conda-build=*" 
Warning: 'L' is not recognized as an internal or external command,
operable program or batch file.
'L' is not recognized as an internal or external command,
operable program or batch file.
Error: The process 'C:\Users\runneradmin\miniconda3\condabin\conda.bat' failed with exit code 9009
```
Use miniforge and conda-forge channel only, to avoid mixing defaults and conda-forge.
Also fix steps to create sub-directories in the …
=> Use Miniforge, use conda-forge channel

CHANGELOG.md, dpctl/tensor/_utility_functions.py
This PR fixes a warning caused by the docstring for `diff` incorrectly indenting the description of the output shape.
Closes #1849
=> Fix documentation warning when rendering `diff` docstring

README.md, docs/doc_sources/beginners_guides/installation.rst
TDO team has deployed pypi channel, which will be used starting from the 2025 release. This PR updates the instructions by adding the installation from Intel pypi channel
=> Add Intel channel for installing wheels

CHANGELOG.md, dpctl/tensor/libtensor/include/kernels/sorting/sort.hpp, dpctl/tensor/libtensor/source/sorting/argsort.cpp
This change modifies implementation of `tensor.argsort` functions making is about 2x faster.
Instead of implementing argsort as sort over structures (index, value),
with subsequent projection to index, it is now implemented as sort
over linear indices themselves, with dereferencing comparator, and
subsequent mapping from linear index to row-wise index.
On Iris Xe, `tensor.argsort` call took 215 ms to find sorting permutation for
vector of 5670000 elements of type int32, and it now takes 106 ms.
The new implementation no longer makes temporary allocations for
storing indices. Previously, it would allocate 
`2*(sizeof(ValueT) + sizeof(IndexT))`, now it just uses the output 
allocation.
Tests exist.
---
=> Argsort performance improvement

CHANGELOG.md, docs/doc_sources/beginners_guides/installation.rst, dpctl/tensor/_dlpack.pyx, dpctl/tensor/_indexing_functions.py, dpctl/tensor/_usmarray.pyx
This PR fixes several warnings raised when buildings docs using `scripts/gen_docs.py`.
=> [MAINT] Fix warnings when building docs

CHANGELOG.md, dpctl/tensor/libtensor/include/kernels/sorting/sort.hpp
The threshold lowered from 64 elements to sort, to 16 elements. This recovers monotonicity of run-times curve.
When number of array elements along the axis we sort is less than the threshold, a quadratic complexity insertion sort is used. Too high a value of the threshold (64) made for the artifact, where sorting 63 elements took several times longer than sorting 65 elements.
Setting it to 16 recovers monotonicity (sorting 16 elements is not slower than sorting 17 elements).
=> Lower the threshold to use sequential sort

dpctl/_host_task_util.hpp, dpctl/tensor/libtensor/source/accumulators/accumulate_over_axis.hpp, dpctl/tensor/libtensor/source/elementwise_functions/elementwise_functions.hpp, dpctl/tensor/libtensor/source/linalg_functions/dot.cpp, dpctl/tensor/libtensor/source/reductions/reduction_over_axis.hpp
Use of std::exception type (in `catch(const std::exception &e) {`), requires `#include <exception>`.
=> Add missing #include <exception>

dpctl/tensor/_manipulation_functions.py, dpctl/tensor/libtensor/source/copy_for_roll.cpp, dpctl/tests/test_usm_ndarray_manipulation.py
Closes gh-1857
Test added based on example provided in the issue.
=> Roll must reduce shift steps by size along axis

CHANGELOG.md
Backport changes to `CHANGELOG.md` made in maintenance/0.18.x branch
=> Added entry to changelog for 0.18.1

CHANGELOG.md, dpctl/tensor/_ctors.py, dpctl/tests/test_usm_ndarray_ctor.py
This PR proposes adding a check to `full` when the value to construct the array with is not a scalar value, i.e., some type of object or a string.
Previously these cases would fail, but pybind11 would throw RuntimeError. Now, a TypeError is thrown from Python, and the result array is never allocated, preventing wasted memory allocation.
=> Improve `dpctl.tensor.full` error for invalid `fill_value`

dpctl/tensor/CMakeLists.txt, dpctl/tensor/_sorting.py, dpctl/tensor/libtensor/include/kernels/sorting/merge_sort.hpp, dpctl/tensor/libtensor/include/kernels/sorting/radix_sort.hpp, dpctl/tensor/libtensor/source/sorting/radix_argsort.cpp, dpctl/tensor/libtensor/source/sorting/radix_sort.cpp, dpctl/tensor/libtensor/source/tensor_sorting_radix.cpp
This PR removes template parameter `is_ascending` from radix sort functions and introduces it as function call argument instead. 
This halves the binary size due to reduction in device code portion. Furthermore, radix sorting functions are singled out into a dedicated Python module `_tensor_sorting_radix_impl` further reducing the build time and memory footprint and provide increased parallelization opportunities to the linker. 
The overall build time drops from 45 minutes to 33 minutes on my Core i7 laptop.
=> Change descending from template parameter to an argument

.github/workflows/conda-package.yml, .github/workflows/generate-coverage.yaml, .github/workflows/generate-docs.yml
Change to "generate-coverage" workflow to adapt to changes in oneAPI Basekit 2025.0
- Install Unified Memory Framework (UMF) component
- Install `hwloc` utility which is required by UMF
---
=> Update generate-coverage workflow to work with oneAPI 2025

.github/workflows/conda-package.yml
The setup-miniconda action is removing 'defaults' channels now, and attempt at repeated removal trips an error.
=> Delete remove defaults channel step from test_windows job

dpctl/tensor/libtensor/include/kernels/copy_as_contiguous.hpp
This PR contributes to gh-1890, by streamlining code for performing copy to contiguous array.
1. Save common subexpressions to variables
2. Sub-group size type changed to uint16 (from uint32)
3. sg.get_local_range() replaced with sg.get_max_local_range()
This is safe to do since work-group size is chosen to be
a multiple of sub-group size for all possile choices
of sub-group size (1, 8, 16, 32, 64)
4. Simplified computation of base value in generic branch for
complex types, or when sg_load is disabled, to avoid a
division (and left a comment)
---
=> Contribution to fix gh 1887

CHANGELOG.md, dpctl/tensor/libtensor/include/kernels/copy_as_contiguous.hpp, dpctl/tests/test_usm_ndarray_ctor.py
This PR resolves https://github.com/IntelPython/dpctl/issues/1887
When using sub-group loads and stores, certain alignment of pointers is required. Copies to C-contiguous memory were not properly checking alignment, which would lead to incorrect results.
Before, using the example in #1887:
```
padded = dpt.zeros((8, 23), dtype=dpt.int64)
value = dpt.asarray([[0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
right_slice = (slice(1, None, None), Ellipsis)
padded[right_slice] = value
print(padded)
#usm_ndarray([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
```
with this change:
```
padded = dpt.zeros((8, 23), dtype=dpt.int64)
value = dpt.asarray([[0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
```
=> Check pointer alignment when copying from strided array to C-contiguous array

dpctl/tensor/libtensor/include/kernels/integer_advanced_indexing.hpp, dpctl/tensor/libtensor/include/utils/indexing_utils.hpp
This PR fixes build break in gh-1894.
In `indexing_utils.hpp` I moved common constexpr variables out of branches .
Replaced `static constexpr` with `constexpr`. Since these are
defined in procedure scope, `static` is not required.
Introduced typed temporary variables, so that type deduction
for `sycl::min`, `sycl::max`, `sycl::clamp` can work and removed
explicit use of their template parameter.
Added explicit static_cast on value of `projected` variable
computed as IndT type.
In `integer_advanced_indexing.hpp`, I made `ProjectT proj` constexpr.
---
=> Contribution to 1894

CHANGELOG.md, dpctl/_sycl_timer.py, dpctl/tests/test_sycl_timer.py, dpctl/utils/src/order_keeper.cpp
This PR adds Python API to submit empty body single task to a queue. `dpctl.SyclTimer` is modified to acquire `device_timer` keyword argument with supported values being `"queue_barrier"` (legacy behavior, a default), and `"order_manager"`.
With `"order_manager"`, timer submits the empty body single tasks (fence tasks) to the queue, using order manager to order them so as to fence timed submissions. For example, execution of the following snippet:
```python
prior_ops
with timer(profiling_queue):
compute_using_the_queue
subsequent_ops
```
results in a task graph `[prior_tasks] -> [fence_start_task] -> [ compute_tasks] -> [fence_end_task] -> [subsequent_tasks]`.
Timer uses profiling data from events associated with fence tasks to estimate execution time of compute tasks as measured by the …
=> Add alternative implementation of device timer to SyclTimer class

dpctl/tensor/libtensor/include/kernels/accumulators.hpp
Checking in small change in accumulator header file. 
It saved repeated sub-expressions into a temporary to clean up the code and hopefully reduce the size of the binary by a few bytes.
=> [MAINT] Save repeated expression in accumulation functor operator to a variable

CHANGELOG.md, dpctl/tensor/libtensor/include/utils/math_utils.hpp
The PR proposes to add missing `sycl/sycl.hpp` include to `math_utils.hpp` header file, because `sycl::half` type and functions from `sycl` namespace are used there.
Otherwise the isolated include, like
```cpp
#pragma once
#include <complex>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include "utils/math_utils.hpp"
// ... some code
```
used by an extension code will produce compilation errors:
```bash
math_utils.hpp:121:24: error: no member named 'log' in namespace 'sycl'; did you mean simply 'log'?
math_utils.hpp:130:31: error: no member named 'log1p' in namespace 'sycl'; did you mean simply 'log1p'?
...
```
=> Add missing include to `math_utils.hpp`

CHANGELOG.md, dpctl/tensor/libtensor/include/utils/type_utils.hpp
Current implementation of `is_complex<T>` is limited in dpctl tensor headers. It doesn't consider CV-qualifiers for a type.
While STL wrappers of DPC++ has more complete implementation.
The PR proposes to align with the STL wrappers and to add support of CV-qualifiers in `is_complex<T>` implementation. And also it suggests to add `is_complex_v<T>` helper.
The PR would help to simplify implementation of `histogramdd` extension in DPNP.
=> Add support of CV-qualifiers in `is_complex<T>` helper

.github/workflows/conda-package.yml
Remove use of nodefaults channel, use conda-remove-defaults: true instead
This change is prompted by CI warning:
```
'nodefaults' channel detected: will remove 'defaults' if added implicitly.
In the future, 'nodefaults' as a way of removing 'defaults' won't be
supported. Please set 'conda-remove-defaults' = 'true' to remove this warning.
```
---
=> Address CI warnings to not use nodefaults channel

.github/workflows/cron-run-tests.yaml
This workflow runs nightly, install dpctl from
dppy/label/dev, and runs tests
This ensures tests are run even if no development happens. The intent is it might catch issues due to external dependency updates, and such.
The work-flow can also be triggered manually.
=> Add a work-flow to run nightly tests of dpctl

CHANGELOG.md, dpctl/tensor/_type_utils.py, dpctl/tests/test_usm_ndarray_manipulation.py
Backport fix for gh-1874 from gh-1877 to maintenance/0.18.x branch
=> Backport gh1874

dpctl/tensor/_copy_utils.py, dpctl/tests/test_usm_ndarray_indexing.py
Closes gh-1913
Add special-casing for empty mask in the implementation of `tensor.place`, which is used by `usm_ndarray.__setitem__` as well.
Added tests.
=> Fix 1913 empty boolean mask

dpctl/tensor/libtensor/include/kernels/sorting/radix_sort.hpp
1. Add missing `#include <array>` needed since `std::array` is used several times in the code.
2. Made `peer_helper` class specializations members const, as well as marking peer_contribution method const.
This allows to make `peer_prefix_hlp` class instance const as well.
3. Added a comment to why subgroup_ballot algorithm for peer helper is only applicable for sub-groups with sizes 32 and narrower.
---
=> Technical debt changes in radix_sort.hpp

dpctl/tensor/_dlpack.pyx
Closes gh-1917.
The change to docstring documents that `tensor.from_dlpack` may return ``numpy.ndarray`` or ``tensor.usm_ndarray`` and stipulates when that may happen.
=> Updated from_dlpack docstring

dpctl/tests/test_usm_ndarray_dlpack.py
The docstring stated that this container implemented legacy DLPack protocol, while it implements DLPack 1.0
=> Correct docstring of Container helper class

CHANGELOG.md, dpctl/__init__.py, dpctl/_init_helper.py
Backporting gh-1922 to maintenance/0.18.x, which fixes gh-1745
=> Backport gh-1922

CHANGELOG.md
Since cherry-picking was causing conflicts, copy them over and add manually even though that creates conflicts with further backporting to 0.18.x branch.
=> Add changes to changelog from maintenance/0.18.x branch

conda-recipe/conda_build_config.yaml, conda-recipe/meta.yaml
Install `{{ stdlib('c') }}` into build environment. 
This requires adding `conda_build_config.yaml` where the version of the compiler as well as standard libraries be specified.
@ekomarova @xaleryb These changes break internal CI. Is there a way to align with conda-forge?
=> Align recipe's meta yaml with conda-forge

CHANGELOG.md, dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
This PR is motivated by gh-1249. It changes masked extract, masked place and nonzero kernels to reduce global memory bandwidth through use of shared local memory.
Kernels are changes from being range-based, to being nd_range-based. Work-items of work-group collectively load `lws + 1` elements of `cumulative_sum` values into local accessor. Each work-item reads two values of this cumulative sum, and reading them from SLM reduces the number of GM accesses by a factor of 2. 
For masked extract, that is called in gh-1249, this PR introduce contiguous `src` array specialization to improve performance, since `x_2d[m_2d]` runs slower than `x_2d_flat[m_2d_flat]`.
=> Boolean indexing improvements

examples/cython/sycl_buffer/src/use_sycl_buffer.hpp, examples/cython/sycl_buffer/syclbuffer/_buffer_example.pyx, examples/cython/use_dpctl_sycl/use_dpctl_sycl/utils.hpp, examples/cython/usm_memory/src/sycl_blackscholes.hpp, examples/pybind11/onemkl_gemv/cpp/main.cpp, examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp, examples/pybind11/onemkl_gemv/sycl_gemm/cg_solver.hpp, examples/pybind11/use_dpctl_sycl_kernel/use_kernel/_example.cpp, examples/pybind11/use_dpctl_sycl_queue/use_queue_device/_example.cpp
Replace ``#include <CL/sycl.hpp>`` with ``#include <sycl/sycl.hpp>`` per deprecation warning
=> Fix deprecation warnings in example/ sources

CHANGELOG.md, dpctl/tensor/libtensor/include/utils/sycl_utils.hpp
The function used to perform custom reduction in a single
work-item (leader of the work-group sequentially).
It now does so cooperatively few iterations, and
processes remaining non-reduced elements sequentially
in the leading work-item.
The custom_reduce_over_group got sped up about a factor of 3x.
The following now shows timing of the reduction kernel
```
unitrace -d -v -i 20 python -c "import dpctl.tensor as dpt; dpt.min(dpt.ones(10**7, dtype=dpt.float32)).sycl_queue.wait()"
```
or par (less that 10%) slower than the int32 kernel, which uses
built-in sycl::reduce_over_group:
```
unitrace -d -v -i 20 python -c "import dpctl.tensor as dpt; dpt.min(dpt.ones(10**7, dtype=dpt.int32)).sycl_queue.wait()"
```
Also fixed uses of group_load/group_store and enabled them for 2025.0 compiler. …
=> Speed up custom reductions

dpctl/tensor/_indexing_functions.py, dpctl/tests/test_usm_ndarray_indexing.py
This PR proposes allowing indices of type `uint64` in `take_along_axis` and `put_along_axis`.
With current behavior, these functions build a list of indices using the default index type. If the input indices are `uint64` and the input array is of dimension greater than 1, when the padded indices are constructed, the function will fail if the default index type is `int64`.
Edit: Closes gh-1936
=> Allow uint64 indices in `dpt.take_along_axis` and `dpt.put_along_axis`

.github/workflows/conda-package.yml, CHANGELOG.md, dpctl/_host_task_util.hpp, dpctl/apis/include/dpctl4pybind11.hpp
Fix native extension code for Python 3.13 (account to removal of `_Py_IsFinilizing()` as it is replaced by `Py_IsFinilizing()`).
Build and test with Python 3.13 in conda package workflow.
=> Support python 3.13

.github/workflows/run-tests-from-dppy-bits.yaml
This change expands matrix of Python versions for which nightly test runs are scheduled to include Python 3.13.
=> Run nightly tests with Python 3.13 as well

dpctl/tensor/libtensor/include/kernels/sorting/merge_sort.hpp, dpctl/tensor/libtensor/include/kernels/sorting/radix_sort.hpp, dpctl/tensor/libtensor/include/kernels/sorting/sort_utils.hpp, dpctl/tensor/libtensor/include/kernels/sorting/topk.hpp, dpctl/tensor/libtensor/include/utils/sycl_alloc_utils.hpp, dpctl/tests/test_usm_ndarray_top_k.py
This PR builds on top of feature/topk branch. 
It adds `iota_impl` in new `sort_utils.hpp` file, and uses it in `merge_sort.hpp`, `radix_sort.hpp` and `topk.hpp`.
It also fixes possible USM allocation leak in exception handling.
=> Add iota kernel

dpctl/tests/test_usm_ndarray_top_k.py
This PR adds a test file with few basic tests for `top_k`. To be extended.
=> Add test file for top_k functionality

.github/workflows/os-llvm-sycl-build.yml
Use Ubuntu 24.04 to run the OS-LLVM workflow to build dpctl with nightly SYCL bundle DPC++ compiler, attempting to fix execution failure of clang++ due to old system `glibc` library.
=> Use Ubuntu 24.04 to run the OS-LLVM workflow to build dpctl with nightly SYCL bundle DPC++ compiler

.github/workflows/os-llvm-sycl-build.yml, dpctl/tensor/libtensor/include/kernels/sorting/radix_sort.hpp, dpctl/tensor/libtensor/include/kernels/sorting/sort_utils.hpp, dpctl/tensor/libtensor/include/kernels/sorting/topk.hpp, dpctl/tests/test_usm_ndarray_top_k.py
Due to a reported issue with OpenCL:CPU device implementation, the kernel for short inputs and short signed integral types may produce incorrect results when compiled for short SIMD width (as chosen automatically for AMD EPYC 7763 64 Processors CPU).
A work-around is to introduce a redundant barrier call (only for CPU devices when sub-group is short).
Also edits made while triaging the issue are applied: counters for short input arrays are stored in 16-bit unsigned integers, rather than in 32-bit ones, `uint16_t` replaced with `std::uint16_t`, etc.
Tests for `tensor.top_k` were expanded to ensure 100% coverage.
=> Work-around for issue with CPU driver, add tests

dpctl/tensor/libtensor/include/kernels/clip.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/conj.hpp, dpctl/tensor/libtensor/include/utils/sycl_alloc_utils.hpp, dpctl/tensor/libtensor/include/utils/type_dispatch_building.hpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp, dpctl/tensor/libtensor/source/integer_advanced_indexing.hpp, libsyclinterface/source/dpctl_sycl_queue_interface.cpp, libsyclinterface/tests/test_sycl_context_interface.cpp, libsyclinterface/tests/test_sycl_device_aspects.cpp, libsyclinterface/tests/test_sycl_device_interface.cpp, libsyclinterface/tests/test_sycl_device_manager.cpp, libsyclinterface/tests/test_sycl_device_subdevices.cpp, libsyclinterface/tests/test_sycl_kernel_bundle_interface.cpp, libsyclinterface/tests/test_sycl_kernel_interface.cpp, libsyclinterface/tests/test_sycl_queue_interface.cpp, libsyclinterface/tests/test_sycl_queue_submit.cpp, libsyclinterface/tests/test_sycl_queue_submit_local_accessor_arg.cpp, libsyclinterface/tests/test_sycl_usm_interface.cpp
Fixed a single instance of unqualified `size_t` picked up after rebasing.
Also fixed unqualified `uint8_t`, `uint16_t`, etc. in `dpctl/tensor/libtensor`.
=> Additional qualified cpp types

dpctl/tensor/libtensor/source/reductions/prod.cpp, dpctl/tensor/libtensor/source/reductions/sum.cpp, dpctl/tests/test_tensor_sum.py
This PR proposes the addition of `bool->bool` kernels to the dtype matrices for `sum` and `prod`
The expected behavior of the reductions is that if an optimized kernel doesn't exist, the input should be cast to the requested output type before performing the reduction whenever possible. But as `bool->bool` loops did not exist, if a user requested bool, it would be reduced in the input type and cast to bool after.
In some edge cases, this would produce unexpected results.
Resolves #1944
=> Add dedicated reduction kernels for sums and products of boolean arrays

dpctl/tensor/libtensor/source/triul_ctor.cpp
Add missing includes to `triul_ctor.cpp`. Use `std::move` to move vector of shared pointers into lambda function executed by `host_task` for lifetime management of temporaries.
=> Avoid copy in triul ctor host task

CHANGELOG.md, dpctl/tensor/_ctors.py, dpctl/tests/test_tensor_asarray.py
This PR changes `dpctl.tensor.asarray` function to recognize objects that implement `__usm_ndarray__` protocol and expect this property to return `dpctl.tensor.usm_ndarray` instance corresponding to the content of the object. 
This property is intended to speed-up conversion from `dpnp.ndarray` to `dpt.usm_ndarray` in `x = dpt.asarray(dpnp_array_obj)`.
The input object that implements `__usm_ndarray__` is recognized as owner of USM allocation that is managed by a smart pointer, and asynchronous deallocation of `x` need not involve GIL.
=> Tensor asarray support for usm ndarray protocol

CMakeLists.txt, dpctl/CMakeLists.txt, dpctl/tensor/CMakeLists.txt, dpctl/utils/CMakeLists.txt
See https://www.intel.com/content/www/us/en/developer/articles/technical/sycl-compilation-device-image-compression.html
It is applicable for any SYCL targets. This change results in 28.4% reduction in shared objects sizes with offload sections on Linux.
```
(* in base branch *)
(dev_dpctl) :~/repos/dpctl$ ls -l dpctl/tensor/_tensor*_impl*
-rw-r--r-- 1 me myself 36403864 Jan  9 16:32 dpctl/tensor/_tensor_accumulation_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 me myself 38666520 Jan  9 16:32 dpctl/tensor/_tensor_elementwise_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 me myself 60695704 Jan  9 16:32 dpctl/tensor/_tensor_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 me myself 16431464 Jan  9 16:32 dpctl/tensor/_tensor_linalg_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 …
```
=> Use --offload-compress linker option to compress offload sections

dpctl/tensor/_usmarray.pyx
This PR fixes a small nonconformity with the array API by making `stream` a keyword-only argument, and adds a test for `stream`.
Closes https://github.com/IntelPython/dpctl/issues/1965
=> Make `stream` a keyword-only argument in `usm_ndarray.to_device`

CHANGELOG.md, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
Implement `usm_ndarray.__array__` that raises `TypeError` to disallow implicit conversion of `usm_ndarray` to `numpy.ndarray` with `dtype=object`.
=> Usm ndrray array protocol must raise

dpctl/tests/elementwise/test_add.py, dpctl/tests/test_tensor_clip.py
Corrected uses of `np.empty_like(usm_ar)` in test suite which error own due to recent change disallowing implicit data conversions.
These were subtle, albeit harmless, bugs.
=> Replace np.empty_like(usm_ndarray_inst) with np.empty(shape, dtype=dt)

dpctl/tensor/libtensor/include/kernels/sorting/merge_sort.hpp, dpctl/tensor/libtensor/include/kernels/sorting/radix_sort.hpp
Use forwarding references to avoid copies of comparator cpp-function, and of iterator.
Also avoid invoking `map_back` kernel in `argsort` when arg-sorting 1d array, i.e. when `iter_nelems == 1`.
=> Avoid copies in sorting

dpctl/_sycl_device.pyx, dpctl/tensor/__init__.py, dpctl/tensor/_dldevice_conversions.py, dpctl/tensor/_dlpack.pxd, dpctl/tensor/_dlpack.pyx, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_sycl_context.py, dpctl/tests/test_sycl_device.py, dpctl/tests/test_usm_ndarray_dlpack.py
This PR proposes improving dpctl's interoperability with DLPack by
- Adding a new method `get_device_id` to `dpctl.SyclDevice` which returns the ordinal ID of a root device
- Adding new functions `dpctl.tensor.dldevice_to_sycldevice` and its converse `dpctl.tensor.sycldevice_to_dldevice` which function as conversions between `dpctl.SyclDevices` and the DLPack device tuples returned by `arr.__dlpack_device__()` for some array `arr` from an arbitrary array library
Closes #1929
=> Improve interoperability between `SyclDevice` and DLPack devices

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
If `stream` argument is not `dpctl.SyclQueue`, `raise TypeError`
=> Add stream argument validation

.github/workflows/conda-package.yml
Works around known issues with lief in the latest versions of conda-build
=> [MAINT] Pin conda-build to most recent working version

dpctl/_init_helper.py, dpctl/tensor/_numpy_helper.py, dpctl/tensor/_types.pxi, dpctl/tests/test_utils.py, dpctl/utils/_intel_device_info.py
Apply `# pragma: no cover` to instruct coverall to omit certain branches, certain lines from coverage stats.
This change, which only adds comments, should result in a great jump in coverage percentage.
=> Improve coverage stats

docs/doc_sources/contributor_guides/building.rst
This PR adds to the documentation that versioneer is a build requirement for dpctl.
It is listed in pyproject.toml, but not referenced in docs.
=> Add versioneer as build requirement in documentation

dpctl/_init_helper.py
This PR modified initialization of `dpctl` to set subprocess to not use FORK, but use SPAWN to launch subprocesses on Linux.
This is a tentative fix to allows `oneapi-gdb` to debug kernels submitted by Python applications.
=> Set subprocess to no use fork

dpctl/tensor/libtensor/include/utils/offset_utils.hpp
The failure was caused by TwoOffsets_FixedDimStridedIndexer not being device copyable, consequence of not being trivially copyable, consequence of using const class members contrary to C++ coding guidelines.
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members.html
This change adheres to the guidelines by removing const qualifier in class members.
This change also avoids unnecessary copy in constructors of fixed-dim-strided-indexers that take container arguments by values.
=> Fix build of dpctl with sycl nightly from 2025-01-18

dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp, dpctl/tensor/libtensor/include/kernels/clip.hpp, dpctl/tensor/libtensor/include/kernels/constructors.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_detail.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/common_inplace.hpp, dpctl/tensor/libtensor/include/utils/offset_utils.hpp
This PR factors out inline submit to populate padded vector in specializations for binary operations on matrix and a vector.
Doing so allows to generate fewer of such kernels, resulting in the binary size decrease.
Before:
```
(dev_dpctl) opavlyk@mtl-world:~/repos/dpctl$ ls -l dpctl/tensor/_tensor_elementwise_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 opavlyk opavlyk 38659896 Jan 19 20:58 dpctl/tensor/_tensor_elementwise_impl.cpython-312-x86_64-linux-gnu.so
```
After:
```
(dev_dpctl) opavlyk@mtl-world:~/repos/dpctl$ ls -l dpctl/tensor/_tensor_elementwise_impl.cpython-312-x86_64-linux-gnu.so
-rw-r--r-- 1 opavlyk opavlyk 37176600 Jan 21 06:36 dpctl/tensor/_tensor_elementwise_impl.cpython-312-x86_64-linux-gnu.so
```
Also this PR adds `static_assert` in `offset_utils.hpp` to verify …
=> Reduce elementwise extension size

dpctl/tensor/_array_api.py, dpctl/tests/test_tensor_array_api_inspection.py
This PR proposes changing the handling of the `device` keyword in the array API inspection utilities to:
- raise a more helpful exception for unexpected inputs
- work correctly with filter strings and SyclQueues
Also fixes the `dtypes` utility returning `complex128` in its output when the provided device does not support double precision types.
Resolves #1978 , resolves #1977
=> Fix array API inspection behavior with `device` keyword

.github/workflows/conda-package.yml
This PR proposes unpinning conda-build in the conda-package workflow, as well as updating the workflow to account for conda-build (after 25.1.0) moving to producing .conda files instead of tarballs.
The change to .conda files is motivated by improvements to package compression, which bring dpctl from ~24 MB to ~13.5 MB, about a 40% decrease in size.
=> [MAINT] Unpin conda-build

dpctl/tests/test_usm_ndarray_dlpack.py
The test `test_dlpack_device` attempted to query a device using DLPack device ID from the list of root devices created by `all_root_devices` fixture in `test_usm_ndarray_dlpack`.
This logic is incorrect, as `all_root_devices` caches only the first two root devices per platform. As the DLPack device ID is based on the ordinal ID of the device as it is canonically presented in `get_devices`, this could fail if a given platform had more than 2 associated devices (in this case, for a machine with 2 PVC. Each has 2 stacks, and therefore, 4 `level_zero` and `opencl:gpu` devices).
=> Fix incorrect tests in `test_usm_ndarray_dlpack`

dpctl/tensor/libtensor/include/kernels/elementwise_functions/sycl_complex.hpp
This PR adds a license header which was missing from the `sycl_complex.hpp` header file.
=> [MAINT] Add missing license header to `elementwise_functions/sycl_complex.hpp`

dpctl/_sycl_queue.pyx, dpctl/tests/test_sycl_queue_memcpy.py
Using typed memoryviews restricts queue `memcpy` to buffers with a single dimension only.
With this change, multi-dimensional buffers with contiguous layout can now be `memcpy`'d.
=> Copy from/to multidimensional buffers

libsyclinterface/tests/test_sycl_device_interface.cpp
Compilation of `"libsyclinterface/tests/test_sycl_device_interface.cpp"` by Clang version 20.0 fails with "error: ordered comparison between pointer and zero".
=> Correct mistake in the test that causes compilation error

libsyclinterface/tests/test_sycl_queue_submit_local_accessor_arg.cpp
Clean-up of `"libsyclinterface/tests/test_sycl_queue_submit_local_accessor_arg.cpp"` file:
1. Save filename of the test SPV into a variable and reuse it
2. Add `static_assert` that `SIZE` is divisible by 10
3. Replaced hard-coded expected value with one that depends on value of `SIZE`
4. Fixed typos in the source code to generate SPV files 
a. Use `#include <sycl/sycl.hpp>` instead of `#include <CL/sycl.hpp>` to reduce deprecation warning
b. Add missing instantiation for test for `uint16_t`
---
=> Clean up of test_sycl_queue_submit_local_accessor_arg.cpp

conda-recipe/meta.yaml
For the 0.19.x release, pin build time DPC++ to 2025.1.0
=> Pin build time version of DPC++ compiler to 2025.1.0 for 0.19.x release

.github/CODEOWNERS, conda-recipe/meta.yaml
Update to CODEOWNERS file and conda-recipe/meta.yaml
=> Update CODEOWNERS and recipe maintainers

.github/workflows/conda-package.yml
Conda workflow has been failing due to issues with LIEF, which jumped to 0.16.1 in CI. Bring conda-build version down to 25.1.1 while waiting for stability to improve.
=> [MAINT] Do not use conda-build 25.1.2 to fix Conda package workflow

CHANGELOG.md, dpctl/tensor/libtensor/source/accumulators.cpp, dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp
This PR backports gh-2002 to the maintenance/0.19.x branch and adds the change to the changelog
=> Backport gh-2002

pyproject.toml
Currently python 3.12 is missing in a list of programming languages in the metadata wile packages with python 3.12 are available of PyPi and conda channel.
This PR proposes to include python 3.12 to the metadata.
Note it does not consider python 3.13, because the packages for python 3.13 will not be included in the upcoming release.
=> Add python 3.12 to metadata

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
C-API functions which make a `usm_ndarray` from a pointer (`UsmNDArray_MakeSimpleFromPtr` and `UsmNDArray_MakeFromPtr`) take an integral `typenum` argument
If this argument is invalid, the `itemsize` declared in the functions would be returned from `type_bytesize` as -1 and could potentially overflow
=> Fix possible `itemsize` overflows in `usm_ndarray` from-pointer constructors

dpctl/tensor/_copy_utils.py
This PR updates docstrings of `from_numpy` and `astype` functions to remove a duplicating `a` in description of `device` keyword.
=> Fix a typo in documentation

CHANGELOG.md, pyproject.toml
Backport gh-2005 to the maintenance/0.19.x branch and add to changelog
=> Backport gh-2005

CHANGELOG.md, dpctl/tensor/_copy_utils.py
Backport changes from gh-2006 to the maintenance/0.19.x branch and add to the changelog
=> Backport gh-2006

dpctl/tensor/libtensor/include/kernels/accumulators.hpp, dpctl/tensor/libtensor/source/accumulators/cumulative_prod.cpp, dpctl/tensor/libtensor/source/accumulators/cumulative_sum.cpp, dpctl/tests/test_tensor_accumulation.py
This PR resolves gh-2017 by introducing missing dedicated kernels for `bool->bool` in the type matrix of `cumulative_sum` and `cumulative_prod`.
Also slips in the addition of `int8->int8`
=> Fix incorrect results from `cumulative_sum` and `cumulative_prod` with `dtype=bool`

.github/workflows/conda-package.yml
This PR unpins conda-build, which was pinned in https://github.com/IntelPython/dpctl/pull/2001 due to issues with a new version of lief
=> [MAINT] Unpin conda-build in Conda package workflow

dpctl/_backend.pxd, dpctl/_sycl_device_factory.pyx, dpctl/_sycl_platform.pyx, dpctl/tests/test_sycl_device_factory.py, dpctl/tests/test_sycl_platform.py, libsyclinterface/helper/source/dpctl_utils_helper.cpp, libsyclinterface/include/syclinterface/dpctl_sycl_device_manager.h, libsyclinterface/include/syclinterface/dpctl_sycl_platform_interface.h, libsyclinterface/source/dpctl_sycl_platform_interface.cpp, libsyclinterface/tests/test_sycl_device_selector_interface.cpp, libsyclinterface/tests/test_sycl_platform_interface.cpp
This PR proposes implementing the `get_devices` method to `dpctl.SyclPlatform` class as per SYCL 2020 spec, which specifies including a `device_type` filter.
Cleans up some remaining references to host devices, missed in https://github.com/IntelPython/dpctl/pull/1028
Closes #509
=> Add `get_devices` method to `dpctl.SyclPlatform` class

CHANGELOG.md, dpctl/tensor/_indexing_functions.py, dpctl/tests/test_usm_ndarray_indexing.py
This PR proposes the addition of the `out` keyword in `dpt.take`, supported by most other libraries (NumPy, Torch, etc.)
=> Add `out` keyword to `dpt.take`

docs/doc_sources/api_reference/dpctl/constants.rst, docs/doc_sources/api_reference/dpctl/index.rst, docs/doc_sources/api_reference/dpctl/tensor.constants.rst, dpctl/enum_types.py
This PR adds generated documentation for `dpctl` enums (i.e., `device_type`, `backend_type`, etc.)
=> [Docs] Add documentation for dpctl enums

.github/workflows/conda-package.yml
After the release of 2025.1.0 compiler, Windows CI broke when building with 2025.0.4 and testing on 2025.1.0
This PR works around the problem by installing the 2025.1.0 compiler in the environment when building
=> [MAINT] Fix Windows CI with 2025.1.0 compiler

CHANGELOG.md, dpctl/tensor/_elementwise_funcs.py, dpctl/tensor/libtensor/include/kernels/elementwise_functions/ceil.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/floor.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/trunc.hpp, dpctl/tests/elementwise/test_floor_ceil_trunc.py
In this PR, support for Boolean dtype is added to `dpctl.tensor.ceil`, `dpctl.tensor.floor`, and `dpctl.tensor.trunc`.
resolves #2030
=> add support for Boolean dtypes for `dpctl.tensor.ceil`, `dpctl.tensor.floor`, and `dpctl.tensor.trunc`

dpctl/_sycl_platform.pyx
This PR removes an unnecessary space from `dpctl.SyclPlatform.__repr__`, fixing spacing in the string representation of `dpctl.SyclPlatform`
=> Fix spacing in string representation of `dpctl.SyclPlatform`

CHANGELOG.md, docs/doc_sources/user_guides/dlpack.rst, libsyclinterface/source/dpctl_sycl_platform_interface.cpp
This PR follows a deprecation warning raised by DPC++ 2025.2 compiler and updates `DPCTLPlatform_GetDefaultContext` implementation to replace deprecated API call of `ext_oneapi_get_default_context()` (see [llvm#17135](https://github.com/intel/llvm/pull/17135)) with `khr_get_default_context()` one (added in [llvm#15645](https://github.com/intel/llvm/pull/15645)).
=> Use `khr_default_context()` per DPC++ 2025.2 compiler deprecation warning

.github/workflows/generate-docs.yml
Doc builds were failing in CI, citing setuptools version >=70.1 being required
Add setuptools">=70.1" to resolve
=> [MAINT] Fix building docs in CI

dpctl/tensor/_elementwise_funcs.py
This PR updates docstrings of elementwise functions to add expected dtype of input arrays where missing, to align the dtypes with implementation and to fix some typos which were identified.
=> Updated expected dtypes of input arrays in docstrings of elementwise functions

dpctl/tensor/_copy_utils.py, dpctl/tensor/_slicing.pxi, dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_indexing.py
The array API specification now requires advanced integer indexing (i.e., with arrays) to promote Python integer scalars to arrays when mixed with integer arrays.
This PR implements this behavior, promoting any integer indices that occur in a sequence with array indices of dimension 1 or greater.
=> Update integer advanced indexing for array API 2024.12 spec

.github/workflows/conda-package.yml
This PR sets `ARRAY_API_TESTS_VERSION` to 2024.12 when running array API conformity job in CI
=> Run array API tests using 2024.12 version of spec

dpctl/tensor/_array_api.py, dpctl/tests/test_usm_ndarray_ctor.py
This PR updates `__array_api_version__` to `2024.12` as the new spec version is now supported, with advanced indexing update now in place
=> Update array API spec version supported to 2024.12

dpctl/tensor/_elementwise_funcs.py
This PR continues work done in #2041 and aligns expected data type of `real` function with the implementation.
=> Update expected data type of input array in `real` function

.gitignore, benchmarks/README.md, benchmarks/asv.conf.json, benchmarks/benchmarks/benchmark_utils.py, benchmarks/benchmarks/binary.py, benchmarks/benchmarks/ef_bench_add.py
This PR introduces ASV benchmarks to the repo.
You can find links to ASV's documentation in the added README
Once this is merged, the infra team can start finalizing the work to add these executions to the CI, allowing instant feedback on benchmarks and performance regressions during development.
The benchmarks were tested pretty exhaustively, but please let me know if I need to tweak any of the parameters or add additional benchmark cases. They work for both CPU and GPU SYCL devices as well.
=> task: benchmarking with asv

.github/workflows/conda-package.yml
Currently a push on `master` branch in the forked repo starts the `Conda package` workflow with enabled uploading of the resulting dpctl conda package to public channel (which is not supported and has to be prohibited). Here is a [log](https://github.com/antonwolfy/dpctl/actions/runs/14617157851/job/41010880625) for reference with the failed step.
This PR proposes to explicitly disable `upload` job for any repo except origin `IntelPython/dpctl`.
=> Disable upload job from forked repo

dpctl/tensor/_copy_utils.py, dpctl/tensor/_ctors.py, dpctl/tests/elementwise/test_type_utils.py, dpctl/tests/test_tensor_copy_utils.py
This PR fixes a bug in `asarray` where `order="K"` keyword could fail to produce an appropriate array in some edge cases, such as the permutation of a contiguous array.
`asarray(x)` for some NumPy array `x` now uses a consistent implementation for `order="K"` as other functions supporting `order`
Closes #2055
=> Resolve gh-2055

.github/workflows/run-tests-from-dppy-bits.yaml
This PR proposes to enable nightly tests run to be scheduled only for main repo, excluding fork ones.
=> Disable scheduled workflow to be run in fork repos

docs/doc_sources/beginners_guides/tensor_intro.rst
This PR updates one of the [example](https://intelpython.github.io/dpctl/latest/beginners_guides/tensor_intro.html#id3) for migrating arrays in beginners guide to fix a typo there.
=> Fix a typo in beginners guide

.github/workflows/generate-coverage.yaml, .github/workflows/os-llvm-sycl-build.yml
`setuptools` update to 80.0.0 has been causing a failure in the test suite
Pin `setuptools` for now while investigating
=> [MAINT] Pin `setuptools` to <80 in CI

dpctl/tensor/libtensor/include/kernels/elementwise_functions/imag.hpp, dpctl/tensor/libtensor/include/kernels/elementwise_functions/real.hpp
This PR proposes to add a `constant_value` of 0 to be used by the implementation of the element-wise kernel when the input is a real-valued data type
Slips in change to use `is_complex_v` in `imag` and `real`
=> Use constant value in `imag` implementation for real-valued data types

.github/workflows/conda-package.yml, .github/workflows/run-tests-from-dppy-bits.yaml
The location of `cl.cfg` file created by installing `intel-opencl-rt` conda package has been changed few releases back from `%CONDA_PREFIX%\Library\lib\cl.cfg` to `%CONDA_PREFIX%\Library\bin\cl.cfg`.
The file is still created at `Library\lib\cl.cfg` path by `intel-opencl-rt-post-link.bat` script but with empty content.
The PR updates public CI to rely on correct path towards `cl.cfg` configuration file.
The issue with `intel-opencl-rt-post-link.bat` script has to be updated by a separate PR in the compiler repo.
=> Correct a path to `cl.cfg` file

dpctl/memory/_memory.pyx
This PR proposes a very small fix to a typo in a docstring in `_memory.pyx`
=> Fix typo in `_memory.pyx` docstring

dpctl/tensor/_array_api.py, dpctl/tests/test_tensor_array_api_inspection.py
`tensor.usm_ndarray` can support potentially arbitrary dimensions
Changes will need to be made where NumPy arrays are created from `usm_ndarray` (printing, dlpack with `kDLCPU`, `asnumpy`/`from_numpy`)
=> Change `"max dimensions"` to `None` in array API capabilities

README.md
The readme provides a link to intel conda, which is deprecated and shows no packages to download. Since this package is not on conda-forge and the intel channel links do not have a browsable URL like anaconda ones, this PR removes the link altogether.
=> DOC: Remove outdated conda link

docs/doc_sources/urls.json, dpctl/_backend.pxd, dpctl/_sycl_device.pyx, dpctl/tests/test_sycl_device.py, libsyclinterface/helper/include/dpctl_utils_helper.h, libsyclinterface/helper/source/dpctl_utils_helper.cpp, libsyclinterface/include/syclinterface/dpctl_sycl_device_interface.h, libsyclinterface/include/syclinterface/dpctl_sycl_enum_types.h, libsyclinterface/source/dpctl_sycl_device_interface.cpp, libsyclinterface/source/dpctl_sycl_kernel_bundle_interface.cpp, libsyclinterface/tests/CMakeLists.txt, libsyclinterface/tests/test_helper.cpp, libsyclinterface/tests/test_sycl_peer_access.cpp
This PR adds full support for the [DPC++ `sycl_ext_oneapi_peer_access` extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_peer_access.asciidoc)
This adds a Python interface to calls that check if a `dpctl.SyclDevice` can enable peer access to another `dpctl.SyclDevice` and, if so, to enable or disable it.
=> Support peer access DPC++ extension

dpctl/_sycl_device.pyx
This PR follows up on #2077 by adjusting the docstring for the `can_access_peer` method
=> Change docstring in `can_access_peer` method

pyproject.toml
There is invalid link to `CHANGELOG.md` on PyPi [page](https://pypi.org/project/dpctl/).
This PR update the link with proper path to the file in the dpctl repo.
=> Correct a link to `CHANGELOG.md` in package metadata

CHANGELOG.md
This PR populates changelog for 0.20.0
=> Add 0.20.0 changes to CHANGELOG.md

dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp
The reshape and roll kernels have a special handling for 1-element input array, where `exec_q.copy()` is used.
But it is still possible that the array data depends on submitted events even in that case with only 1-element.
Thus this PR is fixing the issue with unsafe copying of 1-element input array.
The issue was initially detected in dpnp tests on ARL BMG Linux machine in scope of internal testing.
=> Add passing dependent events to `copy` calls

dpctl/tensor/_ctors.py, dpctl/tests/test_tensor_asarray.py
Closes gh-1046 
This PR resolves `dpt.asarray(x, device=dev)` failing for some array `x` with dtype not supported by device `dev`
=> Resolve gh-1046

CHANGELOG.md, dpctl/tensor/libtensor/source/copy_for_reshape.cpp, dpctl/tensor/libtensor/source/copy_for_roll.cpp
This PR backports the fix in gh-2095 to maintenance/0.20.x and adds 0.20.1 to the changelog, in preparation for an out of cycle release
=> Backport gh-2095

CHANGELOG.md
This PR backports the updated changelog for 0.20.1 to master
=> Add 0.20.1 to the changelog

dpctl/tensor/libtensor/include/kernels/elementwise_functions/angle.hpp
This PR removes duplicate 'static' declaration specifier introduced in #2094.
=> Remove duplicate 'static' declaration specifier

conda-recipe/meta.yaml, pyproject.toml
This PR backports gh-2112 to maintenance/0.20.x to fix potential test failures due to Cython version when dpctl is used with Python 3.13
=> Backport gh-2112

pyproject.toml
This PR backports gh-2110 to the maintenance/0.20.x branch, adding Python 3.13 to the dpctl metadata
=> Backport gh-2110

dpctl/tensor/_copy_utils.py
This PR adds a fast path to copy the USM data to `numpy.ndarray`.
In case when the USM data has the zero size, there is no need to synchronize the data and to perform the copy. It will be enough to call `numpy.ndarray` constructor with appropriate `shape` and `dtype` keywords.
=> Add a fast path to copy to numpy.ndarray

dpctl/tensor/libtensor/source/sorting/py_argsort_common.hpp, dpctl/tensor/libtensor/source/sorting/py_sort_common.hpp, dpctl/tests/test_usm_ndarray_sorting.py
Some sorting algorithms used (in particular `radix_sort`) assert that elements to be sorted must be greater than 1, and this can cause failures in debug builds, like coverage
This PR proposes a fix: copy in sort and memset to 0 in argsort when `sort_nelems` is 1
=> Fix sort for size 1 axes

dpctl/tensor/_copy_utils.py, dpctl/tests/test_usm_ndarray_ctor.py
This PR proposes a fix for gh-2121, which is caused by underlying memory of a boolean array not necessarily representing only 0s and 1s, in particular when it is a view from a non-boolean array
This PR adds a path to astype that guarantees `astype(a, "?")` will give an output array of only 0 and 1
=> Fix for gh-2121

dpctl/tensor/_usmarray.pyx, dpctl/tests/test_usm_ndarray_ctor.py
This PR allows type casting zero-sized `usm_ndarray` to any dtype (including larger ones).
=> Allow type casting of zero-sized array to any dtype

dpctl/tensor/_usmarray.pyx
This PR replaces `DLDeviceType` as inline literal text with a link to the page with the enum's description.
=> Set a link to DLDeviceType enum from `__dlpack_device__` docstring

dpctl/tensor/_copy_utils.py, dpctl/tensor/_slicing.pxi, dpctl/tests/test_usm_ndarray_indexing.py
This PR proposes allowing NumPy arrays when indexing `usm_ndarray`
This can be useful where attempting to use `usm_ndarray` in a library which generates indices with NumPy, and which expects to only handle devices implicitly through tensor operations (i.e., a library which can take an arbitrary tensor input, but generates indices with `numpy.random` and expects these indices to work on the input tensor)
Both boolean and integer advanced indices can accept NumPy arrays with these changes 
Closes #2053
=> Accept NumPy arrays in advanced indexing

dpctl/__init__.py, dpctl/_init_helper.py
This PR refactors some logic in dpctl managing the DLL search path, also adding the dpctl `__init__.py` directory to the PATH, matching the logic in dpnp, in an attempt to fix dpctl being imported from virtual environments failing to see devices or find SYCL dlls
=> Fix logic managing dll search path and path when initializing dpctl

dpctl/memory/_opaque_smart_ptr.hpp, dpctl/tensor/libtensor/source/sorting/rich_comparisons.hpp
This PR proposes removing two anonymous namespaces from headers
This will reduce possible binary size bloating, and prevents potential undefined behavior
=> Remove remaining anonymous namespaces from headers

docs/doc_sources/user_guides/environment_variables.rst, dpctl/_sycl_device_factory.pyx
This PR adds some needed environment variable documentation to the git pages.
=> task: add more env var documentation

dpctl/tests/setup_cython_api.py
Add project root folder to `include_dirs` in the `"setup_cython_api.py"` so that Cython can find `dpctl/__init__.pxd`
This resolves gh-2146 for me locally with Cython 3.1.3
=> Add project root folder to include_dirs in _cython_api setup script

conda-recipe/bld.bat, conda-recipe/run_test.bat, libsyclinterface/dbg_build.bat
This PR proposes using `if %ERRORLEVEL% neq 0 exit 1` in bld.bat wheel copying, which is more general than `if errorlevel 1 exit 1`
A similar change was suggested when adding the recipe to conda-forge
=> [MAINT] Make error checks in `.bat` files more general

docs/doc_sources/api_reference/dpctl/tensor.set_functions.rst, dpctl/tensor/CMakeLists.txt, dpctl/tensor/__init__.py, dpctl/tensor/_clip.py, dpctl/tensor/_elementwise_common.py, dpctl/tensor/_scalar_utils.py, dpctl/tensor/_search_functions.py, dpctl/tensor/_set_functions.py, dpctl/tensor/_utility_functions.py, dpctl/tensor/libtensor/include/kernels/sorting/isin.hpp, dpctl/tensor/libtensor/include/utils/rich_comparisons.hpp, dpctl/tensor/libtensor/source/sorting/isin.cpp, dpctl/tensor/libtensor/source/sorting/isin.hpp, dpctl/tensor/libtensor/source/sorting/merge_argsort.cpp, dpctl/tensor/libtensor/source/sorting/merge_sort.cpp, dpctl/tensor/libtensor/source/sorting/searchsorted.cpp, dpctl/tensor/libtensor/source/sorting/topk.cpp, dpctl/tensor/libtensor/source/tensor_sorting.cpp, dpctl/tests/test_tensor_isin.py
This PR proposes an implementation for `isin`, a function likely coming to a future array API specification, which leverages a similar kernel to the implementation of `searchsorted`
This implementation uses the `searchsorted` kernel to check if the value has a position in the array. If that position is the number of elements in the array, it is not a member. Otherwise, if `arr[pos] == val` for some array `arr` being searched for value `val`, then `val` is a member.
=> Implement `tensor.isin`

CMakeLists.txt, dpctl/CMakeLists.txt
previously part of defunct PR #2157
the message
```
Using compatibility mode for Python, set PYBIND11_FINDPYTHON to NEW/OLD to silence this message
```
is silenced when `find_package(Python REQUIRED COMPONENTS Development.Module)` is added to CMake before fetching pybind11, as `Python_FOUND` will be set
=> Resolve pybind11 CMake message
