IntelPython/dpctl

.gitignore
backends/source/dppl_opencl_interface.c

initialize err variable.

---

conda-recipe/meta.yaml

License update for beta release

---

dpctl/_memory.pyx

Memory acquires _pointer property

---

dpctl/ocldrv.py

References to the ffi and lib modules are now stored inside Runtime. By doing that we ensure that the objects stay around till Runtime is alive. Without the fix when running unit tests I was encountering a crash stating NoneType has no attribute `_runtime`.
Fixes #62

Fixes the implementation of the oclrv.Runtime singleton.

---

dpctl/ocldrv.py

Fix spellings.

---

dpctl/memory/__init__.pxd

This change is needed to make examples work.

fixed dpct/memory/__init__.pxd

---

docs/README.md

Fix small issue with docs README

Update docs generation instruction

---

conda-recipe/build.sh

- Use manylinux1 for Python 3.6
- Use manylinux2014 for Python > 3.6

Update linux wheel build tag

---

dpctl-capi/include/dpctl_sycl_enum_types.h

- Adds a "ALL" entry to DPCTLSyclBackendType and DPCTLSyclDeviceType.
- Changes the value of the "Unknown" entry to 0.

Small changes to DPCTL enums.

---

dpctl-capi/include/dpctl_sycl_context_interface.h
dpctl-capi/source/dpctl_sycl_context_interface.cpp
dpctl-capi/tests/test_sycl_context_interface.cpp

Adds C API wrappers for SYCL context constructors and also adds missing C API tests. The Python API is not implemented here.

Add SYCL context constructor and test cases.

---

dpctl-capi/tests/test_sycl_device_interface.cpp

Remove repeated code from device_interface gtest.

Remove code duplication.

---

dpctl/_sycl_queue.pxd

Atomic change from #334 
Is non-controversial.

exported default_async_error_handler

---

examples/python/subdevices.py

Also made sure that `__version__` and `get_include` is in `__all__`, so that
their docstrings make it into the rendered autogenerated documentation.

Flake8 fixes

---

examples/cython/sycl_buffer/use_sycl_buffer.cpp
examples/cython/sycl_buffer/use_sycl_buffer.h
examples/cython/sycl_direct_linkage/sycl_function.cpp
examples/cython/sycl_direct_linkage/sycl_function.hpp
examples/cython/usm_memory/sycl_blackscholes.cpp
examples/cython/usm_memory/sycl_blackscholes.hpp

Fix formatting issues in C++ files under Cython examples.

Apply clang-format to C++ files in cython examples.

---

.clang-format

Add another fix for missing new-line at EOF.

Add an new line at the end of file.

---

.pre-commit-config.yaml

Use clang-format with -i

---

dpctl-capi/helper/source/dpctl_utils_helper.cpp

Early exit optimization to close #431

---

docs/docfiles/dpctl_pyapi.rst
dpctl/_sycl_context.pyx
dpctl/_sycl_device_factory.pyx

Added docstrings to `get_devices` and `get_num_devices`.

Add missing doc strings.

---

docs/docfiles/user_guides/QuickStart.rst

Few edits to the quick start guide in our documentation site.

Minor edits to the quick start guide.

---

.github/workflows/generate-docs.yml
dpctl-capi/cmake/modules/FindLLVMCov.cmake
dpctl-capi/cmake/modules/FindLLVMProfdata.cmake
scripts/build_for_develop.sh
setup.py

Housekeeping fixes at various places.

Spring cleaning

---

dpctl-capi/source/dpctl_sycl_context_interface.cpp
dpctl-capi/source/dpctl_sycl_device_interface.cpp
dpctl-capi/source/dpctl_sycl_device_manager.cpp
dpctl-capi/source/dpctl_sycl_platform_interface.cpp
dpctl-capi/source/dpctl_sycl_queue_interface.cpp
dpctl-capi/source/dpctl_vector_templ.cpp

Changes to C++ to free resources on errors.

Addressed klocwork_dpctl_issues

---

docs/docfiles/dpctl_pyapi/SyclContext.rst
docs/docfiles/dpctl_pyapi/SyclDevice.rst
docs/docfiles/dpctl_pyapi/SyclEvent.rst
docs/docfiles/dpctl_pyapi/SyclPlatform.rst
docs/docfiles/dpctl_pyapi/SyclQueue.rst
dpctl/_sycl_context.pyx
dpctl/_sycl_device.pyx
dpctl/_sycl_platform.pyx
dpctl/_sycl_queue.pyx

WIP changes to Python API docs.

Updates to API docs prior to 0.8.0 release.

---

dpctl-capi/source/dpctl_sycl_event_interface.cpp
dpctl-capi/tests/test_sycl_event_interface.cpp

This PR adds tests for the DPCTLEvent_Wait function.

Add tests for DPCTLEvent_Wait

---

.github/workflows/conda-package.yml

Run tests on Gen9

---

dpctl-capi/include/dpctl_sycl_enum_types.h
dpctl-capi/source/dpctl_sycl_queue_interface.cpp
dpctl-capi/tests/test_sycl_queue_interface.cpp

Fixes #494 .
Added logic to verify that all bits of property integer were
recognized and used.
Added test to verify handling of property bits.

Addressed concern regarding #494

---

README.md

Added part of oneAPI badge

---

CHANGELOG.md

Compiled change log since dpctl 0.8.0 release

Update CHANGELOG (WIP)

---

.github/workflows/conda-package.yml

Temporary off self-hosted runner

---

dpctl/tests/test_sycl_event.py

Write test to call `__pyx_capi__` exposed `get_event_ref` function using ctypes.

Added a test to exercise API exported function (get_event_ref).

---

dpctl/_sycl_event.pyx
dpctl/tests/test_sycl_event.py

This was gleaned by analyzing coverage (figuring out why that code was never called).
Added tests to improve coverage.

profiling_info_submit was not property

---

dpctl-capi/cmake/modules/FindIntelSycl.cmake

Suppress errant CMake log.

---

.github/workflows/conda-package.yml

Fix public CI 

---

CHANGELOG.md

Update changelog for 0.11.0 release

Update changelog for 0.11.0 release

---

docs/docfiles/user_guides/QuickStart.rst

Added extra dash for extra-index-url
@samaid

Fixed pip install instruction

---

.pre-commit-config.yaml
README.md

Updated the tools used in our pre-commit hooks. Also added a badge for pre-commit to our README.

Update versions for tools used in pre-commit checks. Add a badge.

---

.github/workflows/conda-package.yml

[Public CI] Return condition for tag upload package

---

CHANGELOG.md
dpctl-capi/helper/include/dpctl_string_utils.hpp

Release 0.11.3

---

dpctl/utils/__init__.py

Added license header and docstring to dpctl.utils.__init__

---

CHANGELOG.md
dpctl/tests/test_sycl_queue_manager.py

Release 0.11.4

---

dpctl/_sycl_context.pyx
dpctl/memory/__init__.py
dpctl/program/__init__.py
dpctl/tensor/__init__.py
dpctl/tensor/_copy_utils.py
dpctl/tensor/_ctors.py
dpctl/tensor/_device.py
dpctl/tensor/_usmarray.pyx
dpctl/utils/__init__.py

I am opening the PR against the `generate_rst` branch so that documentation pages get rendered with the new infrastructure.

Collection of fixes and improvements to dpctl docstrings

---

dpctl/_sycl_context.pyx
dpctl/memory/__init__.py
dpctl/program/__init__.py
dpctl/tensor/__init__.py
dpctl/tensor/_copy_utils.py
dpctl/tensor/_ctors.py
dpctl/tensor/_device.py
dpctl/tensor/_usmarray.pyx
dpctl/utils/__init__.py

This PR contains changes from  #710 but targets to master, rather than generate_rst.

Collection of fixes and improvements to dpctl docstrings (#710)

---

dpctl/enum_types.py

Adds docstring to event_status_type enum

---

.github/workflows/os-llvm-sycl-build.yml

Use updated OCL drivers: 12.13.11.0.23_rel, and updated version of TBB 2021.5.0

Update workflow of building with OS intel/llvm

---

.github/workflows/pre-commit.yml

[MAINT] Use pre-commit/action@v2.0.3

---

examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp

Simplified onemkl_gemv example to use the C++ class instead of working with `pybind11::object` and using C-API.

Simplified oneMKL example by using usm_ndarray class for pybind11

---

dpctl/tensor/_stride_utils.pxi
dpctl/tensor/_usmarray.pyx
dpctl/tests/test_usm_ndarray_ctor.py

This PR modifies `usm_ndarray.T` property behavior per array API spec, and introduces `usm_ndarray.mT` property.
Tests added.

Add .mT, change .T properties of dpctl.tensor.usm_ndarray 

---

.github/workflows/os-llvm-sycl-build.yml

Updating to stay in sync with intel/llvm

updated CPU driver version

---

.pre-commit-config.yaml
dpctl/tests/test_sycl_event.py
setup.py

Picking up some changes from master to make sources of `release0.12` buildable in CI.

Fix ci for 0.12

---

CHANGELOG.md

Populates change-log generated by github and arranged it into Added/Changed sub-sections

populated change-log for 0.12.0

---

libsyclinterface/cmake/modules/FindIntelSycl.cmake

The logic to compare package versions inside the CMake module `FindIntelSycl.cmake` is incorrect. We are using lexicographic string comparison that can lead to an version check of `1.7.9 > 1.7.15` evaluating to `True`.  The PR fixes the issues by introducing a correct way to compare versions.

Improves the logic to implement IntelSycl version requirement.

---

.github/workflows/conda-package.yml
.github/workflows/generate-coverage.yaml
.github/workflows/os-llvm-sycl-build.yml

Updated from using actions/cache@v2 to actions/cache@v3 per their [example workflow](https://github.com/actions/cache#example-workflow).

Use actions/cache@v3

---

CHANGELOG.md
dpctl/tensor/__init__.py
dpctl/tensor/_manipulation_functions.py
dpctl/tests/test_usm_ndarray_manipulation.py

concat() function concatenates several arrays along one of axis and follows [array API spec](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.concat.html).

Added dpctl.tensor.concat feature and tests

---

CHANGELOG.md

This change updated CHANGELOG.md to state released version and the date of release

Updated changelog in preparation for release of 0.13.0

---

conda-recipe/bld.bat

Adjust script setting hint dir variable to work with sycl bundles using different clang versions

conda-recipe/bld.bat adjusted to work with different versions of clang used by DPC++

---

dpctl/tensor/_reshape.py

Added support for uppercase and lowercase letters for order argument to reshape() function.

Fixed issue #890 in reshape() function.

---

dpctl/_device_selection.py
dpctl/_sycl_device.pyx
dpctl/_sycl_timer.py
dpctl/program/_program.pyx
dpctl/tensor/_copy_utils.py
dpctl/tensor/_ctors.py
dpctl/tensor/_device.py
dpctl/tensor/_manipulation_functions.py
dpctl/tensor/_reshape.py
dpctl/tensor/_usmarray.pyx
dpctl/tests/test_sycl_device.py
dpctl/utils/_onetrace_context.py
setup.py

Ran `pylint` on `dpctl` sources and addressed generated warnings

Linter informed cleanup

---

.github/workflows/conda-package.yml

Adding Python 3.10 to the matrix for Windows platform for `dpctl`.

Build dpctl on Windows for Python 3.10 as well

---

.github/workflows/python_style_checks.yml

Tab->space to enable workflow to run. 
The tab was introduced in #1055

Fix for python_style_check workflow

---

README.md

Adds a badge to our gitter chatroom.

Add a badge for our gitter chatroom.

---

dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp

Refactors integer_advanced_indexing.cpp.
- [ X ] Have you provided a meaningful PR description?
- [ X ] Have you tested your changes locally for CPU and GPU devices?
- [ X ] Have you made sure that new changes do not introduce compiler warnings?
- [ X ] If this PR is a work in progress, are you filing the PR as a draft?

Refactored advanced_indexing to 1 host_task

---

dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp

Adds host_task_events as dependency of keep_args_alive event that is returned out Python function.

Take, put host_tasks in keep_args_alive

---

CHANGELOG.md

Populated release notes by going through ``git log --oneline --merges 0.14.0..HEAD | grep "pull request"`.

Added change-log for 0.14.1

---

.github/pull_request_template.md

Added a checkbox reminding to investigate performance impact of changes in PR

PR template: memento perficientur

---

dpctl/tensor/libtensor/include/utils/offset_utils.hpp

- Very useful for implementing binary functions and where

Implements indexer for handling three offsets

---

dpctl/tests/test_usm_ndarray_ctor.py

This pull request adjusts several tests for the Flags class, which should improve coverage.
Previously, the `__getitem__` method, `__setitem__` argument validation, and `fnc` and `forc` properties were untested, and this has been changed.

Adds missing tests for usm_ndarray.flags

---

conda-recipe/bld.bat

Check `%PLATFORM_DIR% exists before manipulating it in `bld.bat`

Check that %PLATFORM_DIR% exists before copying there

---

CHANGELOG.md

Populate change-log for 0.14.3, 0.14.4 and 0.14.5 releases

---

dpctl/apis/include/dpctl4pybind11.hpp

This PR implements `dpctl::tensor::usm_ndarray::get_device()` method.

Implement usm_ndarray::get_device()

---

CMakeLists.txt

Update pybind11 version used to build `dpctl` to the latest version 2.11.1

Bump pybind11 version used

---

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp

Moved logic of submitting different kernels in gemm outside of handler function
This should improve debugging experience, where one can see in the debugger which branch the execution took.
No other logic has been changed.

Decide which kernels to submit outside of handler functions in in gemm

---

CHANGELOG.md

Updated change-log in preparation for 0.15.1 release.

Updated change-log in preparation for 0.15.1 release

---

CHANGELOG.md

This PR only tweaks language in 0.16.0 notes

Start 0.16.0 development cycle

---

.github/workflows/generate-docs.yml

Remove stray unused arguments for pr-comment GH action.

[CICD MNT] Remove unused action arguments

---

dpctl/tensor/libtensor/include/kernels/linalg_functions/gemm.hpp

This PR replaced uses of `_old_nm_` functions with `_new_nm_` functions, and then removed `GemmBatchFunctorThreadNM` and the `_old_nm_` unused functions. 
After this all `_new_` and `_old_` parts in the functions names were deleted.

Removed _gemm_batch_old_nm_impl, got rid of using _new_, _old_ in names

---

LICENSE
docs/conf.in
dpctl/sycl.pxd
dpctl/tests/_c_ext.c
dpctl/tests/_numpy_warnings.py
dpctl/tests/elementwise/test_bitwise_and.py
dpctl/tests/elementwise/test_bitwise_invert.py
dpctl/tests/elementwise/test_bitwise_left_shift.py
dpctl/tests/elementwise/test_bitwise_or.py
dpctl/tests/elementwise/test_bitwise_right_shift.py
dpctl/tests/elementwise/test_bitwise_xor.py
dpctl/tests/elementwise/test_logical_and.py
dpctl/tests/elementwise/test_logical_not.py
dpctl/tests/elementwise/test_logical_or.py
dpctl/tests/elementwise/test_logical_xor.py
examples/c/py_sycl_ls/py_sycl_ls/__init__.py
examples/c/py_sycl_ls/py_sycl_ls/__main__.py
examples/c/py_sycl_ls/setup.py
examples/c/py_sycl_ls/src/py_sycl-ls.c
examples/c/py_sycl_ls/tests/test_sycl_ls.py

Some copyright notices with no longer current year were missed in #1549

Updated overlooked outdated copyright year range

---

README.md
dpctl/tensor/__init__.py

This PR updates doc-string of `dpctl.tensor` module. It also tweaks `README.md`.

Tensor doc string

---

SECURITY.md

Adds a Security policy page to improve OpenSSF score

Adds a Security policy

---

dpctl/tests/test_usm_ndarray_ctor.py
dpctl/tests/test_usm_ndarray_indexing.py

Guided by coverage report, added tests to improve coverage.

Improve coverage usmarray

---

conda-recipe/meta.yaml

Exclude it along with 2024.0.1 and 2024.0.2

Most recent release of dpcpp_win-64=2024.0.3 is still broken

---

dpctl/_sycl_platform.pyx
dpctl/tensor/_dlpack.pxd
dpctl/tensor/_dlpack.pyx
dpctl/tensor/_usmarray.pyx
dpctl/tests/test_usm_ndarray_dlpack.py
libsyclinterface/source/dpctl_sycl_platform_interface.cpp

This PR backports changes from gh-1560 to `maintainenance/0.16.x` branch.

Backport gh-1560 to 0.16.x maintenance branch

---

docs/doc_sources/beginners_guides/index.rst
docs/doc_sources/beginners_guides/installation.rst
docs/doc_sources/beginners_guides/tensor_intro.rst

Minor changes to fix grammar and clarity in the beginners guides section of the documentation.

Review of beginners_guides section

---

docs/doc_sources/contributor_guides/building.rst
docs/doc_sources/contributor_guides/memory_ownership_sycl_interface.rst

InfoDev review of contributor guides.

Review of contributor guides

---

CHANGELOG.md
CMakeLists.txt

Added 0.18 development in CHANGELOG.md

Added stub for 0.18 release cycle

---

.github/workflows/CODEOWNERS

Add `.github/CODEOWNERS` file.

Add codeowner file in .github

---

conda-recipe/meta.yaml

Pin DPC++ compiler used at build time to 2025.0.0

Pin compiler at build time to 2025.0 for 0.18.x release

---

.github/pull_request_template.md
CHANGELOG.md

Adds a stub for the development changelog and adds changelog and documentation to PR chore list

---

CHANGELOG.md
conda-recipe/meta.yaml

Backport of changes from gh-1840 to development branch.

Backport for gh 1840

---

CHANGELOG.md
README.md
docs/doc_sources/beginners_guides/installation.rst

Backport updates to README from gh-1860
----

Add Intel channel for installing wheels

---

pyproject.toml

This PR fixes the incorrect classifier `Programming Language`

Fix the incorrect classifier

---

.github/workflows/run-tests-from-dppy-bits.yaml

Removed bad copy-pasted code in the newly added workflow causing an error.
---

Fixed stray and malformed block of copy-pasted code

---

.github/CODEOWNERS
conda-recipe/meta.yaml

Backport changes from gh-1996 to maintenance/0.19.x which corrects automatic assignment of reviewers for this branch as well

Backport gh-1996

---

.github/workflows/conda-package.yml

This PR fixes the CI (in particular, testing the examples), which has been broken due to a known upstream issue with conda producing corrupt JSON files from `conda search -c $CONDA_CHANNEL $CONDA_PACKAGE --json`

[MAINT] Work-around for conda producing corrupt JSON files

---

CHANGELOG.md
dpctl/tensor/_usmarray.pyx
dpctl/tests/test_usm_ndarray_ctor.py

Backports changes from gh-2003 and adds to the changelog for 0.19.0

Backport gh-2003

---

CHANGELOG.md

This PR cherry-picks commits that update CHANGELOG.md from maintenance/0.19.x to master

Backport maintenance/0.19.x changelog to master

---

dpctl/tensor/_accumulation.py

This PR cleans up `_accumulate_common` function which is used internally by accumulators

Technical debt clean-up in `_accumulation.py`

---

CHANGELOG.md

This PR adds a stub to the changelog for development branch changes made since 0.19.0

[MAINT] Add stub to changelog for dev changes after 0.19.0

---

.github/workflows/conda-package.yml

This PR add a step to cancel previous runs for `Conda package` GitHub workflow.

Add cancelling of previously run jobs for building conda packages

---

.github/workflows/os-llvm-sycl-build.yml

SYCL OS builds have been silently failing because of missing `hwloc`

Install `hwloc` in SYCL OS compiler builds

---

.github/workflows/os-llvm-sycl-build.yml

This PR updates the dependencies used in OS compiler workflow

[MAINT] Update OCL RT in OS compiler workflow

---

.pre-commit-config.yaml

This PR updates `bandit` from 1.7.9 to 1.8.3 in pre-commit config

[MAINT] Update `bandit` version

---

CHANGELOG.md

This PR adds a stub to changelog for dev changes after the 0.20.0 release

[MAINT] Add development stub after 0.20.0 release

---

CHANGELOG.md

This PR backports gh-2090 to add the date of release to the changelog in maintenance/0.20.x

Backport change from gh-2090

---

CHANGELOG.md

This PR adds the release date of 0.20.0 to the changelog

Add release date for `0.20.0`

---

CHANGELOG.md

This PR backports the changes from gh-2092 to maintenance/0.20.x branch

Backport gh-2092

---

CHANGELOG.md

This PR adds a short summary of highlighted features from the 0.20.0 release

Add highlights from 0.20.0 to changelog

---

pyproject.toml

This PR proposes adding Python 3.13 to the pyproject.toml metadata

Add Python 3.13 to metadata

---

CHANGELOG.md

This PR backports the changelog for 0.20.2 to master

Backport gh-2115 to master

---

conda-recipe/bld.bat

This is a 2 year old patch that no longer needs to be here, we're well onto 4.x cmake versions that work fine

chore: delete unused cmake patch logic

---

conda-recipe/meta.yaml

chore: suppress false positive warning for $PATH/DPCTLSyclInterface.dll
