- dppl/__init__.py
- dppl/driverapi.py
- dppl/ocldrv.py
- dppl/tests/test_dump_functions.py
- examples/create_sycl_queues.py
- scripts/build_for_conda.sh
- scripts/build_for_develop.sh
- setup.py
reorganize imports using PyDev's organize imports feature.
> Refactor imports

- conda-recipe/bld.bat
- conda-recipe/meta.yaml
- conda-recipe/run_test.bat
- dppl/driverapi.py
- oneapi_wrapper/CMakeLists.txt
- oneapi_wrapper/include/dppl_oneapi_interface.hpp
- oneapi_wrapper/include/dppl_opencl_interface.h
- oneapi_wrapper/source/dppl_oneapi_interface.cpp
- setup.py
> Windows test

- conda-recipe/run_test.bat
- conda-recipe/run_test.sh
- dppl/tests/__init__.py
- dppl/tests/test_dump_functions.py
I have removed stdout capturing. Now tests are simpler and there are other ways to hide tests output.
> Enable tests

- conda-recipe/bld.bat
- conda-recipe/run_test.bat
When I build conda package on Windows in my local environment it fails on tests.
It happens because oneAPI env activation script (part related to FPGA) does `set ERRORLEVEL=1`.
As mentioned in this [article](https://devblogs.microsoft.com/oldnewthing/20080926-00/?p=20743) in cmd.exe scripts
`IF ERRORLEVEL 1 ...` checks the last exit value but `IF %ERROLEVEL% NEQ 0 ...` checks env variable. The env variable does not relate to last exit status. I think it is error in oneAPI and conda scripts to use env variable instead of exit value.
Current CI works without this modifications but my local env does not work without it.
Also, I have tested it with my last commit on branch beta/2021. When I test in master it crashes on python -c "import dppl". It does not relate to this modifications. Just …
> Correct use ERRORLEVEL in conda scripts for Windows

- backends/source/dppl_sycl_queue_interface.cpp
On Windows static variables construction and destruction cause crashes. I think it is because it should be called in specific order. With static variables the order is undefined.
Now the static variables are constructed at the first access to this variables. The first access happens after all necessary initializations.
Also I think destruction should happen in correct order. As we have no explicit destruction function it is hard to control where static global variables will be deleted. So the variables are changed to pointers and we do not call destruction for them at all. As they should exist to the end of the application it is ok to not destruct them and allow OS to clean its memory.
> Change static variables to static pointers

- dppl/_memory.pyx
- dppl/tests/dppl_tests/test_sycl_usm.py
> Method _usm_type of Memory class should accept sycl_context

- dppl/_memory.pyx
- dppl/tests/dppl_tests/test_sycl_usm.py
Parameter `context` could be `None`, `SyclContext` or `SyclQueue`. 
Name `context` confuses.
> Rename _usm_type parameter from context to syclobj

- dppl/tests/dppl_tests/test_sycl_queue_manager.py
- dppl/tests/dppl_tests/test_sycl_usm.py
Checking for `not dppl.has_sycl_platforms` always returns `False`.
Also this PR adds skipIf() for new tests.
> Fix using dppl.has_sycl_platforms() and dppl.has_gpu_queues() functions in skipIf()

- dpctl/ocldrv.py
Reverts IntelPython/dpctl#39
This change causes crashes in Numba. There are places in Numba with following code `driver.runtime.get_current_device()` which returns None. And then it accesses to functions of None... crashes.
As I understand the original PR was intended to check if there is current device context or not. It could be achieved in another way without modification of `_curr_device`.
> Revert "Change default current device to None"

- dpctl/ocldrv.py
This PR fixes: `AttributeError: 'Runtime' object has no attribute '_cpu_device'`
It happens only if CPU or GPU device is not available.
> Set _cpu_device and _gpu_device to None by default

- dpctl/sycl_core.pyx
- dpctl/tests/test_sycl_queue_manager.py
If outside context it returns None.
> Add dpctl.get_curent_device_type()

- conda-recipe/bld.bat
With oneAPI beta10 compiler it is not working to use `CC=dpcpp.exe`. Use `CC=clang-cl.exe` instead.
> onaAPI beta10 compiler

- dpctl/sycl_core.pyx
Addresses  #110
The addressof_ref methods of the SyclXXX classes should use size_t instead of long when casting the address to an Python int.
> Change cast from long to size_t

- conda-recipe/bld.bat
This ensures that backend libraries  are copied into dpctl
and included in the conda tar ball.
Also fixed copy statement to account for .lib files being
in %INSTALL_PREFIX%\lib and .dll files being in
%INSTALL_PREFIX%\bin on Windows.
@PokhodenkoSA @diptorupd @reazulhoque
> Use INSTALL_PATH in cmake call

- dpctl/sycl_core.pyx
Allowing both strings or enums as selectors for
backend and device.
> Fixed typo in the code for set_default_queue

- backends/include/dppl_sycl_platform_interface.h
- backends/include/dppl_sycl_queue_manager.h
- backends/source/dppl_sycl_platform_interface.cpp
- backends/source/dppl_sycl_queue_interface.cpp
- backends/source/dppl_sycl_queue_manager.cpp
- backends/tests/test_sycl_platform_interface.cpp
- backends/tests/test_sycl_queue_interface.cpp
- backends/tests/test_sycl_queue_manager.cpp
- dpctl/backend.pxd
- dpctl/sycl_core.pyx
- dpctl/tests/test_dump_functions.py
- dpctl/tests/test_sycl_queue_memcpy.py
- dpctl/tests/test_sycl_usm.py
Fixes for the scenarios where no sycl device except host exists.
> Fix failing platform test case.

- .git-blame-ignore-revs
- .github/workflows/black.yml
- CONTRIBUTING.md
- README.md
- dpctl/__init__.py
- dpctl/_version.py
- dpctl/ocldrv.py
- dpctl/opencl_core.py
- dpctl/tests/test_dump_functions.py
- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_sycl_program.py
- dpctl/tests/test_sycl_queue.py
- dpctl/tests/test_sycl_queue_manager.py
- dpctl/tests/test_sycl_queue_memcpy.py
- dpctl/tests/test_sycl_usm.py
- pyproject.toml
- setup.py
[black](https://github.com/psf/black) is "The Uncompromising Code Formatter".
Usage is simple: `black .`
This PR should be merged, not squashed.
> Add black formatter for Python code

- dpctl/_sycl_core.pxd
- dpctl/sycl_core.pyx
This change enables changes like the following:
```
-    cdef c_dpctl.SyclQueue q = <c_dpctl.SyclQueue>dpctl.get_current_queue()
+    cdef c_dpctl.SyclQueue q = c_dpctl.get_current_queue()
```
> dpctl.get_current_queue is now cimportable

- backends/CMakeLists.txt
See https://wiki.debian.org/HardeningWalkthrough#Testing_your_packages_after_conversion
> Add -D_FORTIFY_SOURCE=2 for fixing hardening-check

- backends/CMakeLists.txt
- backends/dbg_build.sh
- backends/tests/CMakeLists.txt
- backends/tests/test_main.cpp
- backends/tests/test_sycl_device_interface.cpp
- backends/tests/test_sycl_kernel_interface.cpp
- backends/tests/test_sycl_platform_interface.cpp
- backends/tests/test_sycl_program_interface.cpp
- backends/tests/test_sycl_queue_interface.cpp
- backends/tests/test_sycl_queue_manager.cpp
- backends/tests/test_sycl_usm_interface.cpp
- scripts/build_for_develop.bat
- scripts/build_for_develop.sh
Various clean ups and improvements to our gtest infrastructure:
- Use `find_package(GTest)` instead of the home grown gtest locator.
- Remove NumPy and Python includes as these are not needed and if required can be included using `finda_package`.
- Now building a single test runner executable for all tests.
- Do not print verbose `ctest` output by default and run tests in parallel.
> CMake and Gtest improvements

- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
Add `_Memory.get_pointer_type(DPPLSyclUSMRef p, SyclContext ctx)` to return `bytes` that stores the kind.
> Add _Memory.get_pointer_type static method

- conda-recipe/bld.bat
- conda-recipe/build.sh
- conda-recipe/meta.yaml
- Add wheel build to build command
- Copy created package to WHEELS_OUTPUT_FOLDER if it defined
> Add wheels build

- backends/CMakeLists.txt
- backends/helper/include/dppl_utils_helper.h
- backends/helper/source/dppl_utils_helper.cpp
- backends/source/dppl_sycl_device_interface.cpp
- backends/source/dppl_sycl_platform_interface.cpp
PR closes the issue https://github.com/IntelPython/dpctl/issues/182
> Fix utils functions

- backends/source/dppl_sycl_context_interface.cpp
- backends/source/dppl_sycl_platform_interface.cpp
https://jira.devtools.intel.com/browse/SAT-3619
An up - to-date analysis of the klocwork master branch showed 3 warnings. 2 match the previous analysis and have been corrected. Warning memory leak is unchanged because it was created deliberately(Sergey Pokhodenko).
The memory leak warning is still displayed in the klocwork report. I don't know what to do with it. klocwork does not support comments in the code for skipping analysis. You can add a key to build the report table so that the warning is not displayed in the table.
> Fix problems in dpctl identified with Klockwork static code analysis

- CHANGELOG.md
- README.md
- backends/CMakeLists.txt
- backends/helper/include/dppl_utils_helper.h
- backends/helper/source/dppl_utils_helper.cpp
- backends/source/dppl_sycl_device_interface.cpp
- backends/source/dppl_sycl_platform_interface.cpp
- conda-recipe/bld.bat
- conda-recipe/build.sh
- conda-recipe/meta.yaml
- dpctl/memory/__init__.pxd
- dpctl/memory/__init__.py
- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
- scripts/build_backend.py
- setup.py
> Merge gold/2021 with 0.5.0rc1

- MANIFEST.in
- dpctl/__init__.pxd
- dpctl/dparray.py
- setup.py
This isn't complete since I wasn't able to get the file showing up as part of the package so I wasn't able to test much.  Help needed!
> Initial separation of dparray into 2 parts.

- dpctl/dptensor/numpy_usm_shared.py
I was not able to monkeypatch __sycl__usm_array_interface__ into Numba's MemInfoObj as that object appears not to be monkeypatchable.  Instead, I added a callback mechanism so that numba_dppy can register the previous code we had in array_finalize to check for USM MemInfo's.  This way, we still have the same code but without Numba occurring explicitly in dpctl.
> Add callback mechanism so that array_finalize can see if obj is Numba meminfo.

- docs/CMakeLists.txt
- docs/README.md
- docs/dpCtl.dptensor_api.rst
- docs/dpCtl.program_api.rst
- docs/index.rst
- docs/toc_pyapi.rst
- dpctl/__init__.py
- dpctl/_sycl_core.pyx
- dpctl/dptensor/__init__.py
- dpctl/dptensor/numpy_usm_shared.py
Polished up the documentation a bit to match changes done as part of the upcoming 0.5.0 release.
> Doc improvements

- README.md
> Update README section about using setup.py

- setup.py
Try to fix https://github.com/IntelPython/numba-dppy/pull/50#issuecomment-747596584
> Remove cython from install_requires

- dpctl-capi/cmake/modules/FindLevelZero.cmake
- scripts/build_backend.py
- setup.py
- In `build_backend.py` changed compiler from clang++ to dpcpp.
- Removed CC and CXX vars in setup.py since we want to build the extensions using the system compiler and not DPC++
- Provided environment variable hint to find level zero library to build on systems where level zero is in non default path
All these changes were required to get dpctl to build on ANL's JLSE cluster.
> changes to compiler name usage from clang++ to dpcpp

- .gitignore
- README.md
- conda-recipe/meta.yaml
- conda-recipe/run_test.bat
- conda-recipe/run_test.sh
Changes the `run_test` scripts to use `pytest` and adds `pytest` as a run dependency to the `meta.yaml`.
> change run_test scripts to use pytest.

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- dpctl/__init__.py
* Check only Severity: HIGH (`-lll`)
As a side effect [pre-commit](https://pre-commit.com/) is added.
> Add Bandit

- .gitignore
Ignore the generated coverage reports.
> Update .gitignore (#288)

- dpctl-capi/helper/include/dpctl_utils_helper.h
- dpctl-capi/helper/source/dpctl_utils_helper.cpp
- Adds new functions to convert between SYCL and DPCTL enum types. We can not directly cast the values as DPCTL uses bit flags for some of the enum classes. 
- Also added doc strings to old functions.
> Adds new helper functions to convert between DPCTL and SYCL enum values.

- dpctl-capi/CMakeLists.txt
- dpctl-capi/helper/include/dpctl_vector_macros.h
- dpctl-capi/include/dpctl_vector.h
- dpctl-capi/source/dpctl_vector_templ.cpp
- dpctl-capi/tests/CMakeLists.txt
> A set of macros to help create opaque vector classes out of SYCL types

- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_device_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
- add get_backend, get_platform, get_device_type to SyclDevice
- parameterize the Gtests for dpctl_sycl_devie_interface
> Add new getter functions to device interface.

- .github/workflows/black.yml
- .github/workflows/clang-format.yml
- CHANGELOG.md
- dpctl-capi/cmake/modules/FindDPCPP.cmake
* Do not use POP_FRONT in FindDPCPP.cmake so that we can use a cmake version older that 3.15.
> Fix CI for release0.6

- scripts/build_backend.py
This PR fixes Bandit warning in building script related to `subprocess.check_call(..., shell=True)`.
> Fix the flag in "subprocess.check_call" for Windows

- README.md
- setup.py
* Update packages wheel deps
* Make wheel version public-like
* Fix package version
* Remove install_requires
* Append cflags and ldflags from env to build
* Fix issues
* Fix issue with external flags
* Add wheel install description to readme
* Fix formatting
* Fix readme format
> Merge wheel changes from gold/2021

- setup.py
Changes in #327 were adding empty strigs to `compile_args`, `link_args` which was breaking build on GNU toolchain,
Adding clean-up routine to remove empty strings fixes it.
> Fix build break with GNU C++ compiler

- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_device_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
Add sub_group_independent_forward_progress and preferred_vector_width_char
Closes #314 , the part of #286
> Add device descriptors: sub_group_independent_forward_progress and preferred_vector_width

- dpctl-capi/include/dpctl_sycl_device_manager.h
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/source/dpctl_sycl_device_manager.cpp
- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
- dpctl-capi/source/dpctl_sycl_queue_manager.cpp
- dpctl-capi/tests/test_sycl_device_manager.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_queue.pyx
- dpcpp 2021.2 fixed device equality in the dpcpp runtime and we can
now remove several workarounds in dpctl:
- DPCTLDeviceMgr_GetDeviceAndContextPair is now renamed as
DPCTLDeviceMgr_GetCachedContext and only returns a
DPCTLSyclContextRef instead of a pair of DPCTLSyclContextRef
and DPCTLSyclDeviceRef.
- Remove the DPCTLDeviceMgr_AreEq function and related internal
helper functions for hashing SYCL devices.
- Remove DeviceWrapper class inside dpctl_sycl_device_manager.cpp.
- Remove DPCTL_DeviceAndContextPair type form C API.
- Make equivalent changes to the Python API.
> Remove workarounds to make device equality work.

- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
From #334, changes to _sycl_device.pyx and .pxd.
> Fixed signature of SyclDevice._init_helper

- dpctl-capi/helper/include/dpctl_utils_helper.h
- dpctl-capi/helper/source/dpctl_utils_helper.cpp
- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/include/dpctl_sycl_enum_types.h
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_device_subdevices.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
Closes #290 
Changes were added atop commits in #326, and this PR superseded #326.
> Review sub devices

- dpctl/_sycl_context.pxd
- dpctl/_sycl_context.pyx
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue.pyx
`SyclQueue` and `SyclContext` can now be constructed from named capsule objects, with expected names being "SyclContextRef" and "SyclQueueRef".
Classes also acquire a method `_get_capsule(sef)` to construct a capsule from the instance.  
Examples:
```
In [2]: q = dpctl.SyclQueue("level_zero:gpu")
In [3]: cap = q._get_capsule()
In [4]: q1 = dpctl.SyclQueue(cap)
In [5]: q1.equals(q)
Out[5]: True
In [6]: cap
Out[6]: <capsule object "used_SyclQueueRef" at 0x7f0e651689f0>
In [7]: quit
```
```
In [2]: c = dpctl.SyclContext("gpu")
In [3]: c
Out[3]: <dpctl.SyclContext at 0x7fc1123818d0>
In [4]: caps = c._get_capsule()
In [5]: caps
Out[5]: <capsule object "SyclContextRef" at 0x7fc0eb1acb70>
In [6]: c_copy = dpctl.SyclContext(caps)
In [7]: c.equals(c_copy) …
```
> Add capsules

- .github/workflows/black.yml
- CONTRIBUTING.md
The `stable` branch is no longer there in `github.com/psf/black`. Updated our action to use `20.8b1` tag.
> Fix the black action.

- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_queue_manager.py
This PR contains several fixes for tests which should be skipped if GPU is not available but they was not skipped.
1. `dpctl.SyclContext("gpu")` raises `ValueError`. It seems that catching `dpctl.SyclQueueCreationError` is copy/past error.
2. In `test_context_can_be_used_in_queue2` exception was not caught.
3. `TestGetCurrentDevice` uses context `opencl:gpu:0` in several tests so it should be skipped if GPU is not available.
> Fix tests which fail if GPU is not available (only CPU is available)

- dpctl/_sycl_queue.pyx
> fixed docstring type in SyclQueue.equals

- dpctl/_sycl_context.pyx
Simple typo mistake, but can only be discovered at run-time. This is possible now that sub-devices supported has been merged.
> fixed typo in SyclContext code giving a run-time error

- dpctl/_sycl_context.pyx
- dpctl/tests/test_sycl_context.py
The example for multi-device context creation now works as expected:
```python
Python 3.7.9 (default, Mar 10 2021, 05:18:00)
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: cpu_d = dpctl.SyclDevice("cpu")
In [3]: d0, d1, d2 = cpu_d.create_sub_devices(partition=(4,4,4))
In [4]: ctx = dpctl.SyclContext((d0, d1, d2))
In [5]: ctx
Out[5]: <dpctl.SyclContext for 3 devices at 0x7ffb7a82c350>
In [6]: q = dpctl.SyclQueue(ctx, d0)
In [7]: import dpctl.memory as dpmem
In [8]: dpmem.MemoryUSMShared(1024, queue=q)
Out[8]: <Intel(R) USM allocated memory block of 1024 bytes at 0x55e2e6bf4300>
```
> Fixed missing variable assignment

- .coveragerc
- conda-recipe/run_test.sh
Blocked by [SAT-3964](https://jira.devtools.intel.com/browse/SAT-3964). Waiting for coverage package on internal CI.
Closes #280.
Implemented coverage only on Linux. On Windows tests run without coverage.
> Update Python coverage to use pytest-cov

- dpctl-capi/tests/test_sycl_device_subdevices.cpp
Added initialization of `dpctl_domain` to fix numerous compilation warnings while compiling the test file.
> fixed compilation warnings by addition initialization to dpctl_domain

- .gitignore
- MANIFEST.in
- dpctl/_sycl_context.pxd
- dpctl/_sycl_device.pxd
- dpctl/_sycl_event.pxd
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue_manager.pxd
- dpctl/memory/_memory.pxd
This causes Cython to convert `_sycl_core.pxd`, `_sycl_core.pyx`
into `_sycl_core.h` and `_sycl_core.cpp`.
The header file can be used by external C++/C projects to be aware
of SyclContext and SyclQueue python objects defined by dpctl.
These are PySyclContextObject, PySyclQueueObject, which are instances
of PyObject, and `PySyclContextType`, `PySyclQueueType` which can be used
in `PyObject_TypeCheck` calls, validating that a Python object is
a valid `syclobj` entry in `__sycl_usm_array_interface__`.
> Use public keyword in _sycl_core.pxd on SyclContext/SyclQueue

- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
Implements
```c
DPCTLSyclQueueRef get_queue_ref_from_ptr_and_syclobj(
DPCTLSyclUSMRef ptr, object syclobj)
```
This function is to help users of ``__sycl_usm_array_interface__`` to
create a queue from a pointer and a valid `syclobj` entry in the
interface dictionary.
Currently supported variants are:
```
- filter selector string
: creates queue for the device created from the selector
- dpctl.SyclQueue
: use given queue
- dpctl.SyclContext
: find device from ptr and context, create queue from context
: and device
- capsule with SyclQueueRef
: use this queue
- capsule with SyclContextRef
: use this context to recover device and create queue
- any python object that implements method _get_capsule()
: use that capsule as outlined above
```
> Added get_queue_ref_from_ptr_and_syclobj

- dpctl-capi/helper/include/dpctl_vector_macros.h
- dpctl-capi/include/Support/MemOwnershipAttrs.h
- dpctl-capi/include/dpctl_sycl_context_interface.h
- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/include/dpctl_sycl_device_manager.h
- dpctl-capi/include/dpctl_sycl_device_selector_interface.h
- dpctl-capi/include/dpctl_sycl_enum_types.h
- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/include/dpctl_sycl_kernel_interface.h
- dpctl-capi/include/dpctl_sycl_platform_interface.h
- dpctl-capi/include/dpctl_sycl_platform_manager.h
- dpctl-capi/include/dpctl_sycl_program_interface.h
- dpctl-capi/include/dpctl_sycl_queue_interface.h
- dpctl-capi/include/dpctl_sycl_queue_manager.h
- dpctl-capi/include/dpctl_sycl_types.h
- dpctl-capi/include/dpctl_sycl_usm_interface.h
- dpctl-capi/include/dpctl_vector.h
Separated out doxygen fixes from #341
> Various doc string updates to C API files.

- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_context_interface.cpp
- dpctl-capi/tests/test_sycl_device_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- examples/cython/sycl_buffer/bench.py
- examples/cython/sycl_buffer/run.py
- examples/cython/usm_memory/run.py
> Fixes names

- dpctl/_sycl_context.pyx
- dpctl/_sycl_platform.pyx
- dpctl/_sycl_queue.pyx
No functional change, but moved docstring content of `__cinit__` method to the class docstring.
Now `help(dpctl.SyclQueue)` displays the relevant help info.
> moved __cinit__ docstring into class docstrings

- dpctl/_sycl_device.pyx
- dpctl/memory/_memory.pyx
- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_sycl_queue_memcpy.py
`dpctl.memory.MemoryUSMShared` and friends change their interpretation of `queue=None` default from use `dpctl.get_current_queue()` to use `dpctl.SyclQueue()`.
> Feature/memory queue=none

- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pyx
Final cleanups and improvements to docstrings before releasing 0.7.0.
> Docstring fixes

- dpctl/_sycl_context.pyx
- dpctl/_sycl_queue.pyx
Docstrings change:
- Examples for `SyclContext` were modified to run.
- Docstring for `SyclQueue` was modified following the lead of `SyclContext` from #385
> Sycl queue docstrings

- dpctl/_sycl_context.pxd
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_queue.py
`cpdef equals` changed to `cdef equals` in `SyclDevice`, `SyclContext` and `SyclQueue`. 
Method `__eq__` added to `SyclQueue` and `SyclContext`.
Examples modified.
> Equals changes and misc

- dpctl/__init__.py
> Update dpctl module doc string.

- dpctl/_sycl_device.pxd
Use double quotes in honor of everything `black .`
Use the same verbiage as in .pyx file
> Edit to _SyclDevice.__doc__

- dpctl/memory/_memory.pyx
- dpctl/tests/test_sycl_usm.py
Closes #189 
When type-checking input, check for the input to be instance
of abtract class `numbers.Integral`, rather than class `int`
Modified test suite to not expect the test from the ticket
to fail.
> Fix issue 189

- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
- dpctl/tests/test_sycl_usm.py
Closes #396 
This PR permits constructor calls like `dpctl.memory.MemoryUSMShared( obj_with_suai )` to work with Python object whose `__sycl_usm_array_interface__` dictionary specifies non-contiguous strides, and non-byte-size type-string, used to address elements of a contiguous  block of memory. 
I.e. index tuple `(i0, i1, ...)` would address element `offset + strides[0]*i0 + strides[1]*i1 + ...`  in C-array of dimension `shape[0]*shape[1]*...`.
In this case type-less USM memory buffer created addresses memory from the minimal index to maxima index (inclusive) generated by enumeration of all  displacements  `offset + strides[0]*i0 + strides[1]*i1 + ...`  when iterating over all possible tuple of indexes in determined by the `shape`.
Example:
```python
import numpy as np
import dpctl …
```
> Implemented support for constructing MemoryUSM* from object with __sycl_usm_array_interface__ when array-info is not contiguous

- examples/cython/usm_memory/README.md
- examples/cython/usm_memory/blackscholes.pyx
1. initialized pointers to NULL in declaration in source code
2. Noted in README that `CXXFLAGS=-fno-sycl-early-optimizations` is necessary for compiler issue work-around.
> Small changes to examples/cython/usm_memory for BS model

- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
Use `size_t` instead of `Py_ssize_t` to represent USM pointer as Python object. This allows `_USMBufferData` class to understand SUAI with device-pointers.
Also to avoid formatting of the USM-device pointer as a negative hex value, e.g. format `dpctl.memory.MemoryUSMDevice(32)`.
> Use size_t instead of Py_ssize_t to fit device USM pointer

- dpctl/__init__.py
In this PR:
Fixed deprecation warnings by using `r"""string with backslashes"""` as per  [PEP-257](https://www.python.org/dev/peps/pep-0257/).
> Fix deprecation warning

- dpctl/.gitignore
The cython generated header files are added to .gitignore.
> Ignore all Cython generated headers.

- .git-blame-ignore-revs
Added the git commit that fixed linting issues to the git-blame-ignore-revs.
> Ignore all changes done in #422 from git-blame.

- dpctl-capi/helper/include/dpctl_utils_helper.h
- dpctl-capi/helper/source/dpctl_utils_helper.cpp
- dpctl-capi/include/dpctl_sycl_device_manager.h
- dpctl-capi/include/dpctl_sycl_platform_manager.h
- dpctl-capi/source/dpctl_sycl_device_manager.cpp
- dpctl-capi/source/dpctl_sycl_platform_manager.cpp
- dpctl-capi/tests/test_sycl_platform_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_platform.pyx
- dpctl/tests/test_sycl_platform.py
Closes #293 
Improvements to the `print_*_info()` functions in both C and Python APIs.
The `print_device_info()` function now prints the full filter string.
```python
In [2]: d = dpctl.select_gpu_device()
In [3]: d.print_device_info()
Name            Intel(R) UHD Graphics 630 [0x3e98]
Driver version  1.0.19438
Vendor          Intel(R) Corporation
Profile         FULL_PROFILE
Filter string   level_zero:gpu:0
```
The `print_platform_info()` function now supports verbosity levels that can be `0, 1, 2`. The default verbosity level is set to 0.
```python
In [5]: p = dpctl.get_platforms()[0]
In [6]: p.print_platform_info(verbosity=0)
Intel(R) FPGA Emulation Platform for OpenCL(TM) OpenCL 1.2 Intel(R) FPGA SDK for OpenCL(TM), Version 20.3
In [7]: p.print_platform_info(verbosity=1)
Name …
```
> Print the backend as part of print_device_info.

- dpctl-capi/helper/source/dpctl_utils_helper.cpp
- dpctl/tests/test_sycl_device.py
The property should be able to reconstruct the same parent device that produced it,
serving as a device identifier.
N.B.: in the setup we have currently, (additional driver in Python's `lib/`, we have two devices with the same filter selector string).
> Added two tests for filter_string property

- dpctl-capi/source/dpctl_sycl_usm_interface.cpp
- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
Method takes USMRef, number of bytes and queue reference.
If USMRef is bound to context in the queue and USM type comes
back not 'unknown', appropriate MemoryUSM* object is created
which assumes ownership of this memory.
Optional `memory_owner` keyword argument may be specified to set
the recorded reference object to something other than None (signaling
that _Memory is responsible for memory deallocation).
This can be used to create MemoryUSM* Python object from natively
allocated memory, populate it, but leave deallocation to the caller.
It could also be set to a PyCapsule object that carries a custom deleter.
> Static method of _Memory to create from external allocation

- dpctl/tensor/_slicing.pxi
- dpctl/tensor/_usmarray.pxd
- dpctl/tensor/_usmarray.pyx
Data members are renamed to reflect their internal status, since some
of them are read-accessible from Python.
Cython visible field accessors added to retrieve their value.
Made `dpctl.tensor.usm_ndarray` weak-referenceable
https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#making-extension-types-weak-referenceable
> Data members renamed, accessors added

- dpctl/_sycl_queue_manager.pxd
Closes #436 
This addresses unused-variable compiler warning observed when compiling usm_array Cython file.
> Removing public keyword to get_current_queue Cython declaration.

- dpctl/tensor/_types.pxi
- dpctl/tests/test_usm_ndarray_ctor.py
This changes enables one to use NumPy's `np.dtype` in `dtype` keyword of the constructor.
```python
dpt.usm_ndarray(X.shape, dtype=X.dtype)
```
Added a test case to cover this use-case
> Fixed typo in function dtype_to_typenum

- dpctl/tensor/_device.py
- dpctl/tensor/_usmarray.pyx
Data-API notion of device is higher level abstraction. The class
does allow for public constructor, has class method to create
instance instead.
It typesets as Device(filter_string) for parent devices and
Device(queue) for sub-devices. It can constructed from
- filter selector string
- SyclDevice corresponding to a root device
(attempt at passing sub-device raises and error)
- SyclQueue
- Another instance of Device class
It implements sycl_queue, sycl_device, sycl_context attributes.
usm_ndarray adds .device property, and .to_device(device) method.
```
In [5]: X = dpt.usm_ndarray((4, 5), dtype='d')
In [6]: X.device
Out[6]: Device(level_zero:gpu:0)
In [7]: Y = X.to_device('cpu')
In [8]: Y.device
Out[8]: Device(opencl:cpu:0)
```
> Added Device class representing Data-API notion of device

- dpctl/memory/_memory.pyx
Added docstrings
Added public properties:
sycl_context
sycl_device
```
In [4]: dpm.MemoryUSMShared(1024, queue=dpctl.SyclQueue("cpu"))
Out[4]: <SYCL(TM) USM-shared allocated memory block of 1024 bytes at 0x55656e945780>
In [5]: Out[4].sycl_device
Out[5]: <dpctl.SyclDevice [backend_type.opencl, device_type.cpu,  Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz] at 0x7fdeaf804c70>
In [6]: Out[4].sycl_context
Out[6]: <dpctl.SyclContext at 0x7fded1413c50>
In [7]: Out[4].get_usm_type(syclobj=Out[6])
Out[7]: 'shared'
```
> Changed repr for Memory objects

- dpctl/tensor/_device.py
- dpctl/tensor/_slicing.pxi
- dpctl/tensor/_stride_utils.pxi
- dpctl/tensor/_types.pxi
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Fixed bugs in basic slicing and in constructors discovered by examples used during customer presentation. 
Specifically these had to deal with negative strides and sometimes non-unit strides.
For `Xusm  = dpt.usm_ndarray((12,), dtype='i4')`, and `Xusm[1::2]` had incorrect shape of `(5,)`, while the expected shape should be `(6,)`, consisting of elements of `{Xsum[1], Xusm[3], Xusm[5], Xusm[7], Xusm[9], Xusm[11]}`.
Expanded tests, and fixed memory leak in shape/strides parser on failures (C-array for shape was not being freed).
> Fix for slicing bugs

- dpctl/memory/__init__.py
- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
Used the Cython static method from _Memmory.get_pointer_type in the added function,
as well as in the method `get_usm_type`.
Added docstrings.
```python
In [1]: import dpctl, dpctl.memory as dpm, dpctl.memory._memory as dpm_m
In [2]: import dpctl.tensor as dpt
In [3]: X = dpt.usm_ndarray((4, 5))
In [4]: dpm_m.as_usm_memory(X)
Out[4]: <SYCL(TM) USM-device allocation of 160 bytes at 0xffffd556aa5f0000>
In [5]: X.usm_data
Out[5]: <SYCL(TM) USM-device allocation of 160 bytes at 0xffffd556aa5f0000>
In [6]: class Duck_USMAllocation:
...:     def __init__(self, buf, syclobj):
...:         self.buf_ = buf
...:         self.syclobj_ = syclobj
...:
In [7]: class Duck_USMAllocation:
...:     def __init__(self, buf, syclobj):
...:         self.buf_ = buf
...:         self.syclobj_ = syclobj
...: …
```
> Added free Python function as_usm_memory(obj)

- dpctl/tests/test_sycl_program.py
Instead of using `with dpctl.device(...)` and then `q = dpctl.get_current_queue()`, use `q = dpctl.SyclQueue(...)` directly. 
It is cleaner this way.
> used dpctl.SyclQueue instead of manager and get current queue

- dpctl/tests/test_sycl_usm.py
This test checks for conformance to __sycl_usm_array_interface__ spect from Wiki
> Added test for as_usm_memory

- docs/CMakeLists.txt
- docs/Doxyfile.in
We use Doxyrest to generate the API docs for the dpctl C API sources. The changes in the PR make it possible to turn off Doxygen HTML generation, and by default the HTML generation is turned off.
> Add a flag to make doxygen HTML generation optional.

- .github/workflows/generate-docs.yml
- docs/docfiles/dpctl.memory_api.rst
Closes #205
Attempt to add GH action to install oneAPI compiler, compiler dpctl with it locally, generate HTML version of docs.
> Add action to build dpctl using oneAPI and generate docs

- .gitignore
The shared libraries with soname should be ignored by git.
> Ignore generated shared library files.

- README.md
- docs/docfiles/user_guides/QuickStart.rst
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pyx
- dpctl/_sycl_device_factory.pyx
- dpctl/_sycl_event.pyx
- dpctl/_sycl_platform.pyx
- dpctl/_sycl_queue.pyx
- dpctl/_sycl_queue_manager.pyx
- dpctl/memory/_memory.pyx
- dpctl/program/_program.pyx
- dpctl/tensor/_usmarray.pyx
- scripts/build_backend.py
- setup.py
Closes #361 
- The `build_backend.py` is not invoked using a sub-process. We now use `importlib` to properly import the file as a module.
- `build_backend.py` now provides a function to run the build steps to compile `DPCTLSyclInteface`.
- Initial changes to `build_backend.py` to make it possible to pass in different build options. Presently, the only new option that was added is `l0_support`.
- Minor clean ups and fixes to `setup.py`.
> Improvements to setup.py

- setup.py
Use full versioneer-inferred name to define package version.
This is uber useful for development.
> Ensure that package version reflects dirtiness

- scripts/build_backend.py
After introducing so-versioning for `libDPCTLSyclInterface` the symlinks are not being correctly copied from the build directory (`build_cmake`) to the install directory (`dpctl`). The PR fixes this by using the `follow_symlinks` argument to `shutils.copy`.
> Correctly copy symlinks to the dpctl dir.

- dpctl/tensor/_device.py
- dpctl/tests/test_usm_ndarray_ctor.py
Convert couple of Python test cases to use default device instead of the "gpu" device. The change ensures these tests do not fail when a GPU is not available on the build system.
> Use default device for slicing test case instead of gpu device.

- .github/workflows/generate-coverage.yaml
- CONTRIBUTING.md
- README.md
- scripts/build_for_develop.sh
Adding automated workflow to generate unit test coverage report for C and Python APIs for every PR and publish them to coveralls.io.
> Generate coverage data and publish them to coveralls.io

- CONTRIBUTING.md
Update the last section the `CONTRIBUTING.md` file to reflect that `CODE_COVERAGE` envvar is no longer used.
> Fix a left over section in the contributing.md

- dpctl/tensor/_types.pxi
- dpctl/tests/test_usm_ndarray_ctor.py
Expanded the test checking consistency between NumPy's and dpctl's notions.
In master we had (on Linux):
```
In [3]: import numpy as np
In [4]: a = np.array(np.random.random(10), np.int64)
In [5]: da = dpt.usm_ndarray(a.shape, dtype=a.dtype, buffer="shared")
In [6]: da.nbytes
Out[6]: 40
In [7]: a.nbytes
Out[7]: 80
```
This is because `int64` resolved to type long, which was hard coded to be 4 bytes large. 
This changes uses `sizeof` to query compiler for the size.
> Use compiler's sizeof(type) to determine byte-size of types

- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/include/dpctl_sycl_device_selector_interface.h
- dpctl-capi/include/dpctl_sycl_enum_types.h
- dpctl-capi/include/dpctl_sycl_platform_interface.h
- dpctl-capi/include/dpctl_sycl_queue_manager.h
- dpctl-capi/include/dpctl_vector.h
- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/_sycl_device_factory.pyx
- dpctl/_sycl_platform.pyx
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue.pyx
Change function prototypes to suppress compiler warnings and errors when dpctl C API headers are included in an actual C file.
- All function signatures now satisfy ` -Wstrict-prototype` (e.g. `DPCTLQueueMgr_GetCurrentQueue()` to `DPCTLQueueMgr_GetCurrentQueue(void)`
- Make all enums definitions to use a `typedef` so that the `enum` keyword is not needed explicitly.
- Commensurate changes to Cython files.
> DPCTL C API headers are not always truly C complaint (e.g. -Wstrict-prototype)

- conda-recipe/meta.yaml
We no longer have OpenCL wrappers so remove the reference to OpenCL from the meta.yaml summary.
> Remove OpenCL from meta.yaml summary

- dpctl-capi/CMakeLists.txt
The issue is that conda-build would turn symbolic links of version
library shared objects into hard copies.
Downstream project (e.g. numba-dppy) may end up loading different
hard copies of the library and thus maintain different global states
and encounter segfaults from discrepancies in these states
> Turn off SO versioning for release 0.8

- CHANGELOG.md
> Update changelog for 0.8.0 release.

- dpctl/memory/_memory.pyx
It was added in early iterations of #449 but then
superseded by as_usm_memory, and the get_usm_pointer_type
should have been removed.
The reasoning for the removal can be found in comments
left in #449
> Removing get_usm_pointer_type function

- dpctl-capi/CMakeLists.txt
WIP non-functional implementation for linker scripts instead of symlinks. Needs more fixes, cleans up and checks for OS.
> Use linker scripts instead of symlink.

- dpctl-capi/CMakeLists.txt
Reverts IntelPython/dpctl#472
The linker scripts are intended for `ld`, not for `dlopen`. So using linker_scripts to support so-versioning in Python is not going to work. To support so-version we need to figure out how not to turn symbolic links cmake is generating into hard links by conda building.
> Revert "Use linker scripts instead of symlink."

- dpctl-capi/source/dpctl_sycl_platform_interface.cpp
Object 'PRef' was returned at line 98 after being freed by calling 'delete' at line 90. The issue was unlikely to happen as it was done after catching a bad_alloc. The issue was identified by Klockwork static code analysis.
> Fix an issue identified by klockwork.

- dpctl-capi/CMakeLists.txt
- dpctl-capi/cmake/modules/FindIntelSycl.cmake
- scripts/build_backend.py
Closes #480 
@AndresGuzman-Ballen Please check to see if this changes unblocks the use of DPC++ installation in Python environment.
> Implemented support for non-standard installation of oneAPI compiler by dpctl

- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_device_subdevices.cpp
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
Closes #475 
Issue alike crash of ``dpctl.SyclDevice("cpu").create_sub_devices(partition=0)`` should be fixed.
> Fix sub devices

- dpctl/_sycl_context.pyx
- dpctl/_sycl_event.pyx
- dpctl/_sycl_platform.pyx
- dpctl/_sycl_queue.pyx
- dpctl/_sycl_queue_manager.pyx
dpctl supports only Python 3, we do not need to import from `__future__`.
> Remove imports from __future__. The future is here now.

- dpctl-capi/source/dpctl_sycl_platform_interface.cpp
Follow DPCTLDevice_CreateFromSelector which passes the check.
This should fix an issue from SAT-4170: 
>  Possible memory leak. Dynamic memory stored in 'P' allocated through function 'new' at line 84 can be lost at line 88
> Fix SDL check

- .coveragerc
- .github/workflows/generate-coverage.yaml
- CONTRIBUTING.md
- pyproject.toml
- setup.cfg
`coverage` and `pytest` support PEP518 and `pyproject.toml`. The PR moves configurations for these tools into `pyproject.toml.`
> Consolidate configurations of tools that support PEP 518 into pyproject.toml

- dpctl/_sycl_context.pyx
- dpctl/tests/test_sycl_context.py
Closes #484 
- Fixes a typo in the `addressof_ref` function of `SyclContext` that was causing an `AttributeError` and added a unit test for the member.
- Also, added missing unit tests for `SyclContext` and removed the duplicate tests that were copied over from `SyclDevice`.
> Fixes the addressof_ref function of SyclContext and improves unit tests.

- pyproject.toml
Pytest directory exclusion misnamed "conda-recipe" as "conda.recipe" in the pytproject.toml config. The PR fixes the typo.
> Fix a typo in the pytest configuration.

- conda-recipe/run_test.bat
- conda-recipe/run_test.sh
- dpctl-capi/include/dpctl_sycl_context_interface.h
- dpctl-capi/include/dpctl_sycl_device_interface.h
- dpctl-capi/include/dpctl_sycl_queue_interface.h
- dpctl-capi/source/dpctl_sycl_context_interface.cpp
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_context_interface.cpp
- dpctl-capi/tests/test_sycl_device_interface.cpp
- dpctl-capi/tests/test_sycl_queue_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pyx
- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_queue.py
Closes #483 
Superseded #489 (and reuses some changes from there).
> Added C-API hash function, used them in Python interface

- dpctl-capi/source/dpctl_sycl_program_interface.cpp
- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_queue_submit.cpp
Improvements to dpctl_c_api
- Add missing checks to `dpctl_sycl_queue_interface.cpp`
- Add error messages to `dpctl_sycl_program_interface.cpp` inside the level-zero module creation function.
- Refactor the unit tests for `dpctl_sycl_queue_interface.cpp` introducing negative test cases.
- Moved the queue submit test cases into a separate source file.
Note - Unit tests for `DPCTLQueue_Memcpy` and family are not added here. I will be adding them in a separate PR.
> Improve test coverage for dpctl_sycl_queue_interface

- dpctl/tests/test_sycl_platform.py
The test `test_lsplatform3` should be expecting the warning.
This way the test suite passes even with ``-W error::UserWarning``
> Use pytest.warns in test_lsplatform3

- dpctl-capi/tests/test_sycl_device_manager.cpp
In local build the coverage went from red to yellow.
> Added test class to test DRef=nullptr case

- dpctl-capi/tests/test_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_usm_interface.cpp
Test with queues that use different properties, default/non-default error handler to improve coverage.
> Extend parameterized test in test_sycl_queue_interface

- dpctl-capi/CMakeLists.txt
- dpctl-capi/dbg_build.sh
- dpctl-capi/tests/CMakeLists.txt
- dpctl-capi/tests/dpcpp_kernels.cpp
- dpctl-capi/tests/dpcpp_kernels.hpp
- dpctl-capi/tests/test_sycl_queue_submit.cpp
This does not presently work with coverage turned on due to LLVM version discrepancy between IGC and DPC++.
So the test is excluded for the build with coverage.
> Added a test that retrieved DPCPP compiled kernel and submits them via DPCTLQueue_SubmitRange

- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR adds the `DPCTLEvent_Copy` function which returns a copy of the `DPCTLSyclEventRef` object.
> Add a new DPCTLEvent_Copy function 

- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR adds the DPCTLEvent_GetBackend function which returns the DPCTLSyclBackendType enum value identifying the SYCL backend associated with the event.
> Add a new DPCTLEvent_GetBackend function

- dpctl-capi/source/dpctl_sycl_program_interface.cpp
This PR will propagate compiler flags to `clBuildProgram()`
> Propagate compile flags

- conda-recipe/build.sh
- conda-recipe/meta.yaml
Now dpcpp_linux-64 compiler is available on `-c intel`. It is not necessary to install oneAPI.
This PR uses dpcpp compiler package instead of using oneAPI.
Only for Linux.
> Use dpcpp compiler package for Linux

- dpctl-capi/helper/include/dpctl_utils_helper.h
- dpctl-capi/helper/source/dpctl_utils_helper.cpp
- dpctl-capi/include/dpctl_sycl_enum_types.h
- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR 
- adds the `DPCTLEvent_GetCommandExecutionStatus` function, which returns the value of the `DPCTLSyclEventStatusType` enumeration for the DPCTLSyclEventRef argument.
- adds a new `DPCTLSyclEventStatusType` enumeration for all types from the [SYCL specification](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#appendix.event.descriptors)
- adds `DPCTL_SyclEventStatusToDPCTLEventStatusType` converter function from `sycl:: info` to `DPCTLSyclEventStatusType` enumeration types
> Add a new DPCTLEvent_GetCommandExecutionStatus function

- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR adds a function `DPCTLEvent_GetWaitList` which waits for the event to complete and calls the asynchronous error handler
> Add a new DPCTLEvent_WaitAndThrow function 

- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR adds 3 wrapper functions ( `DPCTLEvent_GetProfilingInfoStart`, `DPCTLEvent_GetProfilingInfoEnd`, `DPCTLEvent_GetProfilingInfoSubmit`) for `sycl::event::get_profiling_info()`.
> Add 3 new functions for sycl::event::get_profiling_info

- dpctl-capi/include/dpctl_sycl_event_interface.h
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
This PR adds the 'DPCTLEvent_GetWaitList' function which returns the list of events that this event waits for in the dependence graph.
> Add a new DPCTLEvent_GetWaitList function

- dpctl/__init__.py
- dpctl/_backend.pxd
- dpctl/_sycl_event.pxd
- dpctl/_sycl_event.pyx
- dpctl/tests/test_sycl_event.py
This PR will add a new `SyclEventRaw` class and tests for it.
> Add a new SyclEventRaw class

- dpctl/__init__.py
- dpctl/_backend.pxd
- dpctl/_sycl_event.pyx
- dpctl/enum_types.py
- dpctl/tests/test_sycl_event.py
This PR adds the  `execution_status`  method which returns the value of the 'event_status_type' enumeration.
> Add a `execution_status` method for the SyclEventRaw class

- dpctl/_backend.pxd
- dpctl/_sycl_event.pyx
- dpctl/tests/test_sycl_event.py
This PR will add a `get_backend` method for the `SyclEventRaw` class which returns the backend enum.
> Add a `get_backend` method for the SyclEventRaw class

- dpctl/_backend.pxd
- dpctl/_sycl_event.pyx
- dpctl/tests/test_sycl_event.py
This PR will add a `wait_list` method for the `SyclEventRaw` class which returns a list of events that the event is still waits for.
> Add a `wait_list` method for the SyclEventRaw class

- dpctl/tensor/_types.pxi
- dpctl/tests/test_usm_ndarray_ctor.py
A test added to check for this.
> dtype keyword of usm_ndarray now supports np.double and other types

- dpctl/_sycl_event.pxd
- dpctl/_sycl_event.pyx
This PR removes method the static method `_init_helper` from the SyclEventRaw class.
> Remove `_init_helper` from the SyclEventRaw class

- dpctl/_backend.pxd
- dpctl/_sycl_event.pyx
- dpctl/tests/test_sycl_event.py
This PR adds 3 methods (`profiling_info_submit`. `profiling_info_start`. `profiling_info_end`) for the `SyclEventRaw` class that return a value describing the time in nanoseconds.
> Add 3 methods of the SyclEventRaw class for profiling

- dpctl-capi/include/dpctl_sycl_queue_interface.h
- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_queue_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_queue.py
C-API function `DPCTLQueue_HasEnableProfiling(QRef)` that returns `true` if `QRef` references a ``sycl::queue`` that was created to have property ``sycl::property::queue::enable_profiling``.
`dpctl.SyclQueue` acquired property `dpctl.SyclQueue.has_enable_profiling`. 
This was used in `dpctl.SyclQueue.__repr__` to echo properties of the queue instance.
> Queue has enable profiling

- dpctl/_sycl_context.pxd
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/_sycl_platform.pxd
- dpctl/_sycl_platform.pyx
and removed from PXD files.
This is purely stylistic and should have no functional effect.
> Static methods _init_helper made into functions

- dpctl/_sycl_context.pxd
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pxd
- dpctl/_sycl_device.pyx
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue.pyx
Also introduce C-API functions to retrieve opaque DPCTL references
from Python objects.
This is useful in using `dpctl` entities as arguments in pybind11
applications
> Use public for data owning class definitions

- README.md
Double dash was needed instead of single dash in front of
extra-index-url option.
Fixes #525
> Fixed typo in pip installation instruction. Fixes #525

- dpctl-capi/include/dpctl_service.h
- dpctl-capi/source/dpctl_service.cpp
- dpctl-capi/tests/test_service.cpp
Fixed Config/dpctl_config.h.in so that `DPCTL_DPCPP_VERSION` preprocessor
variable is now non-empty.
Created `const char * DPCTLService_GetDPCPPVersion(void)` service function
to get the version stored in that preprocessor variable.
This would allow Python to record minimum version requirement for the
DPC++ toolchain runtime.
```
Python 3.7.10 (default, Jun  4 2021, 06:52:02)
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import dpctl, ctypes
In [2]: lib = ctypes.cdll.LoadLibrary('dpctl/libDPCTLSyclInterface.so')
In [3]: fn = lib.DPCTLService_GetDPCPPVersion
In [4]: fn.argtypes=[]
In [5]: fn.restype = ctypes.c_char_p
In [6]: fn()
Out[6]: b'2021.3.0'
```
> Fixed dpctl_config, added dpctl_service.h, .cpp

- docs/requirements.txt
- requirements.txt
- setup.py
This PR adds `install_requires=["numpy", "dpcpp_cpp_rt"]` keyword argument to `setup` call. 
It also adds `requirements.txt` and `docs/requirements.txt` per #398 
Imposing minimal version requirement on `dpcpp_cpp_rt` does not appear possible in `setup.py` because `install_requires` must be provided before the `build_backend` script has a chance to run. 
We should add a Python visible function to get the output of `DPCTLService_GetDPCPPVersion()`.
> Add install requires

- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Closes #547 
Property `__sycl_usm_array_interface__` is to use `self.shape` rather
than call _make_int_tuple directly.
```
In [4]: dpt.usm_ndarray(tuple(), dtype='d').__sycl_usm_array_interface__
Out[4]:
{'data': (94536841949184, True),
'shape': (),
'strides': None,
'typestr': '|f8',
'version': 1,
'syclobj': <dpctl.SyclQueue at 0x7f5bbeb3f780>,
'offset': 0}
```
@shssf @Alexander-Makaryev
> Fixes #547

- examples/python/dppy_kernel.py
- examples/python/sycl_timer.py
This PR adds a python `sycl_timer file` containing the `SyclTimer` class and the `dppy-kernel file` as an example for working with this class
> Add the SyclTimer class to the examples

- dpctl/_backend.pxd
- dpctl/_sycl_event.pxd
- dpctl/_sycl_event.pyx
- dpctl/tests/test_sycl_event.py
This PR adds a static method `wait` for the SyclEventRaw class with a call to `DPCTLEvent_WaitAndThrow`
> Add a static method `wait` for the SyclEventRaw class

- dpctl/memory/_memory.pyx
Added Python C-API functions to access data payload of `_Memory` python instances.
These are being added to `dpctl/memory/_memory.h`.
> Added public C functions to access data payload of USMMemory* objects

- dpctl/_sycl_event.pxd
- dpctl/_sycl_event.pyx
This PR adds and modifies docstrings for the 'SyclEventRaw' class.
> Add docstrings for the SyclEventRaw class

- .github/workflows/conda-package.yml
Added build of dpсtl package to github runner on windows
Tested locally run: https://github.com/1e-to/dpctl/pull/4
> Add workflow for win

- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Added tests for constructor with some invalid dtypes to improve coverage.
> Improved coverage of _types.pxi

- dpctl/__init__.py
- dpctl/_sycl_timer.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_kernel_submit.py
- examples/python/dppy_kernel.py
Added docstring, made dt into a property (rather than a method).
Removed stray "SyclEventRaw" from __all__ in dpctl/__init__.py
> Moved sycl timer into dpctl.SyclTimer

- dpctl/__init__.py
- dpctl/_device_selection.py
- dpctl/tests/test_sycl_device.py
This PR adds the device selection function by aspects and tests to it.
Docstrings will be added in the next commit.
> Add aspect selector

- README.md
This PR modifies README.md to format better. Only the "What" section was modified. 
Use this [link](https://github.com/IntelPython/dpctl/tree/tweak-oneAPI-logo-placement) to view the rendered README.md page.
> Try using <img> tag with alignment attribute set

- dpctl-capi/include/dpctl_sycl_queue_interface.h
- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_queue_interface.cpp
- dpctl-capi/tests/test_sycl_usm_interface.cpp
- dpctl/_backend.pxd
- dpctl/_sycl_queue.pyx
- dpctl/memory/_memory.pyx
The return value of these functions changed. Declaration, documentation,
tests and implementations updated in dpctl-capi/.
dpctl/_backend.pxd updated for changed return type. Usages updated
accordingly to get the event and wait on it to preserve the behavior
for now.
> DPCTLQueue_Memcpy, _Prefetch, _Memadvise become asynchronous

- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_queue.py
Added test to sycl context testing file to create a context
from a sub-device
> Added some tests to involve capsule

- dpctl/tests/test_sycl_platform.py
Added test exercising `__repr__`, and a test for `dpctl.SyclPlatform()` invocation of the constructor.
> added test for repr and test for default argument to constructor

- dpctl/tests/test_service.py
- setup.cfg
- setup.py
Added tests to check `DPCTLService_GetDPCPPVersion`, `dpctl.get_include`, and `dpctl.__version__`.
> Improve coverage of dpctl.__init__ file and other service functions

- dpctl/tests/test_service.py
`0.9.0dev0` is not strictly PEP-440 compliant. It follows semantic version convention. Reg-exp is relaxed to accommodate for that.
> Fixed __version__ test to allow for semantic versioning

- dpctl/_sycl_context.pyx
- dpctl/_sycl_event.pyx
- dpctl/_sycl_queue.pyx
This should also improve coverage.
> Capsule deleters should service used renamed capsules too

- dpctl/tests/test_sycl_event.py
Added tests to exercise unusued capsule deleter, and a test to exercise `addressof_ref` method.
> Tweaks to test_sycl_event to improve coverage

- conda-recipe/build.sh
Workaround to Klocwork overwriting LD_LIBRARY_PATH that was modified by DPC++ compiler conda packages. Will need to be added to DPC++ compiler activation scripts.
> Workaround for running conda-build using Klocwork

- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
Since Cython is compiled with language_level=3 working with unicode type
is obsolete (we should work with str type instead).
Removed the dead branch of code.
Added test to exercise repr method
> Simplified arg parsing in SyclDevice constructor

- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_queue.py
Modernized parsing of filter selector string (use `str` instead of `unicode` Cython type). 
Fixed several typos in memory operation methods of SyclQueue. 
Removed `dpctl.SyclQueue.get_sycl_backend` method, and added `backend` property that reuses that code. 
Extended tests to improve coverage.
> Coverage sycl queue

- dpctl/_sycl_queue_manager.pyx
- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
- dpctl/tests/test_dparray.py
- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_sycl_program.py
- dpctl/tests/test_sycl_queue_manager.py
- dpctl/tests/test_sycl_queue_memcpy.py
- dpctl/tests/test_sycl_usm.py
Changed all test files that used `unittest` to use `pytest` instead.
Expanded tests to improve coverage. 
Fixed several unreferenced bugs/crashes uncovered by expanded test suite.
> Transition all Python API to use pytest over unittest, improved coverage in dpctl/memory 

- dpctl/_sycl_event.pyx
- dpctl/tests/_helper.py
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_queue.py
`SyclEvent` destructor now only calls wait and delete on non-null references.
Added tests to check that constructors handle invalid capsules. 
Added tests to very that queues from different platforms are unequal, added test for validation that creating `SyclQueue` from a context and a devices not from that context.
Added tests to check that creation of `SyclContext` from devices from different platforms fails.
> Added tests for constructors with invalid capsules

- .flake8
- .github/workflows/generate-coverage.yaml
- MANIFEST.in
- conda-recipe/meta.yaml
- dpctl/_sycl_queue.pxd
- dpctl/_sycl_queue.pyx
- dpctl/tests/_cython_api.pyx
- dpctl/tests/setup_cython_api.py
- dpctl/tests/test_sycl_queue.py
- pyproject.toml
1. Added docstrings
2. Added optional keyword argument props, to allow queue creation
with properties.
3. Modified pyproject.toml to not collect coverage of `dpctl/tests/*` and not to report it. Thus, this PR closes #374 
4. `test_sycl_queue` now adds a test that build a cython extension and calls Cython API functions, e.g. static methods of classes.
> Static method SyclQueue._create_from_context_and_device change

- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_sycl_queue.py
Parameterize OpenCL kernel argument types to improve coverage of kernel submit
> Parametrize ocl kernel compiled from source in types of arguments

- dpctl/memory/_sycl_usm_array_interface_utils.pxi
- dpctl/tensor/_slicing.pxi
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
> Add methods __bool__, __float__ and __int__ to usm_ndarray

- examples/pybind11/use_dpctl_syclqueue/example.py
- examples/pybind11/use_dpctl_syclqueue/pybind11_example.cpp
Fixed clang-format induced issue with ordering of includes in the pybind11 example. 
The "dpctl_sycl_types.h" must be included before dpctl's CPython API headers (e.g. `_sycl_queue_api.h`). Otherwise compilation errors with `DPCTLSyclQueueRef` is underfined.
Implemented two more functions, retrieving useful device properties, such as Global and local memory size in bytes. (see #587)
> Used clang-format off, clang-format on to avoid include reordering

- .github/workflows/python_style_checks.yml
Changed to use configuration input to specify CLI arguments.
Prompted by warning in https://github.com/IntelPython/dpctl/actions/runs/1249104763
> isort GH action changed and no longer accepts `args` input

- dpctl/tensor/__init__.py
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_reshape.py
- dpctl/tensor/_stride_utils.pxi
- dpctl/tensor/_usmarray.pxd
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_operators.py
Use of `public` keyword when declaring `usm_ndarray` Cython class amounted to Cython exposing private struct members to Python (such `usm_ndarray.typenum_`, `usm_ndarray.nd_`, etc)
Keeping only `api` (no ``public``), these members are not longer exposed, while the python object and its type remain exposed.
Added ``__pyx_capi__`` functions to access these private members, paving the road to using these classes in C/C++ extensions, e.g. built with help of pybind11.
Added tests to test these ``__pyx_capi__`` functions.
This PR has also grown to add `__setitem__` special method to `usm_ndarray` class, as well as `dpctl.tensor.astype(array, new_dtype, order="K", copy=True)` and `dpctl.tensor.reshape(array, new_shape, order="C")`.
`usm_ndarray` can also be reshaped using `shape` setter if this …
> usm_ndarray object special methods, and other changes 

- dpctl/tensor/__init__.py
- dpctl/tensor/_copy_utils.py
- dpctl/tests/test_usm_ndarray_ctor.py
Added `dpctl.tensor.copy` and `dpctl.tensor.asnumpy`, which is an alias to `dpctl.tensor.to_numpy`.
> Added dpt.copy, and dpt.asnumpy (alias of dpt.to_numpy)

- CHANGELOG.md
Populated changelog with summary of changes since 0.9 release.
> Update CHANGELOG for 0.10

- examples/cython/sycl_buffer/use_sycl_buffer.cpp
- examples/cython/sycl_direct_linkage/sycl_function.cpp
- examples/cython/usm_memory/sycl_blackscholes.cpp
- examples/cython/usm_memory/sycl_blackscholes.hpp
- examples/pybind11/external_usm_allocation/README.md
- examples/pybind11/external_usm_allocation/_usm_alloc_example.cpp
- examples/pybind11/external_usm_allocation/example.py
- examples/pybind11/external_usm_allocation/setup.py
- examples/pybind11/use_dpctl_syclqueue/pybind11_example.cpp
Native Pybind11-generated extension implemented Python type bound to
`DMatrix` C++ class which allocates USM memory using ``sycl::usm_allocator``.
The Python object implements ``__sycl_usm_array_interface__``, which allows
dpctl.memory.as_usm_memory to create a view into that native USM allocation.
The example.py modifies that memory from Python, and uses object's own
`.tolist()` method to retrieve the memory using C++, demonstrating that
values changed.
Also added license missing headers to .cpp and .hpp files from other
examples
> Added new example of Python object exposing __sycl_usm_array_interface__

- dpctl/tensor/_copy_utils.py
The following example used to be very slow
```python
X = dpt.usm_ndarray((1_000_000, 4), "d")
Z1 = dpt.usm_ndarray((1_000, 4), "d")
X[:1_000] = Z1
```
due to missing return after early optimization call.
> Silly typo behind slow copy

- .github/workflows/conda-package.yml
- conda-recipe/build.sh
- conda-recipe/meta.yaml
> Use Python 3.9 [in public CI]

- dpctl-capi/source/dpctl_sycl_queue_interface.cpp
For bookkeeping filed an issue behind the hang as XDEPS-2765. 
Fix for the hang is to avoid passing nullptr argument to ``sycl::queue::prefetch``.
> Avoid passing nullptr to sycl::queue::prefetch to avoid buggy hang

- dpctl-capi/CMakeLists.txt
No meaningful functional change, just moved status message, identical in both branches of the if/else statement to after the conditional.
> Moved repeated status message outside of if/else statement

- .github/workflows/generate-coverage.yaml
This would work around a bug reported as #611 and independently
serve to ascertain that code remains buildable with older compiler.
> Coverage workflow is to use oneAPI 2021.3

- dpctl/tests/test_sycl_device_factory.py
Per filter selector spec, correct way to refer to host backend and host device is "host:host", so make tests do so.
The filter string "host:host_device" was tripping OS llvm/sycl compiler.
> replace host_device device type with host in test

- dpctl-capi/CMakeLists.txt
- dpctl-capi/include/Config/dpctl_config.h.in
- dpctl-capi/source/dpctl_sycl_program_interface.cpp
Store that in include/Config/dpctl_config.h and use the define in
dpctl_sycl_program_interface.cpp
CMake is running the equivalent of the following
```
readelf -d $DPCPP_ROOT/lib/libpi_level_zero.so | grep libze_loader | grep -Po "libze_loader[^\]]*"
libze_loader.so.1
```
This change, together with #603 and #616 make project buildable with OS compiler.
> Use readelf on pi_level_zero library to find exact name of ze_loader

- dpctl-capi/CMakeLists.txt
- dpctl-capi/source/dpctl_sycl_context_interface.cpp
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/source/dpctl_sycl_device_manager.cpp
- dpctl-capi/source/dpctl_sycl_device_selector_interface.cpp
- dpctl-capi/source/dpctl_sycl_event_interface.cpp
- dpctl-capi/source/dpctl_sycl_platform_interface.cpp
- dpctl-capi/source/dpctl_sycl_queue_manager.cpp
- dpctl-capi/source/dpctl_vector_templ.cpp
- dpctl-capi/tests/test_sycl_context_interface.cpp
- dpctl-capi/tests/test_sycl_event_interface.cpp
- dpctl-capi/tests/test_sycl_platform_interface.cpp
Also replaced ``sycl::ONEAPI::filter_selector`` with ``sycl::ext::oneapi::filter_selector``
The packages compiles using open source SYCL compiler after these changes, specifically I used
```
(py39) [13:20:15 ansatnuc04 dpctl]$ clang++ --version
clang version 14.0.0 (https://github.com/intel/llvm 7c17ad9a2bfbf6ff2757f8c7fbd2939841f35fa5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /localdisk/work/opavlyk/sycl_workspace/llvm/build/bin
```
Only one meaningful failure in the so compiled package:
```
>       dpctl_prog.create_program_from_spirv(q, spirv)
dpctl/tests/test_sycl_program.py:93:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Remove use of DPC++ features deprecated in 2021.4 and open source intel/llvm compiler

- dpctl/memory/_memory.pyx
In deciding where a copy from device could be done using a direct
call to memcpy, we queried usm type of the source allocation with
respect to the context to which the destination allocation was
bound.
The test was assuming that any answer other than 'unknown' indicated
that the USM allocation was known and a memcpy could be called.
This did not work well when destination was a host device. For example,
this crashed:
```
SYCL_ENABLE_HOST_DEVICE=1 python -m pytest dpctl/tests/test_usm_ndarray_ctor.py::test_to_device
```
It passes now.
> Rework the logic in memory's copy_from_device

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_reshape.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Caught few bugs and fixed them in the process as a perk.
> Added tests to cover red lines in coverage report

- dpctl-capi/helper/include/dpctl_string_utils.hpp
- dpctl-capi/include/dpctl_sycl_device_manager.h
- dpctl-capi/source/dpctl_service.cpp
- dpctl-capi/source/dpctl_sycl_device_interface.cpp
- dpctl-capi/source/dpctl_sycl_device_manager.cpp
- dpctl-capi/source/dpctl_sycl_kernel_interface.cpp
- dpctl-capi/source/dpctl_sycl_platform_interface.cpp
- dpctl-capi/tests/test_sycl_device_manager.cpp
The PR adds a new helper function in dpctl_sycl_device_manager called `DPCTLDeviceMgr_GetDeviceInfoStr`. The function returns a C string containing the device attributes currently printed out by `DPCTLDeviceMgr_PrintDeviceInfo`. The change will unblock #542.
Added a helper to convert C++ strings to C strings, Reduces code duplication.
> Add a new utility function to return the device info as a C string object.

- dpctl/_sycl_device.pyx
This now passes
```
SYCL_ENABLE_HOST_DEVICE=1 SYCL_DEVICE_FILTER=host:host python -m pytest dpctl/tests/test_sycl_device.py
```
> Always raise SubDeviceCreationError even when counts are zero

- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_queue.py
The stream `std::cout` that the library writes to in a function like
`DPCTLDeviceMgr_PrintDeviceInfo` is not the same as Python's `sys.stdout`.
It makes it difficult to verify that printed output is what should be
expected.
Used `OutputGrabber` class to try to capture `std::cout` outputs of `DPCTLSyclInterface`.
The class is implemented in new `test/_redirector.py` file.
The changes in this commit allow the test to pass, while ensuring
that the captured output is non-empty, but pytest must be envoked with
`--capture=no` option.
It works as follows:
```
(idp) [14:36:03 ansatnuc04 dpctl]$ ipython
Python 3.7.10 (default, Jun  4 2021, 06:52:02)
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import …
```
> DPCTLSyclInterface should avoid functions that print to std::cout

- .github/workflows/conda-package.yml
The workflow should trigger on pushes to any branch, and on pull_requests
> The conda-package workflow triggers change

- README.md
Python API of `dpctl` is tied up to DPC++, depending on some of its SYCL extensions, such as [`filter_selector`](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/FilterSelector), [default platform context](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/PlatformContext), [queue barrier](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/EnqueueBarrier), etc. 
It is best thus to say that `dpctl` exposes to Python a subset of DPC++ functionality, rather than a subset of SYCL functionality.
> Improved verbiage in "What?" section

- conda-recipe/meta.yaml
From @tomashek (SAT-4412):
> dpcpp_cpp_rt was renamed to dpcpp-cpp-rt. We need to make sure we are using the new ones. The old are still around for backward compatibility.
> Use renamed DPC++ runtime package `dpcpp-cpp-rt`

- dpctl-capi/helper/include/dpctl_string_utils.hpp
Set the last byte of new array of chars to 0 to explicitly ensure null-termination.
Noting that the source of the copy, `str.c_str()` is always null-terminated  (see [c++-reference](https://www.cplusplus.com/reference/string/string/c_str/)), the terminating character of the destination depends on how many bytes the `strncpy_s` actually copies.
Feel free to dismiss.
> set the last byte in allocated char array to zero.

- dpctl/memory/_memory.pyx
- dpctl/tests/test_sycl_usm.py
> Memory properties

- docs/docfiles/dpctl_pyapi.rst
Closes #652 
Also changes namespace of referenced SYCL classes from `cl::sycl::` to `sycl::`.
> Correction to dpctl_pyapi.rst

- .github/workflows/generate-coverage.yaml
See 
https://github.com/TheKevJames/coveralls-python/issues/333
The known work-around is to pin coveralls to 3.2.0
> Pin coverage at 3.2.0 to work around TheKevJames/coveralls-python#333

- docs/docfiles/dpctl_pyapi.rst
#661 actually broke the links to the Python API pages from the Python API landing pages. The PR fixes the links.
> Fix the hyperlinks to dpctl Python Classes API docs.

- dpctl/_sycl_queue_manager.pyx
@samaid 
It is best to squash all these commits into 1, but can be done once the PR is approved.
> Docs/ sycl queue manager.pyx

- .github/workflows/generate-docs.yml
Make sure that generated docs are published on intelpython.github.io/dpctl/pulls/prnum
> Try to publish generated_docs from PR sources and comment on the PR

- libsyclinterface/source/dpctl_sycl_program_interface.cpp
Minor change to set the structure type of the descriptor struct.
Set structure type to ZE_STRUCTURE_TYPE_MODULE_DESC
See https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv416ze_module_desc_t
> Set stype fields in ZeModuleDesc struct

- .github/workflows/generate-docs.yml
The hope is that using `persist-credential:false` would fix the following
failure to push
remote: Permission to IntelPython/dpctl.git denied to github-actions[bot].
> Attempt to fix permission on push issue

- CHANGELOG.md
This supersedes #676 
It removes conflicts by not attempting to merge identical changes cherry-picked into release0.11 from master back into master.
It also squashes two commits with identical commit messages modifying `CHANGELOG.md`.
> Update CHANGELOG for 0.11.1

- .github/workflows/os-llvm-sycl-build.yml
Update to use OpenCL driver bits published with [DPC++ 2021-09 release](https://github.com/intel/llvm/releases/tag/2021-09).
> Use oclclpuexp and fpgaemu published with 2021-09 release of Intel llvm/sycl

- CHANGELOG.md
- dpctl/__init__.py
- dpctl/_sycl_queue_manager.pyx
- dpctl/tests/test_sycl_queue_manager.py
Relates to https://github.com/IntelPython/numba-dppy/pull/630.
> Extending `dpctl.device_context` with nested contexts

- dpctl/tensor/_stride_utils.pxi
- dpctl/tests/test_usm_ndarray_ctor.py
Constructor make more rigorous checks for contiguity flags.
This fixes #693 
When constructor is checking contiguity of the 1D array, it needs to
account for 1-element array no matter the value of strides[0].
Similarly for higher dimensionality, contiguity check should not
take into account slots with dimensions of 1.
```
X1 = usm_ndarray((1,3,1), 'i4', 'device', strides=(0,1,0))
X2 = usm_ndarray((2,1,3), 'i4', 'device', strides=(3, 0, 1))
X3 = usm_ndarray((2,1,3), 'i4', 'device', strides=(1, 0, 2))
```
tests added.
> Fixes #693 : Reshape clears contiguity flags

- CHANGELOG.md
- dpctl-capi/helper/include/dpctl_string_utils.hpp
Backport of #650 to release 0.11 branch.
> Set the last byte in allocated char array to zero [cherry picked from #650]

- dpctl/tensor/_ctors.py
- dpctl/tests/test_tensor_asarray.py
Fixed #696
```python
In [3]: import dpctl.tensor as dpt
In [4]: dpt.asarray( [[],]*2)
Out[4]: <dpctl.tensor._usmarray.usm_ndarray at 0x7fe5c92a8450>
In [5]: Out[4].dtype
Out[5]: dtype('float64')
```
> Fixed type inferencing for nest sequences with no elements

- libsyclinterface/helper/source/dpctl_utils_helper.cpp
- libsyclinterface/source/dpctl_sycl_context_interface.cpp
- libsyclinterface/source/dpctl_sycl_program_interface.cpp
- libsyclinterface/source/dpctl_sycl_queue_manager.cpp
- libsyclinterface/tests/test_helper.cpp
- libsyclinterface/tests/test_sycl_context_interface.cpp
- libsyclinterface/tests/test_sycl_device_interface.cpp
- libsyclinterface/tests/test_sycl_device_selector_interface.cpp
- libsyclinterface/tests/test_sycl_kernel_interface.cpp
- libsyclinterface/tests/test_sycl_platform_interface.cpp
- libsyclinterface/tests/test_sycl_program_interface.cpp
- libsyclinterface/tests/test_sycl_queue_manager.cpp
- libsyclinterface/tests/test_sycl_queue_submit.cpp
- libsyclinterface/tests/test_sycl_usm_interface.cpp
Adding tests to libsyclinterface to improve library test coverage.
> Sycl interface null args

- .github/workflows/generate-docs.yml
Use `make Sphinx || exit 1`.
See https://stackoverflow.com/a/57907146/594376
Were this change in place, it would have prevented #704 docs generation job from succeeding and erasing existing directory.
> Make sure to fail worfklow step in doc generation of make Sphinx errs

- dpctl/tensor/_ctors.py
Fixes #698 
When processing sequence of sequences, pass requested array data type
to numpy converter to ensure that the expected `ValueError` is raised:
```
In [2]: import dpctl.tensor as dpt
In [3]: dpt.asarray([float("nan"), -1, 1], dtype="i8")
ValueError                                Traceback (most recent call last)
<ipython-input-3-5393cc22ddff> in <module>
----> 1 dpt.asarray([float("nan"), -1, 1], dtype="i8")
/.../dpctl/dpctl/tensor/_ctors.py in asarray(obj, dtype, device, copy, usm_type, sycl_queue, order)
389         if devs == _host_set:
390             return _asarray_from_numpy_ndarray(
--> 391                 np.asarray(obj, dtype=dtype, order=order),
392                 dtype=dtype,
393 …
```
> Fixes #698

- dpctl/tensor/__init__.py
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/_device.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Exported `dpctl.tensor.Device` as array-API device class
This is returned by `X.device`, as before.
Addressed `dpt.asnumpy.__name__` not being 'anumpy',
and `dpt.to_numpy.__name__` not being `to_numpy'.
Added `normalize_queue_device` to `_device.py` as a utility
> Exported dpctl.tensor.Device as array-API device class

- libsyclinterface/helper/source/dpctl_error_handlers.cpp
- libsyclinterface/tests/CMakeLists.txt
This PR fixes issue #714  and renames the `get_requested_level` function to `requested_verbosity_level` for better readability.
> Fix the output conditions in error_handler and rename the `get_requested_level` function

- docs/Doxyfile.in
Sphinx does not support mixed case labels. To work around the issue,
we force Doxygen to generate only lowercase labels. Refer:
https://github.com/vovkos/doxyrest/issues/33
> Fix broken links in the libsyclinterface html pages.

- docs/generate_rst.py
- _sycl_device_factory consists of device selection and
other functions. Added a check to list all device
selections functions as a group and all other functions
as "Others".
- Also generate labels for classes and function sections, so that they
are we can easily reference them from other pages.
> Add a special case to document device factory functions.

- dpctl/tensor/_copy_utils.py
- dpctl/tests/test_tensor_asarray.py
Restores parity in performance of two scenarios in time_copy.py script
```
(idp_2021.4) [13:33:21 ansatnuc04 python]$ python time_copy.py
Wall time:  0.0004440806806087494  sec.
Device time:  9.926800000000001e-05  sec.
Wall time:  0.0006928546354174614  sec.
Device time:  0.000150562  sec.
```
> Fixes #723: slow item assignment from numpy array

- examples/python/device_selection.py
- examples/python/filter_selection.py
- Use `try`..`except` in examples to make sure we do not
crash on a system where needed drivers are not installed.
> Added an example showing filter string usage.

- examples/python/device_selection.py
- examples/python/filter_selection.py
Added an example for `select_device_with_aspects`. 
We do not need a custom function for printing device information, use `SyclDevice.print_device_info`.
> Add example for select_device_with_aspects.

- .github/workflows/conda-package.yml
- examples/cython/sycl_buffer/_buffer_example.pyx
- examples/cython/sycl_buffer/run.py
- examples/cython/sycl_buffer/setup.py
- examples/cython/sycl_direct_linkage/_buffer_example.pyx
- examples/cython/sycl_direct_linkage/setup.py
- examples/cython/usm_memory/run.py
- examples/cython/usm_memory/setup.py
- examples/pybind11/external_usm_allocation/example.py
- examples/python/device_selection.py
- examples/python/dppy_kernel.py
`conda-packages.yaml` workflow add a step to build and run dpctl/examples on Linux.
This PR is to incorporate exercising examples to make sure that they are not broken by future changes.
> A step added to build/run examples

- .github/workflows/cpp_style_checks.yml
Also check "dpctl/apis" folder, containing header files.
> cpp_style_check workflow use ubuntu 20.04

- setup.py
Remove declaration for support for Python 3.6, added declaration of support for Python 3.9
> Updated setup's classifiers keyword argument

- dpctl/_backend.pxd
- dpctl/_sycl_event.pyx
- dpctl/_sycl_queue.pyx
- dpctl/memory/_memory.pyx
`DPCTLQueue_Wait` and friends are declared nogil, and their use
is moved into `with nogil` context.
This allows us to use `sycl::host_task` to manipulate reference count on a Python object without introducing a deadlock.
Since USM allocation functions are also synchronous and can take some time for 
large allocations, we release GIL for them too. We may perhaps revisit this in the future, only release GIL for large enough allocations.
> Synchronization functions and USM allocations functions release GIL

- libsyclinterface/source/dpctl_sycl_device_manager.cpp
This is replicating the logic of `get_devices` and works where `get_num_devices` crashes.
> DPCTLDeviceMgr_GetNumDevices should not operate on rejected devices

- .github/workflows/conda-package.yml
Before running pytest, run a smoke test checking that 
1. package can be imported
2. executing `dpctl.lsplatform()` to show the platform configuration as seen by dpctl.
> Added smoke step for testing_${{ platform }} jobs

- libsyclinterface/source/dpctl_sycl_device_manager.cpp
If exception ocurred, error handler is invoked, and the ``sycl::device``->``sycl::context``
map is not cached. 
``std::terminate`` call was removed (dead code).
> DeviceCache builder uses try/catch

- .github/workflows/conda-package.yml
Set the environment instead of creating hard links
> Set TBB_DLL_PATH rather than create hard links in the environment

- libsyclinterface/CMakeLists.txt
It should use `CMAKE_CURRENT_SOURCE_DIR` rather than `CMAKE_SOURCE_DIR` to work correctly if included as subdirectory from upper level.
> libsyclinterface/CMakeLists.txt should use CMAKE_CURRENT_SOURCE_DIR

- README.md
Adds a badge to the README that indicates if the generate-docs workflow succeeded for `master`.
> Add a badge indicating status of sphinx generation

- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pyx
- dpctl/_sycl_event.pyx
- dpctl/_sycl_queue.pyx
- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/apis/include/dpctl_capi.h
- dpctl/memory/_memory.pyx
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_queue.py
- dpctl/tests/test_sycl_usm.py
- dpctl/tests/test_usm_ndarray_ctor.py
This expands Python C-API public functions to work with memory objects. 
What is missing is  pybind11 casters.
> Memory api

- .github/workflows/python_style_checks.yml
- .pre-commit-config.yaml
- dpctl/tests/test_sycl_event.py
- examples/cython/sycl_buffer/bench.py
- examples/cython/sycl_direct_linkage/bench.py
- examples/cython/usm_memory/run.py
- examples/pybind11/use_dpctl_syclqueue/example.py
- examples/python/usm_memory_host_access.py
Updated version of black used in workflow and pre-commit. 
Modified files black thinks need tweaking.
> Use black@stable, bring source to black compliance

- dpctl/tests/test_service.py
If `mkl_ver >= dpcpp_ver` is detected, the test is xfailed, rather than failed.
This should side-step failing in internal CI where newer compiler may be used with older library.
> test_dpcpp_version is made non-failing

- dpctl/CMakeLists.txt
- dpctl/_host_task_util.hpp
- dpctl/_sycl_event.pyx
- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_kernel_submit.py
Added `dpctl/_host_task_utils.hpp` file that provides function to
submit `host_task` to decrement reference counts for each
Python object passed to one, gated by passed event references.
Host task is submitted to ``sycl::queue`` behind the `QRef` argument.
`dpctl.SyclQueue.submit` changes the mechanism by which it ensures that
Python objects (and memory they hold) that the kernel works on
are not GC collected before the kernel completes its execution.
We used to store reference to arguments in the `dpctl.SyclEvent` object
returned by `SyclQueue.submit`. To avoid GC-ing kernel arguments
before kernel completes execution, deleter of `SyclEvent` has to
call `SyclEvent.wait`.
With this PR `SyclQueue.submit` increments reference counts of
arguments after submission, then schedules a host task …
> SyclEvent deleter no longer waits

- .flake8
- CONTRIBUTING.md
- dpctl/_dev.pyx
- dpctl/_diagnostics.pyx
- dpctl/tests/test_service.py
- libsyclinterface/CMakeLists.txt
- libsyclinterface/helper/source/dpctl_error_handlers.cpp
- libsyclinterface/include/dpctl_service.h
- libsyclinterface/source/dpctl_service.cpp
- scripts/build_backend.py
- scripts/build_locally.py
This PR contains the primary implementation of using GLog in dpctl.
The implementation used Glog 5.0
`conda install glog`
Added the `--glog` flag for setup in development mode
`python setup.py develop --glog=True`
Implemented 2 functions for initialization and deinitialization of GLog
`void DPCTLService_InitLogger` and `void DPCTLService_ShutdownLogger`
> Implementation of GLog

- scripts/build_locally.py
This PR adds Windows OS support for build_locally.py and adds a command line argument `--dubug` to change the compilation mode
> Update build_locally.py for Windows support and compilation mode selection

- dpctl/tensor/_reshape.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Fixes #729
The generated reshaped_strides routine is meant for non-empty arrays,
and so empty ones must be handled differently.
Tests added as well.
> Fix for errors reported in #729 when reshaping 0-elems array

- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_queue.py
- libsyclinterface/helper/include/dpctl_string_utils.hpp
- libsyclinterface/helper/source/dpctl_error_handlers.cpp
- libsyclinterface/helper/source/dpctl_utils_helper.cpp
- libsyclinterface/include/dpctl_sycl_enum_types.h
- libsyclinterface/source/dpctl_sycl_context_interface.cpp
- libsyclinterface/source/dpctl_sycl_device_interface.cpp
- libsyclinterface/source/dpctl_sycl_device_manager.cpp
- libsyclinterface/source/dpctl_sycl_device_selector_interface.cpp
- libsyclinterface/source/dpctl_sycl_event_interface.cpp
- libsyclinterface/source/dpctl_sycl_kernel_interface.cpp
- libsyclinterface/source/dpctl_sycl_platform_interface.cpp
- libsyclinterface/source/dpctl_sycl_platform_manager.cpp
- libsyclinterface/source/dpctl_sycl_program_interface.cpp
- libsyclinterface/source/dpctl_sycl_queue_interface.cpp
- libsyclinterface/source/dpctl_sycl_queue_manager.cpp
- libsyclinterface/source/dpctl_sycl_usm_interface.cpp
- libsyclinterface/source/dpctl_vector_templ.cpp
- libsyclinterface/tests/test_helper.cpp
- libsyclinterface/tests/test_sycl_device_aspects.cpp
- libsyclinterface/tests/test_sycl_device_subdevices.cpp
- libsyclinterface/tests/test_sycl_queue_interface.cpp
Clean up for `#includes`, replacing use of `#include "../helper/include/header.h"` with `#include "header.h"`, since include directories already point to `../header/include`.
Replaced deprecated sycl declarations with their intended replacements:
```c++
sycl::backend::level_zero -> sycl::backend::ext_oneapi_level_zero
sycl::queue::barrier -> sycl::queue::ext_oneapi_barrier
sycl::aspect::usm_system_allocator -> sycl::aspect::usm_system_allocations
````
Also removed uses of reprecated `sycl::runtime_error` in favor of use of `sycl::exception`.
Because of deprecation of `sycl::aspect::usm_system_allocator`, changed the name of dpctl enum entry name accordingly, which is a user visible change.
> Cleanup: sycl deprecation warnings, includes

- dpctl/apis/include/dpctl4pybind11.hpp
Fixes #748 
Move all Pybind11 type casters into single namespace declaration.
> Remove redundant namespace scopes.

- .github/workflows/generate-docs.yml
- docs/CMakeLists.txt
- docs/README.md
- scripts/build_locally.py
- scripts/gen_coverage.py
- scripts/gen_docs.py
Modifications to the CMakeLists.txt inside docs and integrate it to build from top-level CMakeLists.txt.
Add a helper scripts to generate docs.
Closes https://github.com/IntelPython/dpctl/issues/759
> Add a script to generate documentation using new Cmake infrastructure 

- dpctl/tensor/_usmarray.pxd
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Made type constants (e.g `UAR_DOUBLE`) and flags (e.g. `USM_ARRAY_C_CONTIGUOUS`) API symbols as well, so that
pybind11 extensions can use them.
`UsmNDArray_GetOffset` api function added to API, and a test added to excercise it.
> usm_ndarray API extended by GetOffset function

- dpctl/apis/include/dpctl4pybind11.hpp
pybind11 type_caster for SyclQueue/SyclDevice convert None to default constructed instances
This automates interpretation of None as default-selected device/queue in pybin11 functions.
> pybind11 type caster to sycl::queue, sycl::device handle None

- dpctl/tensor/_copy_utils.py
To intervals `[B1..E1)` and `[B2..E2)` do not overlap when
`E1 <= B2 || E2 <= B1` <=> `B1 >= E2 || B2 >= E1`.
The typo in the code was the reason why the coverage was jumping
around.
The overlap may occur only if `(B1 < E2) and (B2 < E1)`.
> Fixed type in utility `_memory_overlap`.

- setup.py
`extra_require` renamed to `extras_require`.
This resolves one of `dist.py:274: UserWarning: Unknown distribution option` see during building.
> fixed typo in setup call: extra_require->extras_require

- dpctl/_host_task_util.hpp
This PR applies the solution worked out in a toy POC
Host tasks are executed in a separate threads from
the main thread which submitted the kernel and incremented
reference counts.
When kernel submission occurs near the end of the script,
the CPython interpreter may have begun finalization process
by the time the kernel completes the execution.
`PyThread_Ensure` would crash in that case. So execute the host
task only if `Py_IsInitialized()`.
The only testing of this scenario is to submit the kernel at
the end and not call queue synchronization.
> Only call PyThread_Ensure from host_task if the main-thread interpreter is initialized

- dpctl/tensor/_usmarray.pyx
Since `dpnp.positive` is not implemented, to unblock integration testing implemented ``usm_ndarray.__pos__`` to return self.
> operator.pos(ums_ndarray) is always an identity

- dpctl/tests/test_service.py
- versioneer.py
This change makes changes to the versioneer.py installed into the codebase. 
Versioneer 0.21 added escape character to the match option of git
describe. 
> * FIX: Escape asterisk in `git describe` call on Windows, see python-versionseer/python-versioneer#262
Similar change was made upstream too: 
https://github.com/python-versioneer/python-versioneer/pull/283/files
but it has been made it into the released version yet.
```
(base) C:\Users\opavlyk\devel\dpctl>git describe --tags --dirty --always --long --match "\*"
3bd37749
(base) C:\Users\opavlyk\devel\dpctl>git describe --tags --dirty --always --long --match "\\*"
3bd37749
(base) C:\Users\opavlyk\devel\dpctl>git describe --tags --dirty --always --long --match "*"
0.12.0dev3-33-g3bd37749
```
> [FIX] versioneer 0.21 regression fixed in vendored file

- .github/workflows/generate-docs.yml
- docs/generate_rst.py
- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds permute_dims functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.permute_dims.html) for usm_ndarray.
Moved from #786
> Implementation of permute_dims function

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `expand_dims` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.expand_dims.html) for usm_ndarray.
> Implementation of expand_dims function

- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR reuses `normalize_axis_tuple` function from `numpy.core.numeric` instead instead of `_check_value_of_axes` and fixes test_permute_dims_0d_1d.
> Fix dpct.tensor.permute_dims function

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `squeeze` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.squeeze.html) for usm_ndarray.
> Implementation of squeeze function

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `broadcast_to` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.data_type_functions.broadcast_to.html) for usm_ndarray.
> Implementation of broadcast_to function

- dpctl/tensor/_copy_utils.py
Using `ze_tracer` from pti-gpu/ repo reported two kernel calls for every setitem call. 
Missing `return` was the culprit
> [BUGFIX] Excessive number of copy kernel calls

- dpctl/tensor/_device.py
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_utils.py
- dpctl/utils/__init__.py
- dpctl/utils/_compute_follows_data.pyx
Adds `dpctl.utils.get_coerced_usm_type` to deduce the usm type for the output array based on usm types of input arrays.
Also modified behavior of `dpctl.utils.get_execution_queue`. The notion of equivalency has changed. Now two queues are equivalent if they compare equal, i.e. `q1 == q2`. This is true when the underlying C++ class instances are copies of the same underlying instance.
Note that `dpctl.SyclQueue() == dpctl.SyclQueue()` returns `False`, and so would `dpctl.SyclQueue("cpu") == dpctl.SyclQueue("cpu")`.
To bring two arrays to equivalent queues, do `Yc = Y.to_device(X.device)`, and then `foo(X, Yc)` if `foo(X, Y)` was raising due to incompatible queues.
> Get coerced usm type

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `broadcast_arrays` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.data_type_functions.broadcast_arrays.html) for usm_ndarray.
> Implementation of broadcast_arrays function

- dpctl/tensor/CMakeLists.txt
Thanks the compiler team for pointing this out.
Now, envoking copy kernels for different types calls JIT-ting as evidenced by
```
(idp_2022) [14:54:46 ansatnuc04 dpctl]$ SYCL_PI_TRACE=-1 python -c "import dpctl.tensor as dpt; print(dpt.__file__); X = dpt.empty(10, 'd'); Y = dpt.empty(10, 'i4'); X[:] = Y; X1 = dpt.empty(10,'f4'); X1[:] = Y" >& pi_trace.txt
(idp_2022) [14:54:55 ansatnuc04 dpctl]$ grep -c piProgramCreate pi_trace.txt
2
```
Previously the output was 1 (all 14*14 kernels were compiled all at once which was slower)
on the first invocation.
> -fsycl-device-code-split=per_kernel must be passed to linker, not compiler

- dpctl/_backend.pxd
- dpctl/_sycl_platform.pyx
- libsyclinterface/include/dpctl_sycl_platform_manager.h
- libsyclinterface/source/dpctl_sycl_platform_manager.cpp
- libsyclinterface/tests/test_sycl_platform_interface.cpp
Closes #796 
This PR changes `DPCTLPlatformMgr_PrintInfo` function to return `char *` instead of outputting it in `libsyclinterface` , and use that to print using CPython.
> Fix dpctl.lsplatform() to output in jupyter notebook

- .pre-commit-config.yaml
Updated `.pre-commit-config.yaml` to use black 22.3.0 to work around a breaking change in a dependent `click`.
See https://github.com/psf/black/issues/2964#issuecomment-1080974737
> Update black to version 22.3.0 to fix issue with click

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `flip` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.flip.html) for usm_ndarray.
> Implementation of flip function 

- .github/workflows/conda-package.yml
Like we in test_run scripts in conda recipe, we should be disabling faulthandler plugin of pytest enabled in 5.1 to resolve some sporadic unreproducible crashes.
> Disable faulthandler plug-in for pytest

- dpctl/tensor/_reshape.py
- dpctl/tests/test_usm_ndarray_ctor.py
reshape function acquired `copy` keyword argument:
https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.reshape.html
> Add copy keyword argument to reshape

- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds `roll` functions according to [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.roll.html) for usm_ndarray.
> Implementation of roll function

- CMakeLists.txt
- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tensor/_reshape.py
- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tensor/libtensor/tests/test_copy.py
- dpctl/tests/test_sycl_event.py
This PR implements specialized flat-view-like copying between two same type arrays.
```python
_tensor_impl._copy_usm_ndarray_for_reshape(
src = X,    # required: usm_ndarray
dst = Y,    # required: usm_ndarray
shift = offset,  # required: ssize_t
sycl_queue = q,  # required: dpctl.SyclQueue
depends = []     # optional: list of dpctl.SyclEvent
)
```
`X`, and `Y` have the same data type, and the same number of elements.
Equivalent to
```python
for i in range(src.size):
dst_ind = np.multi_index((i + shift) % src.size, dst.shape)
src_ind = np.multi_index(i, src.shape)
dst[dst_ind] = src[src_ind]
```
For `shift == 0` this is used for reshape where a copy is needed (for default order='C'), 
and for general shift this is used in implementation of `dpctl.tensor.roll`.
The function has been …
> Milestone: copy_usm_ndarray_for_reshape implemented and deployed

- .github/workflows/generate-coverage.yaml
- scripts/gen_coverage.py
Those are internal, lengthy tests and do not contribute to coverage report.
> Generate coverage should ignore tests from dpctl/tensor/libtensor/tests

- libsyclinterface/include/dpctl_sycl_queue_interface.h
- libsyclinterface/source/dpctl_sycl_queue_interface.cpp
- libsyclinterface/tests/test_sycl_queue_interface.cpp
This PR:
1. Implements of `DPCTLQueue_Memset` function.
2. Adds test to 'libsyclinterface/tests' to test this function.
> Implementation of memset function in libSyclInterface 

- dpctl/_backend.pxd
- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
- dpctl/tests/test_sycl_usm.py
`obj.memset()` fills object with zero bytes.
`obj.memset(val)` fills object with given value (expected to fit in
`unsigned short` type)
> Hooked up _Memory.memset() method

- dpctl/tensor/__init__.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tests/test_usm_ndarray_manipulation.py
- dpctl/tests/test_utils.py
- dpctl/utils/__init__.py
- dpctl/utils/_compute_follows_data.pyx
Adds implementation of `dpctl.tensor.arange` per [array API spec](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.arange.html).
Also adds a kernel to be later used for implementation of `linspace` function of the spec.
Adds a test.
> Add arange function

- dpctl/tensor/__init__.py
- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Implements `zeros` from [array-API specs](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.zeros.html):
```python
import dpctl
import dcptl.tensor as dpt
X = dpt.zeros(30, dtype='f4', device="gpu")
```
> Adding dpctl.tensor.zeros

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/libtensor/source/tensor_py.cpp
- setup.py
Added an implementation of dedicated copy-with-casting routine to copy from numpy's ndarray to usm_ndarray.
Deployed in in `_copy_utils`, which automatically uses it in `__setitem__`.
> Copy from ndarray

- examples/pybind11/onemkl_gemv/CMakeLists.txt
- examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp
Also made libraries required, removed use of target_link_directories
> onemkl_gemv example: fixed typos in find_library call arguments PATH->PATHS

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp
used that in `tensor_py.cpp` and `onemkl_gemv` example.
> Exported keep_args_alive to dpctl4pybind11

- dpctl/_sycl_event.pxd
- dpctl/_sycl_event.pyx
- dpctl/_sycl_queue.pyx
This used to solve the problem of keeps Python arguments that
SYCL kernels work on to stay "alive" for the duration of kernel
execution.
This mechanism was them changed to use host_task, but args member
was not removed.
This should lower the overhead of constructing/destroying SyclEvent
objects.
> Remove unnecessary arg member of SyclEvent/_SyclEvent classes

- dpctl/_sycl_timer.py
This changes docstring to avoid glitches in formatting:
> Fix docstring for SyclTimer

- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
- libsyclinterface/include/dpctl_sycl_device_interface.h
- libsyclinterface/source/dpctl_sycl_device_interface.cpp
- libsyclinterface/tests/test_sycl_device_interface.cpp
This adds a `DPCTLDevice_GetProfilingTimerResolution` public function to export `device::get_info<info::device::profiling_timer_resolution>()`.
Expose this property to `dpctl.SyclDevice`. Added tests to both SyclInterface library and pytest,
> Profiling timer resolution device property

- dpctl/__init__.py
- dpctl/_device_selection.py
- dpctl/_sycl_context.pyx
- dpctl/_sycl_device.pyx
- dpctl/_sycl_device_factory.pyx
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_queue.py
- examples/python/sycl_queue.py
Changed error type raised on failure to create `SyclDevice`.
It used to be `ValueError`, now `SyclDeviceCreationError` is raised.
Also this error and `SyclSubDeviceCreationError` are now exported to `dpctl` namespace.
Remove incorrect comment  in `sycl_queue.py`.
Adjusted example `sycl_queue` to handle error creating sub-devices.
Lowered the value of partition keyword from 4 to 2
> Raises dedicate exception type of failure to create SyclDevice

- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
There was a typo in one of the assertions, and numerous comparisons between signed and unsigned types.
Recent fix to build_locally.py (#835) uncovered these, and this PR fixes the error and addresses the warnings,
> Fix errors and warnings in asserts

- examples/pybind11/onemkl_gemv/solve.py
- examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp
- examples/pybind11/onemkl_gemv/sycl_gemm/cg_solver.hpp
- examples/pybind11/onemkl_gemv/sycl_timing_solver.py
This PR modifies `pybind11/onemkl_gemv` example by 
- plugging a device memory leak
- fixing `cg_solve` in solve.py to create temporaries using the same allocation queue as input arrays
- renaming C++ variables for clarity in `cg_solver.hpp`
- restructuring `sycl_timing_solver.py` to easily allow to comment out python/cpp portion invocations.
> Refine gemv example

- dpctl/tensor/_usmarray.pyx
This PR fixes extraneous argument in `__lrshift__` special method which was revealed by changes in Cython 0.29.29 and caught by existing tests.
> Removed extraneous argument in __lrshift__ special method

- examples/pybind11/onemkl_gemv/sycl_timing_solver.py
This PR changes the runner script to modularize sections iterating different solvers.
This mostly meant defining functions with proper docstrings and calling them. Now commenting out section testing cpp or python implementation is a one-line change.
> Modularized the examples/pybind11/onemkl_gemv/sycl_timing_solver.py

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/_device.py
- dpctl/tensor/libtensor/source/tensor_py.cpp
Improved efficiency of pybind11 classes and type casters. 
Type casters in pybind11 generated with `PYBIND11_TYPE_CASTER` macro rely on default constructor of C++ type. The default constructed value is then overwritten by `load`  method. C++ types such as `sycl::device` and `sycl::queue` do non-trivial amount of work in default constructor. This work was ranking high in certain workloads (such as `example/pybind11/onemkl_gemv/sycl_timing_solver.py`).
Same applies to auto-generated type-casters for classes `dpctl::memory::usm_memory` and `dpctl::tensor::usm_ndarray`.
This PR introduces DPCTL_TYPE_CASTER macro that defines `unique_ptr` to the C++ type, rather than the type itself. This avoids superfluous call to default constructor altogether.
Instead of redefining `pyobject_caster` …
> Improve type casters

- dpctl/tensor/_ctors.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_usm_ndarray_ctor.py
While modifying tests to use `dpctl.tensor.arange` I encountered exception when starting value was outside of the range of the elemental data-type, e.g. `dpctl.tensor.arange(128, 0, -1, dtype='i1')`.
This PR fixes the issue by coercing the starting point to the elemental data-type scalar. 
A test of `arange` was modified to cover such input. 
Tests in `test_sycl_event` and `test_sycl_kernel_submit` were modified to use `dpctl.tensor.arange` as opposed to using `numpy.arange` and copying the content into a `MemoryUSMShared` allocation.
> Fixed bug in dpctl.tensor.arange, streamlined tests

- dpctl/tests/test_sycl_usm.py
The `dpctl.MemoryUSM*` Python object representing USM allocation are
reconstructed from an object exposing `__sycl_usm_array_interface__`
use USM-pointer queries. When SUAI provides ``sycl::context`` object,
the device is inferred using `get_pointer_device`. For host
allocations this may not need to return the device in the queue used
to make the allocation. It will return the first device in the context
to which the allocation is bound instead (per SYCL 2020 spec).
This change will not affect test suite outcome on configurations where 
platforms only have a single device it them.
> Adjusted test for reconstruction of USM host allocation from SUAI

- conda-recipe/meta.yaml
- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_queue.py
- libsyclinterface/helper/source/dpctl_utils_helper.cpp
- libsyclinterface/include/dpctl_sycl_enum_types.h
- libsyclinterface/tests/test_sycl_device_aspects.cpp
From gh-309 only emulated aspect remains unsupported.
The following aspects from gh-309 are now supported
```c++
sycl::aspect::host_debuggable,
sycl::aspect::atomic64,
sycl::aspect::usm_atomic_host_allocations,
sycl::aspect::usm_atomic_shared_allocations,
```
Removed (due to deprecation in DPC++) aspects are
```c++
int64_base_atomics
int64_extended_atomics
```
----
> Remove deprecated aspects related to atomics, added supported aspects

- CHANGELOG.md
Wrote up all the changes that went into 0.13.* up to gh-847.
Once this is merged in, I intend to tag 0.13.0dev2
> Populated change-log with changes that went into 0.13 so far

- docs/conf.in
- dpctl/_sycl_platform.pyx
Use `sphinx.ext.intersphinx` Sphinx extension to generate inventory of objects in the docs web-page to cross-referencing. 
Also addressed warnings coming from docstring of `dpctl.lsplatform`.
> Include intersphinx extension to generate objects inventory

- examples/python/device_selection.py
- examples/python/filter_selection.py
#826 has modified the type of exception raised when `dpctl.SyclDevice` could not be created from `ValueError` to `dpctl.SyclDeviceCreationError`. 
Python examples were not updated. Hence the output of the script shows errors on the [manual page about device selection](https://intelpython.github.io/dpctl/latest/docfiles/user_guides/manual/dpctl/device_selection.html).
This PR updates two affected Python example files, `device_selection.py` and `filter_selection.py`.
> update expected exception type when creating devices

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
The expected length of `dpt.arange(0,1, 0.25, dtype="f4")` is 4 elements, but old code was constructing array of length 1.
Fixed the logic for computing the length of the array to allocated. Added a test.
> Fixed bug causing dpt.arange(0,1,1e-3,dtype="f4") be length 1

- libsyclinterface/source/dpctl_sycl_kernel_bundle_interface.cpp
In open-source `intel/llvm` location of `<CL/sycl/backend/opencl.hpp>` has been moved to `<sycl/backend/opencl.hpp>`. This PR uses C++17 feature of `__has_include` to keep the code compilable with both older and newer compilers.
> Adjustments to account for changed include location in main trunk of DPC++

- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_sycl_queue_memcpy.py
- libsyclinterface/source/dpctl_sycl_event_interface.cpp
Several changes made during running test suite in WSL on a machine with Iris Xe.
1. Turns out calls to `sycl::event::wait` can throw SYCL exceptions, e.g. `CL_DEVICE_NOT_FOUND` and these need to be intercepted.
2. In the test for `test_sycl_queue_memcpy.py` be explicit about the allocation queue.
3. Since Iris Xe does not natively support double precision type, I added the logic to not submit the kernel built for double precision if the HW does not support it.
> Changes from testing dpctl under wsl on a laptop with Iris Xe

- dpctl/CMakeLists.txt
If the absolute path for `dpctl` checkout contains spaces the lack of quotes around working directory argument to Cython causes trouble. 
This change adds the quotes.
> Using quotes for dpctl/CMakeLists.txt per Anton's feedback

- libsyclinterface/tests/test_sycl_event_interface.cpp
Use of `sycl::noinit` in `libsyclinterface/tests/test_sycl_event_interface.cpp` was producing deprecation warnings during coverage build. 
This change replaces `sycl::noinit` with suggested `sycl::no_init` addressing the warning.
> Fixed stray use of deprecated SYCL-2020 quantifier in dpctl_c_api tests

- dpctl/tests/test_tensor_asarray.py
- dpctl/tests/test_usm_ndarray_ctor.py
Modified test suite to not exercise calls that would result in JIT-compiling kernels with double precision floating point types on hardware such as Intel Iris Xe which does not have HW support for the double precision floating point type.
> Test iris xe part2

- dpctl/apis/include/dpctl4pybind11.hpp
Closes gh-852. 
Getter methods of `dpctl::tensor::usm_ndarray` class are marked as `const`.
> Getter functions for usm_ndarray are marked const per gh-852

- dpctl/_sycl_device.pyx
- dpctl/_sycl_queue.pyx
- dpctl/_sycl_timer.py
- dpctl/tensor/_usmarray.pyx
- libsyclinterface/include/dpctl_service.h
- libsyclinterface/include/dpctl_sycl_kernel_bundle_interface.h
With release of Sphinx 5.1.0 the `dpctl` documentation build started failing due to sphinx-doc/sphinx#10701 with an exception in sphinx.
The exception is tripped by missing or empty docstrings for `property` class attributes as pointed out by @yaricoptic.
Update in Sphinx also revealed two typos in Doxygen annotations which this PR also fixed.
> Fix doc build

- CHANGELOG.md
Expanded CHANGELOG.txt to reflect additions of #853
> expanded changelog with work from gh-853

- cmake/IntelDPCPPConfig.cmake
Added license text to IntelDPCPPConfig.cmake to align it with what's is oneAPI DPC++
No functional changes.
> Added license text to IntelDPCPPConfig.cmake

- libsyclinterface/helper/include/dpctl_utils_helper.h
- libsyclinterface/helper/source/dpctl_utils_helper.cpp
- libsyclinterface/source/dpctl_sycl_device_manager.cpp
- libsyclinterface/source/dpctl_sycl_platform_manager.cpp
SYCLInterface library functions used `std::to_string(sycl::backend d.get_platform().get_backend())` to produce backend section of the filter selector.  Correspondingly they produced invalid strings like `"ext_oneapi_level_zero:gpu:0"` where `"level_zero:gpu:0"` was expected.
---
For example, now:
```
Platform  3 ::
Name        Intel(R) Level-Zero
Version     1.3
Vendor      Intel(R) Corporation
Backend     ext_oneapi_level_zero
Num Devices 1
Name                Intel(R) UHD Graphics [0x9bca]
Version             1.3.23750
Filter string       level_zero:gpu:0
```
While previously the filter string was "ext_oneapi_level_zero:gpu:0".
Similar change for print_device_info:
```
$ SYCL_FILTER_SELECTOR=level python -c "import dpctl; dpctl.SyclDevice().print_device_info()"
Name            Intel(R) …
```
> Fixed filter-selector-string output by lsplatform and print_device_info

- CHANGELOG.md
- dpctl/tensor/__init__.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
stack() function joins a sequence of arrays along a new axis and follows [array API spec](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.stack.html#signatures.manipulation_functions.stack).
> Added dpctl.tensor.stack feature and tests

- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tests/test_usm_ndarray_ctor.py
The utilities that maps array's `typenum` to `type_id` for function pointer look-up need to understand not only computed disjoint types, but only shadowed types which are not mapped to the disjoin types.
```python
import dpctl.tensor as dpt, numpy as np
dpt_dst = dpt.empty((10,), dtype=np.int32)
dpt_dst[:] = np.arange(10, dtype='intc')   # used to raise RuntimeError of unrecognized 
```
Test added.
> Type dispatch fix

- CMakeLists.txt
- examples/pybind11/external_usm_allocation/CMakeLists.txt
- examples/pybind11/onemkl_gemv/CMakeLists.txt
- examples/pybind11/use_dpctl_syclqueue/CMakeLists.txt
This PR updates pybind11 from 2.9.2 to 2.10.0
> Updated pybind11 from 2.9.2 to 2.10.0

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_manipulation.py
The kernel implementing `dpctl.tensor.linspace` uses `double` precision temporary variable causing issues when running on HW without double precision support.
This PR changes the kernel to use `float` type on such hardware. 
It also changes how copying of double precision numpy array to device w/o DP HW support works. 
The array is cast to single precision on host before kernel is launched.
Tests are modified so that test suite now passes on Iris Xe integrated card.
> Linspace should not use double type unconditionally

- .github/workflows/conda-package.yml
- dpctl/_sycl_platform.pyx
- examples/c/py_sycl_ls/py_sycl_ls/__init__.py
- examples/c/py_sycl_ls/py_sycl_ls/__main__.py
- examples/c/py_sycl_ls/setup.py
- examples/c/py_sycl_ls/src/py_sycl-ls.c
- examples/c/py_sycl_ls/tests/test_sycl_ls.py
- examples/cython/sycl_buffer/setup.py
- examples/cython/sycl_buffer/use_sycl_buffer.cpp
- examples/cython/sycl_direct_linkage/setup.py
- examples/cython/sycl_direct_linkage/sycl_function.cpp
- examples/cython/usm_memory/setup.py
- libsyclinterface/include/dpctl_sycl_device_interface.h
One of DPCTLSyclInterface function was deprecated in #876, and `__attributes__((deprecated(what, repl))` was used.
This broke building of C extensions using the library. This PR uses `[[deprecated(msg)]]` instead, which is understood by both the gcc and icx.
An example of native Python extension written in C and that is using DPCTLSyclInterface is added. It is being compiled in the workflow `conda-package.yml` workflow when testing that examples can be compiled on Linux.
Incidentally, `dpctl.lsplatform` implementation replaced informational `print` with seemingly more appropriate use of `warnings.warn`.
@mingjie-intel
> Fix c interface

- .github/workflows/os-llvm-sycl-build.yml
- dpctl/tensor/_ctors.py
- dpctl/tests/test_tensor_asarray.py
This PR addresses a test failure in `dpnp` caused by lack of data-type checking in `dpctl.tensor.asarray(numpy_array)`.
```python
import numpy as np, dpctl.tensor as dpt
dpt.asarray(np.array([1,2,3], dtype=object)) # now raises TypeError
```
> dpctl.tensor.asarray must check numpy array data-type

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_manipulation.py
- dpctl/tests/test_usm_ndarray_operators.py
This is the set of changes that get test suite to run clean on Iris Xe hardware.
Also removed stray print statement in the test for stack_2d. Improved exception text for `usm_ndarray`.
The test suite was run as follows from within WSL:
```bash
for f in $(find dpctl/tests -name "test_*.py" -type f); do python -m pytest ${f}; done
```
using [NEO 23852](https://github.com/intel/compute-runtime/releases/tag/22.31.23852).
> Tests on iris xe

- dpctl/tensor/libtensor/source/tensor_py.cpp
static_cast to void pointer from char pointer in calls to memcpy to appease klocwork scanner
> Work around false positive in klockwork report

- .github/workflows/conda-package.yml
- dpctl/apis/include/dpctl4pybind11.hpp
`conda-package.yml` workflow used different orders of channels specified to `conda` during building and during testing which might be causing action failures experienced in #893 and #894
> Fix conda-package workflow

- dpctl/_sycl_device.pyx
Improved exception message when SyclDevice could not created from invalid filter string. Closes #891
```
In [2]: dpctl.SyclDevice("invalid")
SyclDeviceCreationError                   Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 dpctl.SyclDevice("invalid")
File ~/repos/dpctl/dpctl/_sycl_device.pyx:295, in dpctl._sycl_device.SyclDevice.__cinit__()
293             ret = self._init_from_selector(DSRef)
294             if ret == -1:
--> 295                 raise SyclDeviceCreationError(
296                     "Could not create a SyclDevice with the selector string "
297                     "'{selector_string}'".format(selector_string=arg)
SyclDeviceCreationError: …
```
> Addressed gh-891, improved SyclDevice ctor error message

- libsyclinterface/include/dpctl_sycl_device_interface.h
Changed `libsyclinterface/include/dpctl_sycl_device_interface.h` to only use `[[deprecated("msg")]]` annotation for C++ builds.
This fixes build of numba-dpex's native extension. This remained broken despite claim to the contrary in #879.
@mingjie-intel
> Use [[deprecated("msg")]] annotation only for C++ builds

- .github/workflows/conda-package.yml
PR #881 as a new PR, fixing duplicate commits
> Array API conformity test added

- .github/workflows/conda-package.yml
Since array API conformance statistics messages allow repetitions, include full conda package version and build number in the message to differentiate multiple results posted to the PR.
> Annotate array-API conformance messages with dpctl version data

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tests/test_usm_ndarray_ctor.py
This introduces `dpctl::utils::queues_are_compatible(exec_q, {alloc_q1, alloc_q2, ...})` and deploys it in `tensor_py.cpp`.
The check replaces notion of compatibility from queues have equal contexts to queues are equal, aligning check with the logic in `_compute_follows_data.pyx`.
Furthermore, this PR implements optimization for transfer of shape/strides from host-allocated metadata to kernels.
Previously, transfer was done with 3 or 4 calls to `exec_q.copy`. It is replaced with allocation of host temporary where necessary `std::copy` calls are made to populate it, followed by a single call to `exec_q.copy` to copy data into USM allocation for use in kernel. 
No other logic has changed.
> Improve queue compatibility testing

- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_dlpack.py
If `stream` keyword argument has type `dpctl.SyclQueue`, then submit a barrier into `self.sycl_queue`, and than submit another barrier into stream with dependency on the event returned by submission of the barrier into `self.sycl_queue`:
```python
ev = self.sycl_queue.submit_barrier()
stream.submit_barrier(dependent_events=[ev])
```
All other types of stream are ignored, in particular integer values of stream.
-- 
With this PR, MPI transfer of `usm_ndarray` allocated using level-zero backend becomes possible:
```python
from mpi4py import MPI
import numpy as np
comm = MPI.COMM_WORLD
rank = comm.Get_rank()
if rank == 0:
data = dpt.arange(100, dtype="float64")
comm.Send(data, dest=1, tag=13)
elif rank == 1:
data = dpt.empty(100, dtype="float64")
comm.Recv(data, …
```
> Added support for stream other than None

- dpctl/tests/_device_attributes_checks.py
Improved `check_max_work_item_sizes` to use `pytest.warns` context manager instead of `pytest.marks.filterwarnings` decorator.
This is better since it assers that warning is issues, and filters it out, so test run of `test_sycl_device.py` is green, rather than darker-yellow.
> Use pytest.warns instead of fixure filterwarning

- dpctl/tests/test_utils.py
- dpctl/utils/__init__.py
- dpctl/utils/_onetrace_context.py
This PR adds implementation of `onetrace_enabled` context manager to `dpctl.utils` namespace.
Example of usage:
```
(dev_dpctl) opavlyk@opavlyk-mobl:~/repos/dpctl$ ~/pti-gpu/tools/onetrace/build/onetrace --conditional-collection -v -t --demangle ipython
Device Timeline: start time (CLOCK_MONOTONIC_RAW) [ns] = 207284739877222
Device Timeline: start time (CLOCK_MONOTONIC) [ns] = 207284790110055
Device Timeline: start time (CLOCK_REALTIME) [ns] = 1662686020459161393
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import dpctl.tensor as dpt, dpctl, numpy as np
Device Timeline: start time (CLOCK_MONOTONIC_RAW) [ns] = 207294358012969
Device Timeline: start time …
```
> Adding onetrace_enabled

- dpctl/tensor/__init__.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tests/test_usm_ndarray_ctor.py
`tril()` function returns the lower triangular part of a matrix (or a stack of matrices) x and follows array [API spec](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.tril.html?highlight=tril).
`triu()` function returns the upper triangular part of a matrix (or a stack of matrices) x and follows array [API spec](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.triu.html?highlight=triu)
> Added dpctl.tensor.tril and dpctl.tensor.triu feature

- .github/workflows/os-llvm-sycl-build.yml
Since some sycl-nightly tags do no thave associated binaries attached the workflow was failing.
This commit enhances the download logic to go through recent tags until one is where where binary file is available.
> Fix os-llvm-sycl-build workflow

- dpctl/tensor/libtensor/source/tensor_py.cpp
Change to use USM-host allocation for packed shape/strides on the host. 
USM-host allocations take less time to copy them into USM-device allocations.
The difference is going to be especially pronounced on discrete GPU devices.
> Improve performance of array metadata transfer to device

- examples/cython/sycl_buffer/README.md
- examples/cython/usm_memory/README.md
- examples/pybind11/onemkl_gemv/README.md
This PR corrects markdown formatting  tags for headings.
> Update README.md title extension for examples

- scripts/build_locally.py
Added support for --cmake-opts option inspired by LLVM configure script. This can be used to experiment with adding of additional options to cmake. For example, to try gold linker I used
```
python scripts/build_locally.py --cmake-opts="-DCMAKE_EXE_LINKER_FLAGS=-use-gold-plugin -DCMAKE_CXX_FLAGS=-flto"
```
> scripts/build_locally.py now supports --cmake-opts option

- dpctl/memory/_memory.pxd
Declaration of `MemoryUSMDevice` class was missing `api` qualifier in `_memory.pxd`.
> Add missing api keyword in declaration of MemoryUSMDevice class

- dpctl/tensor/__init__.py
- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Implements dpctl.tensor.meshgrid constructor which returns a matrix of coordinates. Implemented as per [array API standard](https://data-apis.org/array-api/latest/API_specification/generated/signatures.creation_functions.meshgrid.html).
> Implemented dpctl.tensor.meshgrid and tests

- .flake8
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/_flags.pyx
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Reworks usm_ndarray.flags to return a dpctl.tensor._flags object, which streamlines checking flags, such as array memory order and if it's writable.
e.g., for an array X, X.flags now prints the truth values of the currently implemented flags: C-contiguous, F-contiguous, and Writable, while X.flags.forc returns True if one of C-contiguous and F-contiguous is true, and False otherwise.
Note: this will fail the flake8 style guide check as flake8 does not recognize 'cimport' in _flags.pyx as valid syntax.
> Implements dpctl.tensor._flags

- dpctl/tensor/__init__.py
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_sycl_kernel_submit.py
- dpctl/tests/test_tensor_asarray.py
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_manipulation.py
This PR adds data type objects to `dpct.tensor` namespace, specifically
```
dpctl.tensor.bool
dpctl.tensor.int8
dpctl.tensor.uint8
dpctl.tensor.int16
dpctl.tensor.uint16
dpctl.tensor.int32
dpctl.tensor.uint32
dpctl.tensor.int64
dpctl.tensor.uint64
dpctl.tensor.float16
dpctl.tensor.float32
dpctl.tensor.float64
dpctl.tensor.complex64
dpctl.tensor.complex128
```
This also adds `dpctl.tensor.iinfo` and `dpctl.tensor.finfo`. These are directly imported from `numpy`.
> Exported data types, finfo and iinfo symbols

- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
- dpctl/tensor/_flags.pyx
- dpctl/tensor/_stride_utils.pxi
- dpctl/tensor/_usmarray.pxd
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
Instances of writeable have been changed to writable throughout dpctl
Closes #924 
Docstrings have been added to _flags.pyx. They are currently only user-accessible by calling help(flags) where flags is an instance of dpctl.tensor.Flags.
Closes #927
> Changed instances of writeable to writable, added docstrings to _flags.pyx

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/apis/include/dpctl_capi.h
- dpctl/tensor/libtensor/include/kernels/constructors.hpp
- dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp
- dpctl/tensor/libtensor/include/utils/type_utils.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
This PR moves out implementations of implementation kernels into separate header files.
This PR is the first of the series of smaller PRs separated from #923.
> Moved implementation of kernels out to dedicated header files.

- .github/workflows/conda-package.yml
- .github/workflows/cpp_style_checks.yml
- .github/workflows/generate-coverage.yaml
- .github/workflows/generate-docs.yml
- .github/workflows/os-llvm-sycl-build.yml
- .github/workflows/pre-commit.yml
- .github/workflows/python_style_checks.yml
Chore: updated action versions to pick up update from EOL node-12 to node-16.
> Updated actions per prompt from Github

- dpctl/.gitignore
- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
Introduced `dpctl::tensor::usm_ndarray::is_c_contiguous` and `dpctl::tensor::usm_ndarray::is_f_contiguous` and used them in `tensor_py.cpp`.
Modularized common operation of retrieving `PyUSMArrayObject *` into a private method and used it in methods of `dpctl::tensor::usm_ndarray`.
Got rid of global variable `static dpctl::tensor::detail::usm_ndarray_types array_types` in `tensor_py.cpp`. Since the type implements singleton, call its `get()` method at each use site.
> [cleanup/tensor, part 2] Modularized tests for contiguity, retrieval of PyUSMArrayObject* and removed use of a global variable.

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
This PR creates `dpctl::detail::dpctl_capi` singleton class that load Cython-generated CAPI functions implemented in Cython modules of dpctl, and re-exports them as class members. 
This PR removes another singleton `dpctl::tensor::detail::usm_ndarray_types` which is not a simple struct with trivial constructor.
This moves all initialization of static variables exported and implemented by Python into a single place, thus avoiding static order initialization fiasco.
> [cleanup/tensor, step 3] Implement dpctl_capi loader in dpctl4pybind11 header file

- dpctl/tensor/libtensor/include/utils/strided_iters.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
Code for `contract_iter` and `contract_iter2` functions in "strided_iters.hpp" used identifiers from `::pybind11` namespace.
Made these functions templated passing necessary types via template parameters.
This is avoid using py::value_error and py::ssize_t and py::type_error in there explicitly.
Use in "tensor_py.cpp" has been adjusted.
> [cleanup/tensor, part 4] Made contract_iter and contract_iter2 functions templated to avoid needing to include pybind11 headers

- dpctl/tensor/CMakeLists.txt
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.hpp
- dpctl/tensor/libtensor/source/copy_for_reshape.cpp
- dpctl/tensor/libtensor/source/copy_for_reshape.hpp
- dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp
- dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.hpp
- dpctl/tensor/libtensor/source/device_support_queries.cpp
- dpctl/tensor/libtensor/source/device_support_queries.hpp
- dpctl/tensor/libtensor/source/eye_ctor.cpp
- dpctl/tensor/libtensor/source/eye_ctor.hpp
- dpctl/tensor/libtensor/source/full_ctor.cpp
- dpctl/tensor/libtensor/source/full_ctor.hpp
- dpctl/tensor/libtensor/source/linear_sequences.cpp
- dpctl/tensor/libtensor/source/linear_sequences.hpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tensor/libtensor/source/triul_ctor.cpp
- dpctl/tensor/libtensor/source/triul_ctor.hpp
This PR moves each Python function definition and the initialization of function pointer tables/vectors used in `tensor_py.cpp` into dedicated `.cpp` files. Definitions reside in `dpctl::tensor::py_internal` namespace.
Going forward, adding a new function to `dpctl.tensor._tensor_impl` would involve:
- creating new `.cpp` and `.hpp` file with implementation and declarations
- adding the new `.cpp` to list of sources in "dpctl/tensor/CMakeLists.txt"
- registering Python method implementation and using initialization code in "tensor_py.cpp"
---
> [cleanup/tensor, part5] Moved implementation of every Python binding into separate translation unit

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Fixed issue #948  in asarray_from_numpy for uint64 dtype. And changed call copy_to function
> Fixed issue in asarray_from_numpy for uint64 dtype. 

- examples/pybind11/external_usm_allocation/README.md
- examples/pybind11/external_usm_allocation/external_usm_allocation/_usm_alloc_example.cpp
- examples/pybind11/onemkl_gemv/CMakeLists.txt
- examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp
- examples/pybind11/onemkl_gemv/tests/test_gemm.py
- examples/pybind11/use_dpctl_syclqueue/use_queue_device/_example.cpp
This PR modifies examples `examples/pybind11` to account for changes in dpctl4pybind11. 
Specifically, one no longer needs to do `import_dpctl()` at the start of the initialization, since type casters do that through use of `dpctl_capi` singleton.
> Adjust examples for changes in dpctl4pybind11

- dpctl/tensor/_ctors.py
- dpctl/tests/test_tensor_asarray.py
Within compute follows data programming model, we recommend explicit migration of inputs to the same allocation queue.
This is to be done using `usm_ndarray.to_device` method, or with `dpctl.tensor.asarray` operation. This operation until this commit was not able to migrate data across devices.
This commit adds such an ability by copying via host.
Test was added.
> dpt.asarray can now migrate arrays across devices

- libsyclinterface/CMakeLists.txt
Running the documentation generation workflow I encountered the following compilation warnings:
```
icpx: warning: Note that use of '-ggdb3' without any optimization-level \
option will turn off most compiler optimizations similar to use of \
'-O0' [-Wdebug-disables-optimization]
```
This change addressed the warning.
> Use -O0 alongside -ggdb3 to address compiler warning

- docs/docfiles/intro.rst
- docs/docfiles/urls.json
- docs/docfiles/user_guides/QuickStart.rst
- docs/docfiles/user_guides/manual/dpctl/basic_concepts.rst
Made explicit the intended use of event to ensure completion of submitted operation from host side of the application.
Removed note that `dpctl.lsplatform()` is new in dpctl 0.7
Closes #937 
Closes #938 
@alexandraepan
> Edits to documentation per review feedback

- libsyclinterface/source/dpctl_sycl_kernel_bundle_interface.cpp
Use "sycl/ext/oneapi/backend/level_zero.hpp" instead of deprecated path "sycl/backend/level_zero.hpp" but that header path is now deprecated.
> Include sycl/ext/oneapi/backend/level_zero.hpp instead of deprecated path

- libsyclinterface/helper/include/dpctl_dynamic_lib_helper.h
This PR adds call to `error_handler` into the branch of `DynamicLibHelper::getSymbol` where it returns `nullptr` because of an error,
> Use error_handler if getSymbol encountered error and returns nullptr

- cmake/IntelDPCPPConfig.cmake
Compiler oneAPI DPC++ 2022.2.0 no longer requires use of `--dpcpp` option.
The work-in-progress compiler generates warnings when `--dpcpp` is used. Removing this flag now to be future-proof.
> Removed use of unnecessary compiler option --dpcpp in vendored compiler config cmake script

- CHANGELOG.md
Populated `CHANGELOG.md` with changes between 0.13.0 tag and base of this PR.
> Populated change-log with changes in 0.14 thus far

- CHANGELOG.md
Refined an item in 0.14 changelog regarding scope of changes from #913.
> Expanded on content of changes in pr 913

- .github/workflows/python_style_checks.yml
Some jobs of python-style-check workflow used matrix to choose Python version, resulting in python-version dependent job names. This made it cumbersome to refer to such jobs in branch protection rules.
This PR removes use of matrix, hard-coding the Python version name inside the parameters of respective jobs.
> [Chore] Removed use of matrix in python style check workflow jobs

- CMakeLists.txt
- examples/pybind11/external_usm_allocation/CMakeLists.txt
- examples/pybind11/onemkl_gemv/CMakeLists.txt
- examples/pybind11/use_dpctl_syclqueue/CMakeLists.txt
Updated version of pybind11 fetched by cmake to 2.10.1
> Use pybind11 2.10.1

- dpctl/tests/test_usm_ndarray_ctor.py
This PR modifies the test which unconditionally exercises operations on arrays with float16 data-type.
The test fails on HW without float16 native support. 
This PR make test only do that if HW has aspect fp16. Test also adds step to unconditionally use float32
to maintain coverage level on all platforms.
> Condition test exercising fp16 support on availability of HW support

- libsyclinterface/cmake/modules/FindIntelSycl.cmake
Introduced alternative names for sycl.lib on Windows to support OS compiler
This prepares dpctl for forthcoming changes in Intel(R) oneAPI DPC++ release.
> Introduced alternative names for sycl.lib on Windows

- libsyclinterface/include/dpctl_sycl_queue_interface.h
Fixed usage of non-templated `unwrap(KRef)` to `unwrap<kernel>(KRef)` since implementation was changed in #960.
> Fixed usage of unwrap in comment to templated one

- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tensor/libtensor/source/device_support_queries.cpp
- examples/pybind11/onemkl_gemv/sycl_gemm/_onemkl.cpp
Chore: use "auto const &api" instead of "auto &api" for dpctl_capi instances.
This changes makes it explicit that `api` is not modified.
> Chore: use const qualifier for dpctl_capi references.

- MANIFEST.in
- libsyclinterface/CMakeLists.txt
- libsyclinterface/include/Config/dpctl_config.h.in
Incremented `__SYCL_COMPILER_2023_SWITCHOVER` by a day to fix compilation issue with Intel(R) oneAPI DPC++ 2022.2.1 compiler. 
Adjusted `libsyclinterface/CMakeLists.txt` to copy `*.hpp` files into `dpctl/include`. 
Adjusted `MANIFEST.in` to copy `dpctl/include/*.hpp` files into the installation folder.
> Fix fallout of recent changes

- dpctl/_sycl_queue.pyx
Fixed unintended syntax in forming exception in SyclQueue constructor code
Syntax parsed as a call operator on string type. Instead it was meant as concatenation operation.
This PR fixes that.
> Fixed unintended syntax in forming exception of SyclQueue constructor

- dpctl/tensor/libtensor/source/triul_ctor.cpp
Use full qualifier in template parameter to fix build break on Windows with CPython 3.10
> Fixed compilation error on triul_ctor on Windows with Python 3.10

- .flake8
- .github/workflows/conda-package.yml
- dpctl/sycl.pxd
- examples/cython/use_dpctl_sycl/.gitignore
- examples/cython/use_dpctl_sycl/README.md
- examples/cython/use_dpctl_sycl/setup.py
- examples/cython/use_dpctl_sycl/tests/test_example.py
- examples/cython/use_dpctl_sycl/use_dpctl_sycl/__init__.py
- examples/cython/use_dpctl_sycl/use_dpctl_sycl/_cython_api.pyx
- examples/cython/use_dpctl_sycl/use_dpctl_sycl/utils.hpp
This PR adds `dpctl/sycl.pxd` to alleviate the need for Cython extension authors to redeclare SYCL RT classes in their code, and to provide routines to cast from SYCLInterface library's opaque pointers to Sycl class pointers and back. 
Example is added to test and to illustrate the usage of `dpctl.sycl` in Cython.
> Introduce dpctl/sycl.pxd

- CHANGELOG.md
- dpctl/_sycl_platform.pyx
- dpctl/tensor/_dlpack.pyx
USM allocation must be bound to the default context. When producing DLPack, 'device_id; is populated with id of the ancestor root device.
> Added support for consuming DLPack allocated on a sub-device

- CHANGELOG.md
- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/_device_attributes_checks.py
- examples/pybind11/use_dpctl_syclqueue/tests/test_queue_device.py
- examples/pybind11/use_dpctl_syclqueue/use_queue_device/__init__.py
- examples/pybind11/use_dpctl_syclqueue/use_queue_device/_example.cpp
- libsyclinterface/include/dpctl_sycl_device_interface.h
- libsyclinterface/source/dpctl_sycl_device_interface.cpp
- libsyclinterface/tests/test_sycl_device_interface.cpp
This PR implements `dpctl.SyclDevice.sub_group_sizes` property as requested in #975
> Add sycl device sub group sizes property

- libsyclinterface/include/Config/dpctl_config.h.in
Due to 2022.2.1 compiler release on Windows, we need to increment `__SYCL_COMPILER_2023_SWITCHOVER` timestamp to fence out code intended for 2023, since currently available compiler does not have those changes yet.
> Incremented 2023-SWITCHOVER timestamp

- conda-recipe/meta.yaml
This ensures that dpctl built with 2023 compiler
can be installed into 2022 environment, as they are ABI incompatible
With this change, `dpctl` will have dependency depending on the version of the compiler used during building. 
If building with 2023, we are going to have 
```
dependencies:
- dpcpp-cpp-rt >=2023.0,<2024.0a0
```
> Use pin-compatible dpcpp-cpp-rt to restrict range of dpcpp-cpp-rt

- .pre-commit-config.yaml
Checking out `pycqa/flake8` from gitlab has stopped working (see https://github.com/IntelPython/dpctl/actions/runs/3473890443/jobs/5808023582). 
This PR updates to use github.com/pycqa/flake8` instead. It also updates tags
of individual components to the latest at the time of commit.
> Updated versions of checks in pre-commit, use github for flake8

- dpctl/tensor/_usmarray.pyx
Expanded doc-string for `to_device` method of `usm_ndarray` class.
> Expanded doc-string of dpctl.tensor.usm_ndarray.to_device

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Fixed missing copy for full() function if fill_value is array.
Added tests that check order and strides for dpctl.tensor.full() function.
> Fixed missing copy for dpctl.tensor.full() function if fill_value is array

- dpctl/tensor/_dlpack.pyx
Expanded doc-string for `dpctl.tensor.from_dlpack` function.
> Expanded docstring for  method

- CHANGELOG.md
Expanded change-log to mention changes that went in since 0.14.0rc2 tag.
> Final preparations in CHANGELOG for 0.14.0 release

- .github/workflows/conda-package.yml
- CHANGELOG.md
- dpctl/tests/setup_cython_api.py
- dpctl/tests/test_sycl_queue.py
Cython extension built during test run to exercise Cython only functions used to skip the test if extension building were to run into problem.
This PR makes it fail the test instead. Otherwise the problem may go undetected for a long time.
> Error building Cython test extension must fail the tests, not skip it

- conda-recipe/build.sh
- conda-recipe/meta.yaml
- libsyclinterface/cmake/modules/GetLevelZeroHeaders.cmake
Using system `git` in conda environment may be problematic due to inconsistency in dependent libraries. 
For example, #1000 and #999 were affected by this:
```
03:35:37.053600 git.c:460               trace: built-in: git clone https://github.com/oneapi-src/level-zero.git
Cloning into 'level-zero'...
03:35:37.060849 run-command.c:655       trace: run_command: git remote-https origin https://github.com/oneapi-src/level-zero.git
03:35:37.063415 git.c:750               trace: exec: git-remote-https origin https://github.com/oneapi-src/level-zero.git
03:35:37.063456 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/oneapi-src/level-zero.git
/usr/lib/git-core/git-remote-https: symbol lookup error: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: …
```
> Fix inconsistency system git and conda env

- dpctl/tensor/_types.pxi
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
This change fixes formation of `TypeError` message string.
Closes #998. 
It also reworks `dtype` argument validation, fixing unreferenced issue with `dpt.usm_ndarray(1, dtype=np.dtype(">f4"))`.
> Fixed gh-998: exception raised while forming an expected TypeError exception message  

- dpctl/apis/include/dpctl4pybind11.hpp
dpctl_capi ctor initialize all members, dtor resets smart pointers
This addressed accessing uninitialized variables SDL tool warnings.
> Fixed marginal memory leak in singleton class dpctl_capi 

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Fixed error in pybind11 for casting some types in dpctl.tensot.full() function.
Added tests.
> Fixed error in cast dtype for full() function.

- dpctl/_backend.pxd
- dpctl/_sycl_device.pyx
- dpctl/tests/_device_attributes_checks.py
- examples/pybind11/use_dpctl_syclqueue/tests/test_queue_device.py
- examples/pybind11/use_dpctl_syclqueue/use_queue_device/__init__.py
- examples/pybind11/use_dpctl_syclqueue/use_queue_device/_example.cpp
- libsyclinterface/include/dpctl_sycl_device_interface.h
- libsyclinterface/source/dpctl_sycl_device_interface.cpp
- libsyclinterface/tests/test_sycl_device_interface.cpp
This implements #1004, by exposing `dpctl.SyclDevice.partition_max_sub_devices` property.
SyclInterface library gets `DCPTLDevice_GetPartitionMaxSubDevices(const DPCTLSyclDeviceRef)` function.
Tests are added to both `dpctl` and SyclInterface library.
@dmishura
> Adds SyclDevice.partition_max_sub_devices

- dpctl/tensor/libtensor/include/utils/strided_iters.hpp
Fixes https://github.com/IntelPython/dpctl/issues/1007.
This include directive seems to have been forgotten and it is impossible for me to compile dpctl without it.
---
> MAINT Include tuple in 'utils/strided_iters.hpp'

- .github/workflows/conda-package.yml
- .github/workflows/pre-commit.yml
Given unexpected pre-commit failure in #1008 due to `clang-format`, add a step to `pre-commit.yaml` workflow to output the version of `clang-format` used. 
This would allow to quickly tell if the pre-commit failure was caused by version update of `clang-format` in GitHub runner image.
> Added step to display version of clang-format used in pre-commit workflow

- .github/workflows/conda-package.yml
`ubuntu-latest` image now refers to Ubuntu-22.04. Conda packages built there can be installed on Ubunutu 20.04 due to 
```
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
```
This changes uses ubuntu-20.04 image for "build_linux" and "test_linux" steps.
> Conda packages must be built with Ubuntu 20.04

- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
`dpctl.tensor.usm_ndarray` constructor sets writable flag.
`__setitem__` raises on attempt to modify read-only array.
> Make usm_ndarray be writable by default

- dpctl/__main__.py
- dpctl/tests/test_service.py
It is pretty cumbersome to use DPCTL to enumerate devices typing `python -c "import dpctl; dpctl.lsplatform(verbosity=2)"`. 
This change adds support for enumerating devices in all visible platforms to `__main__`, replacing the above with much easier to type `python -m dpctl -f`.
```
(dev_dpctl) opavlyk@opavlyk-mobl:~/repos/dpctl$ python -m dpctl --help
usage: __main__.py [-h] [--includes] [--cmakedir] [--library] [-l] [-e] [-s]
optional arguments:
-h, --help       show this help message and exit
--includes       Include flags dpctl headers.
--cmakedir       CMake module directory, ideal for setting -DDPCTL_ROOT in CMake.
--library        Linker flags for SyclInterface library.
-f, --full-list  Enumerate system platforms, using dpctl.lsplatform(verbosity=2)
-l, --long-list  Enumerate …
```
> Added support for python -m dpctl -l to list platforms

- dpctl/tensor/_ctors.py
Fixed a typo in `_map_to_device_dtype` function pointed out by @antonwolf
Also additional small change of creating `dtc` atop the function definition and using it throughout.
> Fixed a typo in _map_to_device_dtype pointed out by @antonwolf

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_for_reshape.cpp
- dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp
- dpctl/tensor/libtensor/source/eye_ctor.cpp
- dpctl/tensor/libtensor/source/full_ctor.cpp
- dpctl/tensor/libtensor/source/linear_sequences.cpp
- dpctl/tensor/libtensor/source/triul_ctor.cpp
This PR ass  ``dpctl::utils::queues_are_compatible`` signature for list of `usm_ndarray` instances.
Instead of the call
```c++
queues_are_compatible(exec_q, {X1.get_queue(), X2.get_queue()})
```
for `usm_ndarray` instances `X1` and `X2`, one can now say
```c++
queues_are_compatible(exec_q, {X1, X2})
```
I verified this locally when compiling https://github.com/oleksandr-pavlyk/kmeans_dpcpp/
> Add queues_are_compatible signature for list of usm_ndarray instances

- dpctl/tensor/libtensor/source/device_support_queries.cpp
Change `default_device_int_type` to return 'l' (code for for long type).
This should make `dpt.arange(10)` be int32 on Windows.
> Change default_device_int_type to return 'l' for long.

- dpctl/tensor/libtensor/include/kernels/constructors.hpp
- dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp
- dpctl/tensor/libtensor/include/utils/type_utils.hpp
Implemented and deployed `validate_type_for_device<T>(q)` utility function.
This check would produce more succinct error message:
```
In [2]: dpt.arange(0, 10, dtype='f8')
RuntimeError                              Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 dpt.arange(0, 10, dtype='f8')
File ~/repos/dpctl/dpctl/tensor/_ctors.py:603, in arange(start, stop, step, dtype, device, usm_type, sycl_queue)
601     _step = sc_ty(1)
602 _start = _first
--> 603 hev, _ = ti._linspace_step(_start, _step, res, sycl_queue)
604 hev.wait()
605 if is_bool:
RuntimeError: Device Intel(R) Graphics [0x9a49] does not support type 'double'
```
> Implemented and deployed validate_type_for_device<T>(q)

- dpctl/tensor/_copy_utils.py
This should improver transfer timing per GPU optimization guidelines
> Use USMHost as underlying buffer for result

- dpctl/tensor/_device.py
- dpctl/tests/test_usm_ndarray_ctor.py
Added method `dpctl.tensor.Device.print_device_info` for user convenience.
> Device print info

- dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
- dpctl/tensor/libtensor/tests/test_copy.py
This PR does not add new functionality, but cleans up C++ sources of copy-and-casting kernels.
1. A routine to simplify iteration space always sets `shape`, `src_strides` and `dst_strides` pointers.
2. Added `const` qualifiers for some arguments in implementation functions to simplify code and to better reflect the intent.
3. Upgraded `dpctl/tensor/libtensor/tests/test_copy.py` script to run on Iris Xe without support for double precision floating point numbers and to comply with compute follows data.
> Simplify iteration tweak

- dpctl/tensor/libtensor/include/kernels/constructors.hpp
- dpctl/tests/test_usm_ndarray_ctor.py
This PR changes to `_tensor_impl` with `-fno-associate-math` compiler flag. See https://clang.llvm.org/docs/UsersManual.html#controlling-floating-point-behavior for how to control FP-behavior in clang.
This fixes output of `dpt.linspace(dpt.finfo('f4').max, dpt.finfo('f4').max, num=16, dtype='f4')` which unexpectedly contained `nan` values as discovered by @npolina4
> Use no associative math

- .github/workflows/conda-package.yml
As pointed out by @antonwolfy, conda tar-balls built for Py-3.10 on Windows were in fact not uploaded to the development channel.
This PR corrects that oversight.
> Upload tar-balls to dev-channel for Windows and Python 3.10 too

- .github/workflows/generate-coverage.yaml
- .github/workflows/generate-docs.yml
- .github/workflows/os-llvm-sycl-build.yml
This PR updates `os-llvm-sycl-build` workflow to use newer component libraries.
> Updated TBB, OCL-CPU, OCL-FPGAEMU versions in os-llvm-sycl-build workflow

- dpctl/tensor/libtensor/include/utils/type_utils.hpp
Utility `validate_type_for_device<T>(sycl::device &)` modified to flag `std::complex<double>` for devices with no `aspect::fp64`.
To test, I used:
```
In [1]: import dpctl.tensor as dpt, dpctl.tensor._tensor_impl as ti
In [2]: dpt.ones(10, dtype='c16')
RuntimeError                              Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 dpt.ones(10, dtype='c16')
File ~/repos/dpctl/dpctl/tensor/_ctors.py:708, in ones(sh, dtype, order, device, usm_type, sycl_queue)
700 dtype = _get_dtype(dtype, sycl_queue)
701 res = dpt.usm_ndarray(
702     sh,
703     dtype=dtype,
(...)
706     buffer_ctor_kwargs={"queue": sycl_queue},
707 )
--> 708 hev, _ = ti._full_usm_ndarray(1, res, sycl_queue) …
```
> Utility validate_type_for_device must flag complex128 as it flags double

- libsyclinterface/include/Config/dpctl_config.h.in
- libsyclinterface/source/dpctl_sycl_kernel_bundle_interface.cpp
Corrected behavior for `-DDPCTL_ENABLE_L0_PROGRAM_CREATION=OFF`
Shortened preprocessor variable name from
`DPCTL_ENABLE_L0_PROGRAM_CREATION` to `DPCTL_ENABLE_L0_PROGRAM`.
Placed additional uses of L0-specific functions it preprocessor conditioned sections.
Tested with both `python scripts/build_locally.py` and `python scripts/build_locally.py --no-level-zero`.
> Corrected behavior for DPCTL_ENABLE_L0_PROGRAM_CREATION=OFF

- libsyclinterface/include/Config/dpctl_config.h.in
- libsyclinterface/source/dpctl_sycl_kernel_bundle_interface.cpp
Changes from gh-1039 inadvertently broke L0 program creation support, resulting in failure of test
test_sycl_program.py::test_create_program_from_spirv_l0
This PR fixes it, while still resolving issues raised in gh-1039.
> Fix loss of L0-program creation from gh-1039

- dpctl/tensor/_print.py
- dpctl/tests/test_usm_ndarray_print.py
> Fixed spacing of dtype string in array printing

- .github/workflows/conda-package.yml
- CMakeLists.txt
Set `DOWNLOAD_EXTRACT_TIMESTAMP FALSE` in `FetchContet_Declare` cmake functions per CML0135-related warning.
> Set DOWNLOAD_EXTRACT_TIMESTAMP FALSE per cmake policy CMP0135

- dpctl/tensor/_ctors.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_dlpack.py
Closes gh-1038.
Added checks to `dpctl.tensor.empty` and `dpctl.tensor.zeros` to disallow creation of arrays with data-types not natively supported by the requested device. 
Also added check to `dpctl.tensor.usm_ndarray` constructor to raise the error if an attempt to create an instance requests data type not natively supported by the device.
> Fix gh 1038 empty zero check device aspects

- dpctl/tensor/libtensor/include/utils/strided_iters.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
Added `dpctl.tensor._tensor_impl._contract_iter3` utility to simplify iteration space over indices of 3 arrays with the same shape, but possibly different strides.
```
In [1]: import dpctl.tensor as dpt, dpctl.tensor._tensor_impl as ti, dpctl
In [4]: import itertools
In [5]: ti._contract_iter2((2, 5, 3), (15, -3, 1), (0,0,1))
Out[5]: ([10, 3], [3, 1], -12, [0, 1], 0)
In [6]: or_s = set( (15*i0 - 3*i1 + i2, i2, 15*i0 - 3*i1 + i2) for i0,i1,i2 in itertools.product(range(2), range(5), range(3)) )
In [7]: alt_s = set( (3*i0 + i1 - 12, i1, 3*i0 + i1 - 12) for i0,i1 in itertools.product(range(10), range(3)) )
In [8]: or_s == alt_s
Out[8]: True
```
This utility is going to be useful in implementation of binary functions, `_binary_func( in1, in2, out)`, example of which is `out = in1 + in2`.
> Added _contract_iter3 utility to simplify iteration space over 3 arrays

- dpctl/tensor/_manipulation_functions.py
The implementation takes an iterable of shapes. This is useful for implementation of general broadcasting function.
Otherwise, no functional change.
> CHORE: Factored out _broadcast_shape implementation

- dpctl/tensor/_device.py
- dpctl/tests/test_usm_ndarray_ctor.py
Added `dpctl.tensor.Device.__eq__` and `dpctl.tensor.Device.__hash__` methods and tests.
```
x = dpt.empty(10)
y = dpt.empty(10)
assert x.device == y.device 
```
The assertion used to fail, but returns `True` now.
> Make dpctl tensor device hashable, added equality comparison

- .pre-commit-config.yaml
- dpctl/_sycl_queue.pyx
- dpctl/tests/test_sycl_queue.py
This fixes lack of validation in `dpctl.SyclQueue(device="gpu")` call to constructor.
> Fix sycl queue argument validation

- .github/workflows/python_style_checks.yml
- .pre-commit-config.yaml
This change fixes version of black specified in pre-commit config and in python_style_check workflow to 22.12.0
Latest release 23.1.0 suggests further changes to previously passing code.
> Use black 22.12.0

- .github/workflows/conda-package.yml
The registry entry makes the OCL CPU library in the environment known to the loader, enabling the CPU SYCL device.
> Clean-up PowerShell script to add registry expected by OpenCL loader

- dpctl/tensor/libtensor/include/utils/strided_iters.hpp
The target ordering used to be based on absolute values of the first vector of strides, now it uses lexicographic ordering of tuples of absolute values of all strides involved.
This enables iteration space reduction for examples where all strides in the first vector are all zero, like in the example arising from
```
dpctl.tensor.full((2,3,4,), dpctl.tensor.asarray(1))
```
The following two invocations show that iteration space used is 1d:
```
onetrace -d -v --demangle python -c \
"import dpctl.tensor as dpt; x = dpt.ones((30, 40, 50), dtype='i4'); y = dpt.empty_like(x, dtype='f4'); y[:] = x"
onetrace -d -v --demangle python -c \
"import dpctl.tensor as dpt; dpt.full((2,3,4), dpt.asarray(1, dtype='f4'))"
```
> Changed simplify_iteration_two_strides, simplify_iteration_three_strides

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_sycl_usm.py
- dpctl/tests/test_usm_ndarray_ctor.py
Closes #1049 
This PR adds 3 new C-API for usm_ndarray: 
- `void UsmNDArray_SetWritableFlag(usm_array arr, int flag)` : Set WRITABLE flag of `arr` if `bool(flag)` is `True`, and clears it otherwise
- `object UsmNDArray_MakeFromMemory(int nd, const Py_ssize_t *shape, int typenum, c_dpmem._Memory memobj, Py_ssize_t offset)`: create `usm_ndarray` of given shape and data-type from USM-memory object and offset
- `object UsmNDArray_MakeFromPtr(size_t nelems, int typenum, DPCTLSyclUSMRef ptr, DPCTLSyclQueueRef QRef, object owner)`:  create 1D `usm_ndarray`  of requested data-type from pointer and queue reference; `owner=None` is interpreter as transfer of memory ownership, and memory will be deallocated once the usm_ndarray instance is deleted. If `owner` is not `None`, deleter of `usm_ndarray` …
> Add usm_ndarray creation c-api

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Changed generating integer output for dpctl.tensor.linspace() function like in numpy.linspace().
``` python
xp.linspace(0.1, 9.1, 11, endpoint=True, dtype=int)
array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
> Changed generating integer output for linspace() function.

- dpctl/tensor/__init__.py
- dpctl/tensor/_print.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_print.py
Exposed usm_ndarray_repr and usm_ndarray_str in dpctl.tensor.
This allows extensions and subclasses to leverage usm_ndarray_repr for printing with custom prefixes/class names, formatting, etc.
Unblocks IntelPython/dpnp#1279
> usm_ndarray repr, str exposed in dpctl.tensor

- dpctl/_backend.pxd
- dpctl/memory/_memory.pyx
- libsyclinterface/include/dpctl_sycl_enum_types.h
- libsyclinterface/include/dpctl_sycl_usm_interface.h
- libsyclinterface/source/dpctl_sycl_usm_interface.cpp
- libsyclinterface/tests/test_sycl_usm_interface.cpp
- DPCTLUSM_GetPointerType used to return a global string literal
and had an API that is different from all other libsyclinterface
functions that return a C string.
Returning a pointer to a global literal as opposed to a heap
allocated memory meant the ownership of the pointer was not
clear when crossing language boundary.
Calling DPCTLCString_Delete on the previously returned const char*
will cause a segfault
- The PR introduces an enum for usm types and returns an enum value
from DPCTLUSM_GetPointerType.
- All Python API is unaffected.
Existing unit tests have been updated.
No
Yes
> Changes the API for DPCTLUSM_GetPointerType.

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
Allocation for the result array did not honor `usm_type` of the argument for `dpctl.tensor.tril`, `dpctl.tensor.triu` functions.
This PR fixes that and adds tests.
> Added missing usm_type to tril() and triu() functions.

- dpctl/_backend.pxd
- dpctl/enum_types.py
- dpctl/memory/_memory.pxd
- dpctl/memory/_memory.pyx
- dpctl/tests/test_sycl_usm.py
- libsyclinterface/include/dpctl_sycl_enum_types.h
In compute follows data we stipulate DEVICE<SHARED<HOST for the usm_type coercion logic.
It makes sense to keep integral values associated with the enum consistent with that mental model.
> Reordered DPCTL_USM_HOST and DPCTL_USM_SHARED

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/_stride_utils.pxi
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
* Renamed C-API:
`UsmNDArray_MakeFromMemory` -> `UsmNDArray_MakeSimpleFromMemory`
`UsmNDArray_MakeFromPtr` -> `UsmNDArray_MakeSimpleFromPtr`
* Added C-API:
`UsmNDArray_MakeFromPtr` to create strided array.
* Added pyx-capi test for the new C-API.
* Exposed C-API via dpctl_capi.
> Extended UsmNDArray creation C-API

- .github/workflows/conda-package.yml
This PR tweaks conda-package workflow to use `python -m dpctl -f` to display SYCL environment information instead of less verbose `python -c "import dpctl; dpctl.lsplatform()"`, which is equivalent to `python -m dpctl -l`.
`python -m dpctl -f` will also display driver version of each available SYCL device. Hoping this to provide more insight into the cause for #1063
> Make test_windows:smoke test 2 more verbose

- dpctl/tests/test_usm_ndarray_print.py
This PR solves the issue #1069.
The PR adds the `has_aspect_fp64` condition in the `test_usm_ndarray_print.py::TestPrintFns::test_print_rep` to check for double type support on devices and allows that this test passes on Iris Xe.
> Add double type support check condition for test_print_repr

- conda-recipe/build.sh
- conda-recipe/meta.yaml
Use compiler CFG files for Intel LLVM to use conda's sysroot and toolchain
> Intel LLVM is to use conda's gcc toolchain, sysroot and target libraries

- dpctl/tensor/_dlpack.pyx
- dpctl/tensor/include/dlpack/README.md
- dpctl/tensor/include/dlpack/dlpack.h
- dpctl/tests/test_usm_ndarray_dlpack.py
Fixes gh-1071. Updated DLPack to 0.8 with support for `kDLBool` elemental tensor data type.
Exception reported #1071 would arise every time array would not start at the beginning of the underlying allocation, i.e. `x0 = dpt.arange(6); x1 = x0[::-2]; dpt.from_dlpack(x1)` fails, but `x0 = dpt.arange(7); x1 = x0[::-2]; dpt.from_dlpack(x1)` works. 
Test was added to cover such inputs too.
> Fix gh 1071 from dlpack

- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
Mark static function ``usm_ndarray_types::typenum_to_lookup_id`` as `const`.
This allows to call it for `const struct` references.
> Mark static function usm_ndarray_types::typenum_to_lookup_id const

- dpctl/_sycl_queue_manager.pxd
- dpctl/_sycl_queue_manager.pyx
- dpctl/memory/_memory.pyx
- dpctl/tensor/_device.py
- dpctl/tensor/_dlpack.pyx
- dpctl/tests/test_sycl_queue_manager.py
- dpctl/tests/test_usm_ndarray_dlpack.py
This PR creates dedicate queue cache with context, device pair being a key.
Use of this cache in `dpctl.tensor.Device`, `dpctl.tensor.from_dlpack` and in `dpctl.memory` allows to returns the same queue for a given device, streamlining user experience with compute-follows-data model.
```
(dev_dpctl) opavlyk@opavlyk-mobl:~/repos/dpctl$ ipython
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: dpt.Device.create_device("gpu") == dpt.Device.create_device("gpu")
Out[2]: True
In [3]: x = dpt.linspace(0, 3 + 2j, num=1000)
In [4]: y = dpt.from_dlpack(x)
In [5]: x.sycl_queue == y.sycl_queue
Out[5]: True
In [6]: …
```
> Cached device store

- conda-recipe/meta.yaml
Dropping `- {{ compiler('c') }}` and bumping up minimal version of DPC++.
> Require DPC++ >=2023.0.0, no need to require c-compiler

- dpctl/_sycl_queue_manager.pyx
- dpctl/tests/test_sycl_queue_manager.py
Per discussion in gh-1076, this adds support for filter-string input in `get_device_cached_queue` utility function:
```
In [2]: import dpctl._sycl_queue_manager as qm
In [3]: qm.__pyx_capi__
Out[3]:
{'get_current_queue': <capsule object "struct PySyclQueueObject *(int __pyx_skip_dispatch)" at 0x7fe2260bcc30>,
'get_current_device_type': <capsule object "PyObject *(int __pyx_skip_dispatch)" at 0x7fe2260bcc60>,
'get_current_backend': <capsule object "PyObject *(int __pyx_skip_dispatch)" at 0x7fe2260bcc90>,
'get_device_cached_queue': <capsule object "PyObject *(PyObject *, int __pyx_skip_dispatch)" at 0x7fe2260bccc0>}
In [4]: qm.get_device_cached_queue("cpu")
Out[4]: <dpctl.SyclQueue at 0x7fe226945b80>
In [5]: qm.get_device_cached_queue("gpu")
Out[5]: <dpctl.SyclQueue at …
```
> Cached queue use filter string support

- dpctl/tensor/_ctors.py
- dpctl/tests/test_usm_ndarray_ctor.py
> Fixed meshgrid() function with empty input.

- conda-recipe/build.sh
- conda-recipe/dpctl-post-link.sh
The post-link creates a symbolic link from `$PREFIX/etc/OpenCL/vendors/intel-gpu.icd` to `/etc/OpenCL/vendors/intel.icd` if one exists.
This is a work-around to ensure that OpenCL GPU device from system installation can be found by OpenCL loader in ``intel-opencl-rt`` forthcoming package.
> This PR modifies conda-recipe to add post-link to dpctl

- conda-recipe/build.sh
- conda-recipe/dpctl-post-link.sh
- conda-recipe/dpctl-pre-unlink.sh
This PR addresses some shortcomings introduced in gh-1081
conda prunes empty folders, so the dpctl tar-ball did not contain empty etc/OpenCL/vendors folder. Solved by create a dummy `.dpctl_readme` file in that folder.
The script dpctl-post-link.sh contained a type in the filename it was checking should not exist.
> Fixes to dpctl-post-link prior changes gh-1081

- conda-recipe/bld.bat
- dpctl/CMakeLists.txt
- dpctl/tensor/CMakeLists.txt
Tweaked `bld.bat` to account for possible folder names in `Library\lib\clang`.
Made the logic of patching `Windows-IntelLLVM.cmake` in conda package for cmake 3.22 dependent of existence of the folder.
Modified `CMakeLists.txt` to ensure that SDL flags `/NXCompat /DynamicBase` are correctly applied on Windows.
Worked around issue of oneAPI DPC++ integration with cmake 3.22 to ensure that `-fsycl-device-code-split=per_kernel` is correctly passed to the linker driver. 
Also ensure that `-fsycl-link-huge-device-code` is only added on Linux (option is [not supported](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/offload-openmp-and-parallel-processing-options/fsycl-link-huge-device-code.htm …
> Work-around for not applying -fsycl-device-code-split=per_kernel on Windows

- .github/workflows/generate-docs.yml
- docs/conf.in
- docs/requirements.txt
- [Y] Have you provided a meaningful PR description?
- [N] Have you added a test, reproducer or referred to an issue with a reproducer?
- [N] Have you tested your changes locally for CPU and GPU devices?
- [N] Have you made sure that new changes do not introduce compiler warnings?
- [N] If this PR is a work in progress, are you filing the PR as a draft?
> Enable Google Analytics

- dpctl/apis/include/dpctl_sycl_interface.h
dpctl_sycl_interface.h now includes kernel and kernel_bundle iface headers.
> dpctl_sycl_interface.h now includes kernel and kernel_bundle ifaces

- dpctl/apis/include/dpctl4pybind11.hpp
- dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp
Added synchronization for every `host_task` that is supposed to manage life-time of temporary vector with usm_host allocator.
> Try out a hunch that crashes are caused by dangling host_task-s.

- dpctl/apis/include/dpctl4pybind11.hpp
This means that it should not be making call to `UsmNDArray_GetOffset`. This restores correctness to checks for array region overlapping.
> get_minmax_offsets should always return data relative to data ptr

- dpctl/tensor/CMakeLists.txt
- dpctl/tensor/__init__.py
- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_indexing_functions.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp
- dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
- dpctl/tensor/libtensor/source/boolean_advanced_indexing.hpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tests/test_usm_ndarray_indexing.py
This PR adds implementation of kernels for boolean indexing. 
It adds `mask_positions`, `_extract`, `_place` and `_nonzero` functions that become
a foundation for forthcoming implementations of `dpt.place`, `dpt.extract`
and `dpt.nonzero`.
> Boolean indexing: extract, place, nonzero

- dpctl/tensor/_indexing_functions.py
- dpctl/tests/test_usm_ndarray_indexing.py
- Improved conformity to array API standard
- Added docstrings
> dpt.take and dpt.put changes

- dpctl/tensor/libtensor/include/kernels/boolean_advanced_indexing.hpp
This is needed to ensure that `0<=gid < size`.
> Class Strided1DIndexer must used min(gid, size-1)

- dpctl/tensor/_copy_utils.py
- dpctl/tests/test_usm_ndarray_indexing.py
Fix for 
```python
import dpnp
x = dpnp.random.randn(200)
x[x<0] = 0   # used to raise TypeError, expecting r.h.s. to be a 0-d usm_ndarray 
```
> Fix boolean mask asignment scalar

- dpctl/tensor/_indexing_functions.py
- dpctl/tests/test_usm_ndarray_indexing.py
This PR adds a check for an empty array for `vals` argument and throws a `ValueError` exception in case of truth as numpy and covers this case with test.
The PR solves #1104.
> Add an empty value check for dpt.place

- dpctl/tensor/_indexing_functions.py
- dpctl/tests/test_usm_ndarray_indexing.py
This PR complements #1105 .
The original behavior of `numpy.place` throws an exception when it gets  an empty array of `vals` argument
BUT if the `mask` argument contains all `False`, `numpy.place` works without exceptions ([example](https://github.com/numpy/numpy/blob/main/numpy/lib/tests/test_function_base.py#L1335)).
> Update empty vals check in dpt.place

- dpctl/tensor/_ctors.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tensor/_reshape.py
- dpctl/tests/test_usm_ndarray_manipulation.py
Minor changes throughout dpctl to improve array API conformity.
Function signature changes to match array API
Notably introduces finfo_object subclass of np.finfo. finfo_objects return eps, max, min, and smallest_normal as Python floats.
> Improve array API conformity

- conda-recipe/bld.bat
- conda-recipe/build.sh
- dpctl/CMakeLists.txt
- dpctl/tensor/CMakeLists.txt
- libsyclinterface/CMakeLists.txt
- scripts/build_locally.py
Make sure that `-fwrapv` is used on Linux, and `/GS /DynamicBase` is used on Windows. 
`script/build_locally.py` now has `--verbose` mode to invoke `cmake` with `-DCMAKE_MAKEFILE_VERBOSE:BOOL=ON`.
> Add sdl flags

- dpctl/tensor/_copy_utils.py
Closes gh-1089
Hardened `_copy_from_numpy_into` to handle `numpy.ndarray` inputs with USMMemory buffer as a base.
Copy-with-casting kernel to transfer content of numpy.ndarray to usm_ndarray is implemented using sycl::buffer used on ndarray's data-pointer. The pointer can not be a host-accessible USM pointer for the behavior to be well-defined.
This change should fix gh-1089
> Handle numpy arrays with usm memory underneath in dpctl.tensor.asarray  

- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_for_reshape.cpp
- dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp
- dpctl/tensor/libtensor/source/triul_ctor.cpp
Draft pull request for collecting host_tasks throughout dpctl to prevent dangling tasks, which are suspected to cause crashes.
May be related to #1063
> Host task cleanup

- dpctl/tensor/CMakeLists.txt
`"dpctl/tensor/_usmarray.pyx"` includes several `*.pxi` files, but this dependency was not reflect in cmake script. 
This PR addresses that oversight.
> Make dependency of _usmarray.pyx on *.pxi files explicit in cmake

- dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
Renamed inserter to __appender, moved functions into concat_impl namespace
For open-source SYCL bundle based on clang 17.0 and using GCC 10.2 toolchain compilation error about ambiguous call to inserter was encountered. This was because of name clash between the definition in this file and ``std::inserter``.
Renaming helped resolve that.
Thank you @ZzEeKkAa for reporting this issue.
> Fixed build break on Debian 11 with recent OS SYCL bundle

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/_device.py
- dpctl/tensor/_dlpack.pyx
- dpctl/tensor/_indexing_functions.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tensor/_print.py
- dpctl/tensor/_reshape.py
- dpctl/tensor/_usmarray.pyx
- dpctl/utils/_compute_follows_data.pyx
Closes gh-1114 and closes gh-1116.
A pass through doc-strings of dpctl.tensor functions and classes to improve rendering of the documentation and to expand docstring.
> Closes gh-1114 and gh-1116

- dpctl/tensor/libtensor/include/kernels/integer_advanced_indexing.hpp
- dpctl/tests/test_usm_ndarray_indexing.py
Closes #1126 
This PR fixes incorrect logic in the WrapIndex class.
The previous logic was implemented to handle cases where modulus returns negative, but broke the implementation for indices lower than `-max_item`.
This re-implementation solves this.
> dpctl.tensor.take negative index wrapping fix

- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
> Added support for argument axis with value None for dpctl.tensor.concat().

- dpctl/_sycl_device.pyx
Partially addresses gh-1098, improving timing of `dpctl.SyclDevice.filter_string` property on repeated invocations.
Fixed docstring of `filter_string` property.
Introduced internal `dpctl._sycl_device._cached_filter_string` stand-alone function that is decorated with ``functools.cache``.
Used that internal function in implementation of
`dpctl.SyclDevice.filter_string`.
Caching improved timing of `filter_string` property:
```
In [2]: d = dpctl.SyclDevice()
In [3]: %timeit d.filter_string
2.31 µs ± 42.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
Previously, the timing was around `200 ms`.
Tests already exist.
> Used functools.cache to cache filter_string property

- dpctl/tensor/_slicing.pxi
- dpctl/tests/test_usm_ndarray_indexing.py
Closes gh-1135.
Handle `x[True]` and `x[False]` as NumPy does, even though the behavior
may be undocumented. NumPy treats `True` as `None` (insert axis with size 1),
and treats `False` as `None` followed by empty slicing (insert axis with size 0).
Changed the logic of `_basic_slice_meta` utility function to correctly handle
boolean scalars (surprisingly, `insinstance(True, int)` evaluates to `True`).
0d arrays are handled on the same footing as the Python scalars.
Introduced `_is_integral` and `_is_boolean` utilty functions and used them in
`_basic_slice_meta` utility.
> Slicing bug gh 1135

- dpctl/tensor/_copy_utils.py
This PR replaces local implementation of `_has_memory_overlap` with call to `_tensor_impl._array_overlap` for efficiency and modularity.
> Used ti._array_overlap instead of local implementation

- dpctl/tensor/_copy_utils.py
- dpctl/tensor/_ctors.py
- dpctl/tensor/_device.py
- dpctl/tensor/_dlpack.pyx
- dpctl/tensor/_indexing_functions.py
- dpctl/tensor/_manipulation_functions.py
- dpctl/tensor/_print.py
- dpctl/tensor/_reshape.py
- dpctl/tensor/_usmarray.pyx
Closes gh-1115 by adding Sphinx's annotations to use of `usm_ndarray` class to produce cross-references.
Also replaces `out (usm_ndarray):` with `usm_ndarray:` in `Returns:` section of docstrings. Changes are tailored to
the returned type, of course.
> Closes gh-1115, fixes docstring's Returns sections

- .github/workflows/conda-package.yml
- .github/workflows/os-llvm-sycl-build.yml
Workflow to build `dpctl` with open source LLVM SYCL bundle was exercising test suite twice. Excising one of these runs. 
Workflow to build conda packages was attempting to install `anaconda-client` twice in upload step. Removed one install. 
Thank you @samaid for catching these inefficiencies.
> Fix redundant steps in workflows

- dpctl/memory/_memory.pyx
- dpctl/memory/_sycl_usm_array_interface_utils.pxi
- dpctl/tensor/_ctors.py
- dpctl/tensor/_usmarray.pyx
- dpctl/tests/test_tensor_asarray.py
Closes gh-1134
```
In [1]: import dpctl.tensor as dpt, dpctl
In [2]: m = dpt.ones((2,4), dtype='i4')
In [3]: w = dpt.full(4, -1)
In [4]: v = dpt.zeros(4)
In [5]: dpt.asarray([m, [w, v]])
Out[5]:
usm_ndarray([[[ 1.,  1.,  1.,  1.],
[ 1.,  1.,  1.,  1.]],
[[-1., -1., -1., -1.],
[ 0.,  0.,  0.,  0.]]], dtype=float32)
```
> Allow asarray to work on sequences of usm_array

- dpctl/tensor/_usmarray.pyx
While reviewing #1139 the following suboptimal behavior was highlighted:
```python
import dpctl.tensor as dpt, numpy as np
u, n = dpt.empty(5), np.ones(5, dtype="O")
u[...] = n
```
This example used to raise a cascade of exceptions starting with cryptic  "RuntimeError: Unrecogized typenum 17 encountered.", where typenum 17 corresponds to type object. The latest exception raised was `ValueError`.
After this change, the error message is crisper:
```
ValueError: Input of type <class 'numpy.ndarray'> can not be \
assigned to usm_ndarray because of unsupported data \
type 'object'
```
Tests exist.
> Improved error handling for usm_ndarray.__setitem__

- dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp
- No longer permits passing 2 as a flag (leftover from changes to clip and wrap modes)
> Validation of integer indexing modes fixed

- conda-recipe/meta.yaml
The test `test_cython_capi` requires setuptools, so it should be recorded in test requirements.
> Running tests needs setuptools for test_cython_capi test

- dpctl/tensor/_flags.pyx
- dpctl/tests/test_usm_ndarray_ctor.py
- FNC (F-not-C-contiguous) flag was returning CNF instead
- Added tests for correct behavior
> Fixed typo resulting in backwards FNC flag

- dpctl/tensor/libtensor/include/utils/offset_utils.hpp
- dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_for_reshape.cpp
- dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp
The service routine returns `nullptr` upon allocation failure. Modified use sites to handle such an exception.
> Handle device_allocate_and_pack allocation failure

- dpctl/tensor/_ctors.py
- dpctl/tests/test_tensor_asarray.py
Added support for `asarray` to create arrays from sequences of usm_ndarray objects allocated on different devices, and other Python sequences or numpy arrays.
```
In [1]: import dpctl, dpctl.tensor as dpt
In [2]: m = dpt.zeros((2, 4), dtype="i2", device="cpu")
In [3]: w = dpt.full(4, -1, device="opencl:gpu")
In [4]: res = dpt.asarray([m, [w, [0,] * 4 ]], dtype="f4", device="cpu")
In [5]: res
Out[5]:
usm_ndarray([[[ 0.,  0.,  0.,  0.],
[ 0.,  0.,  0.,  0.]],
[[-1., -1., -1., -1.],
[ 0.,  0.,  0.,  0.]]], dtype=float32)
In [6]: res.device
Out[6]: Device(opencl:cpu:0)
```
> As type supports sequence of arrays from multiple devices

- scripts/build_locally.py
This PR corrects help string associated with `cmake-opt` CLI option of `scripts/build_locally.py` script.
> Corrected help string for cmake-opts option of build_locally

- .github/workflows/conda-package.yml
In CI, shell scripts are executed with elevated privileges, hence OpenCL loader ignores variable `OCL_ICD_FILENAMES`. One must set a registry value. `intel-opencl-rt` comes with a script to do that.
It also comes with fixed `cl.cfg` file, so the step to modify `cl.cfg` in situ is no longer needed, and in fact corrupts the file.
> Adjusting test_windows step to work with intel-opencl-rt=2023.1.0

- .github/workflows/conda-package.yml
Since intel-opencl-rt=2023.1.0 has corrected logic to activate OpenCL CPU RT, the kludge can be removed.
> Got rid of setting OCL_ICD_FILENAMES now that intel-opencl-rt is fixed

- dpctl/tensor/CMakeLists.txt
- dpctl/tensor/__init__.py
- dpctl/tensor/_search_functions.py
- dpctl/tensor/_type_utils.py
- dpctl/tensor/libtensor/include/kernels/where.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tensor/libtensor/source/where.cpp
- dpctl/tensor/libtensor/source/where.hpp
- dpctl/tests/test_type_utils.py
- dpctl/tests/test_usm_ndarray_search_functions.py
Closes #1120 
This PR implements dpt.where function, which takes a condition array and two arrays of data, x1 and x2. The output is an array with elements from x1 where condition evaluates to true and x2 where condition is false. The output is of type determined by type promotion of x1 and x2.
i.e.,
```
In [4]: condition = dpt.asarray([False, True, True, True])
In [5]: x1 = dpt.asarray([1])
In [6]: x2 = dpt.asarray([2])
In [7]: dpt.where(condition, x1, x2)
Out[7]: usm_ndarray([2, 1, 1, 1])
```
> Implements dpctl.tensor.where

- dpctl/memory/__init__.py
- dpctl/memory/_memory.pyx
This PR addresses concern about use of non-descriptive RuntimeError exception in earlier versions raised in issue gh-1158
```
In [2]: import dpctl.memory as dpm
In [3]: dpm.MemoryUSMDevice( 1024 * 1024 * 1024 * 8)
USMAllocationError                        Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 dpm.MemoryUSMDevice( 1024 * 1024 * 1024 * 8)
File ~/repos/dpctl/dpctl/memory/_memory.pyx:783, in dpctl.memory._memory.MemoryUSMDevice.__cinit__()
781           SyclQueue queue=None, int copy=False):
782 if (isinstance(other, numbers.Integral)):
--> 783     self._cinit_alloc(alignment, <Py_ssize_t>other, b"device", queue)
784 else:
785     self._cinit_other(other)
File …
```
> Add USMAllocationError exception, use it for USM allocation failures

- dpctl/tensor/libtensor/include/utils/offset_utils.hpp
The `TwoOffsets_CombinedIndexer` takes two single offset indexers and combines their indexing results into a `TwoOffsets` struct.
The `UnpackedStridedIndexer` is a relative of `StridedIndexer`, except shapes and strides are provided as separate pointers. This increases its size, but may be useful to produce indexer that only computes the second offset using shape/strides stored in packed format for two-offset indexers.
These are going to be used in reduction kernels.
> Add TwoOffsets_CombinedIndexer, and UnpackedStridedIndexer

- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_operators.py
Replaced pattern `dpt.from_numpy(np.creation_op(...))` with `dpt.creation_op(...)` where applicable.
This change decreased test-suite runtime by 3 seconds.
> Use direct dpctl.tensor creation functions in tests instead of copying from host

- dpctl/tensor/libtensor/include/utils/type_dispatch.hpp
- dpctl/tests/test_tensor_asarray.py
Closes gh-1167.
Adds mapping of typenums corresponding to 'long long' and 'unsigned long long' to mapper typenum-to-look-up-id.
Test is added.
Generally, `long` and `ulong` are 64-bit on Linux, but NumPy must have a special-casing intended to covert Windows platform too:
```
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import numpy as np
In [2]: np.asarray(9223372036854775807).dtype.char
Out[2]: 'l'
In [3]: np.asarray(9223372036854775808).dtype.char
Out[3]: 'Q'
In [4]: np.dtype('ulonglong').char
Out[4]: 'Q'
```
> Fix for gh 1167

- dpctl/tensor/libtensor/include/kernels/copy_and_cast.hpp
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_numpy_ndarray_into_usm_ndarray.cpp
This PR works copy-and-cast functionality by simplifying underlying functors, removing specialized implementation for 2d arrays based on `CIndexer_array` as it is only very marginally faster than general strided implementation based on `CIndexer_vector`. 
This PR also adds special implementation for copy-with-casting of contiguous arrays, making type casting of contiguous arrays several times faster.
> Simplify copy and cast kernels

- dpctl/tensor/libtensor/include/kernels/where.hpp
- dpctl/tensor/libtensor/include/utils/offset_utils.hpp
- dpctl/tensor/libtensor/include/utils/strided_iters.hpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.cpp
- dpctl/tensor/libtensor/source/simplify_iteration_space.hpp
- dpctl/tensor/libtensor/source/tensor_py.cpp
- dpctl/tensor/libtensor/source/where.cpp
- dpctl/tests/test_usm_ndarray_search_functions.py
This PR implements simplify_iteration_space_4 and indexers for offsets in 4 arrays to resolve #1170.
Additionally, implements contract_iter4 and simplifies calls to std::min in strided_iters.
The issue was caused by an oversight in the mapping of elements between arrays in the strided where kernel. As the destination array was not being simplified, there was not a guarantee that the nth element of the destination corresponded to the correct element in x1 or x2.
> Fixes incorrect output in dpctl.tensor.where strided implementation

- .github/workflows/generate-coverage.yaml
- dpctl/tensor/_ctors.py
- dpctl/tests/test_sycl_queue_manager.py
This PR addresses deprecation warning reported when `dpt.arange(512*1024, 0, step=-1, dtype="i2")` is evaluated issued by NumPy 1.24.
This PR also fixes `test_sycl_queue_manager.py:: test_device_context_activates_nested_context` which fails with Python 3.11 due
to the change the exception type raised when attempting to nest contexts using object which does not implement context protocol.
> Fix tests for py3.11

- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
closes #1173 
Fixes an error related to `dpt.moveaxis` and adds new tests from numpy
> Fix implementation of dpctl.tensor.moveaxis() 

- dpctl/tensor/libtensor/source/boolean_advanced_indexing.cpp
- dpctl/tensor/libtensor/source/copy_and_cast_usm_to_usm.cpp
- dpctl/tensor/libtensor/source/copy_for_reshape.cpp
- dpctl/tensor/libtensor/source/integer_advanced_indexing.cpp
- dpctl/tensor/libtensor/source/triul_ctor.cpp
- dpctl/tensor/libtensor/source/where.cpp
Return events for computational tasks, rather than temp-clean up host tasks
This resolves a hang that Anton has uncovered. The gist of the bug is
```python
for i in range(op_count):
v[i] = dpt.empty_like(a[i], order='F', dtype=v_type)
ht_copy_ev[i], copy_ev = ti._copy_usm_ndarray_into_usm_ndarray(src=a[i], dst=v[i], sycl_queue=a_sycl_queue)
di._wait(copy_ev)
```
Here is `di` is a Pybind11 extensions, whose function `_wait` was implemented as
```c++
m.def("_wait", [](sycl::event e) -> void { e.wait(); }, "");
```
The script would hang on the second iteration of the loop if `di._wait` call. The hang disappears after the change in this commit. Out attempts to build a C++ reproducer have not been successful thus far.
> Return events for comp. tasks, rather than temp-clean up host tasks

- dpctl/tensor/_stride_utils.pxi
- dpctl/tests/test_usm_ndarray_ctor.py
Closes gh-1180
Utility determining contiguity flags of the newly constructed array was not setting F-contiguous flags where it should have in a special case of 1D array.
```
In [1]: import dpctl.tensor as dpt, dpctl
In [2]: x = dpt.ones((1,3,1))
In [3]: y = dpt.squeeze(x)
In [4]: x.flags, y.flags
Out[4]:
(  C_CONTIGUOUS : True
F_CONTIGUOUS : True
WRITABLE : True,
C_CONTIGUOUS : True
F_CONTIGUOUS : True
WRITABLE : True)
```
> Fix for gh-1180: missing F-contiguous flags after calling squeeze

- dpctl/tensor/_manipulation_functions.py
- dpctl/tests/test_usm_ndarray_manipulation.py
Use normalize_axis_tuple to normalize axis for all but expand_dims functions
Closes gh-1178
Adds test to cover gh-1178.
> Use normalize_axis_tuple to normalize axis for all functions but expand_dims

- dpctl/tensor/_print.py
In this PR, the recursive method used in `dpctl.tensor._print._nd_corners` function is replaced with an iterative method to improve performance.
`x_dpt = dpt.reshape(dpt.arange(6*6*117*117, dtype='i4'),(6,117,117,6))`
`%timeit -r 20 dpt.usm_ndarray_repr(x_dpt)`
New timing: 4.55 ms ± 645 µs per loop (mean ± std. dev. of 20 runs, 100 loops each)
Old timing: 6.43 ms ± 2.31 ms per loop (mean ± std. dev. of 20 runs, 100 loops each)
> print_corners

- .github/workflows/os-llvm-sycl-build.yml
- dpctl/tests/test_service.py
- dpctl/tests/test_sycl_context.py
- dpctl/tests/test_sycl_device.py
- dpctl/tests/test_sycl_event.py
- dpctl/tests/test_sycl_queue.py
- dpctl/tests/test_sycl_queue_memcpy.py
- dpctl/tests/test_sycl_usm.py
- dpctl/tests/test_tensor_asarray.py
- dpctl/tests/test_usm_ndarray_ctor.py
- dpctl/tests/test_usm_ndarray_dlpack.py
- dpctl/tests/test_usm_ndarray_manipulation.py
- dpctl/tests/test_usm_ndarray_operators.py
- dpctl/tests/test_usm_ndarray_print.py
- libsyclinterface/source/dpctl_sycl_device_manager.cpp
- libsyclinterface/source/dpctl_sycl_platform_interface.cpp
- pyproject.toml
Wrapped certain DPC++ RT function calls, such as `sycl::device::get_devices` and `sycl::platform::get_platforms` in try/except.
Added validation of object returned by cache builders.
Fixed typo in exception name in a Python test suite file, then run each test file individually with invalid setting of `ONEAPI_DEVICE_SELECTOR=cpu` to make sure the all execute fine. 
All but `test_sycl_queue_manager.py` pass. This one hangs due to filed problem in DPC++ Runtime.
Test suite continues to run clean with unset `ONEAPI_DEVICE_SELECTOR` environment variable, or it being set to a valid value, i.e. `ONEAPI_DEVICE_SELECTOR=*:cpu`.
> Better handle no devices systems

- conda-recipe/meta.yaml
This PR bumps up required version of DPC++ compiler to 2023.1.0.
It also restricts the version of sysroot that may be installed into build environment from below.
> Require DPC++ 2023.1.0 and later, require min version of sysroot
